{{- if .Values.opi.secretSmuggler.enable }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: secret-smuggler-{{ .Release.Revision }}
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      serviceAccountName: eirini-secret-smuggler
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
      containers:
      - name: smuggle
        {{- if .Values.opi.secret_smuggler_image }}
        image:  {{.Values.opi.secret_smuggler_image}}:{{ .Values.opi.image_tag }}
        {{- else }}
        image: eirini/secret-smuggler@{{ .Files.Get "versions/secret-smuggler" }}
        {{- end }}
        imagePullPolicy: Always
        env:
        - name: SECRET_NAME
          value: "{{ .Values.opi.secretSmuggler.scfSecretName }}"
        - name: UAA_NAMESPACE
          value: uaa
        - name: SCF_NAMESPACE
          value: {{ .Release.Namespace }}
        - name: OPI_NAMESPACE
          value: {{ .Values.opi.namespace }}
        - name: REGISTRY_CREDS_SECRET_NAME
          value: {{ .Values.opi.registry_secret_name }}
        - name: REGISTRY_URL
          {{- if .Values.opi.use_registry_ingress }}
          value: "https://registry.{{ .Values.opi.ingress_endpoint }}:443"
          {{- else if .Values.services.loadbalanced }}
          value: "https://registry.{{ .Values.env.DOMAIN }}:6666"
          {{- else }}
          value: "https://registry.{{ index .Values.kube.external_ips 0 }}.nip.io:6666"
          {{- end }}
        # This is to ensure the job starting only after the secrets are generated. The environment variable itself is not in use.
        - name: INTERNAL_CA_CERT
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.opi.secretSmuggler.scfSecretName }}"
              key: internal-ca-cert
        volumeMounts:
          - name: bits-config
            mountPath: /config
      volumes:
        - name: bits-config
          configMap:
            name: bits
            items:
              - key: bits-config-key
                path: bits-config
{{- end }}
