{{- if .Values.opi.rootfsPatcher.enable }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eirini-rootfs-patcher
  namespace: {{ .Release.Namespace }}
---
# Role to patch statefulsets
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rootfs-patcher-role
  namespace: {{ .Values.opi.namespace }}
rules:
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - list
  - update
---
# Binding to patch statefulsets
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rootfs-patcher-rolebinding
  namespace: {{ .Values.opi.namespace }}
roleRef:
  kind: Role
  name: rootfs-patcher-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: eirini-rootfs-patcher
  namespace: {{ .Release.Namespace }}

# BITS WAITER
---
# Role to list deployments
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bits-waiter-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
---
# Binding to list deployments
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bits-waiter-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: bits-waiter-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: eirini-rootfs-patcher
  namespace: {{ .Release.Namespace }}
{{- end }}
