{{- if .Values.opi.secretSmuggler.enable }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eirini-secret-smuggler
  namespace: {{ .Release.Namespace }}
---
# Role to get scf secrets
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-smuggler-role
  namespace: {{ .Release.Namespace}}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
---
# Binding to get scf secrets
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-smuggler-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: secret-smuggler-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: eirini-secret-smuggler
  namespace: {{ .Release.Namespace }}
---
# Role to create secrets in opi namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-smuggler-role
  namespace: {{ .Values.opi.namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - patch
  - create
---
# Binding to get scf secrets
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-smuggler-rolebinding
  namespace: {{ .Values.opi.namespace }}
roleRef:
  kind: Role
  name: secret-smuggler-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: eirini-secret-smuggler
  namespace: {{ .Release.Namespace }}
{{- end }}
