---
apiVersion: v1
kind: Service
metadata:
  name: "eirini-opi"
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 8085
      protocol: TCP
      name: https
  selector:
    name: "eirini"
