---
{{- if eq (printf "%s" .Values.kube.auth) "rbac" }}
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  name: "secret-generator"
{{- end }}
---
{{- if eq (printf "%s" .Values.kube.auth) "rbac" }}
apiVersion: "rbac.authorization.k8s.io/v1beta1"
kind: "RoleBinding"
metadata:
  name: "secret-generator-configgin-role-binding"
subjects:
- kind: "ServiceAccount"
  name: "secret-generator"
roleRef:
  kind: "Role"
  name: "configgin-role"
  apiGroup: "rbac.authorization.k8s.io"
{{- end }}
---
{{- if eq (printf "%s" .Values.kube.auth) "rbac" }}
apiVersion: "rbac.authorization.k8s.io/v1beta1"
kind: "RoleBinding"
metadata:
  name: "secret-generator-secrets-role-binding"
subjects:
- kind: "ServiceAccount"
  name: "secret-generator"
roleRef:
  kind: "Role"
  name: "secrets-role"
  apiGroup: "rbac.authorization.k8s.io"
{{- end }}
