---
{{- if eq (printf "%s" .Values.kube.auth) "rbac" }}
apiVersion: "rbac.authorization.k8s.io/v1beta1"
kind: "Role"
metadata:
  name: "test-role"
rules:
- apiGroups:
  - ""
  resources:
  - "services"
  verbs:
  - "create"
  - "get"
  - "delete"
- apiGroups:
  - "apps"
  resources:
  - "statefulsets"
  verbs:
  - "create"
  - "get"
  - "update"
  - "delete"
- apiGroups:
  - ""
  resources:
  - "pods/exec"
  verbs:
  - "create"
  - "delete"
- apiGroups:
  - ""
  resources:
  - "pods/log"
  verbs:
  - "create"
  - "delete"
  - "get"
  - "list"
{{- end }}
