---
# The cf-usb role contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# - route_registrar: Used for registering routes
#
# Also: cf-usb

{{- if gt (int .Values.sizing.cf_usb.count) 3 }}
_maxReplicas: {{ fail "cf_usb cannot have more than 3 instances" }}
{{- end }}

{{- if and .Values.sizing.HA (and (ne (int .Values.sizing.cf_usb.count) 1) (lt (int .Values.sizing.cf_usb.count) 2)) }}
_minHAReplicas: {{ fail "cf_usb must have at least 2 instances for HA" }}
{{- end }}

{{- if lt (int .Values.sizing.cf_usb.count) 1 }}
_minReplicas: {{ fail "cf_usb must have at least 1 instances" }}
{{- end }}

apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "cf-usb"
  labels:
    skiff-role-name: "cf-usb"
spec:
  replicas: {{ if and .Values.sizing.HA (eq (int .Values.sizing.cf_usb.count) 1) -}} 2 {{- else -}} {{ .Values.sizing.cf_usb.count }} {{- end }}
  selector:
    matchLabels:
      skiff-role-name: "cf-usb"
  template:
    metadata:
      name: "cf-usb"
      labels:
        skiff-role-name: "cf-usb"
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: "skiff-role-name"
                  operator: "In"
                  values:
                  - "cf-usb"
              topologyKey: "beta.kubernetes.io/os"
            weight: 100
        {{- if .Values.sizing.cf_usb.affinity.nodeAffinity }}
        nodeAffinity: {{ toJson .Values.sizing.cf_usb.affinity.nodeAffinity }}
        {{- end }}
      containers:
      - env:
        - name: "CATS_SUITES"
          value: {{ .Values.env.CATS_SUITES | quote }}

        {{- if not .Values.secrets.CF_USB_BROKER_SERVER_CERT }}
        - name: "CF_USB_BROKER_SERVER_CERT"
          valueFrom:
            secretKeyRef:
              key: "cf-usb-broker-server-cert"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.CF_USB_BROKER_SERVER_CERT }}
        - name: "CF_USB_BROKER_SERVER_CERT"
          valueFrom:
            secretKeyRef:
              key: "cf-usb-broker-server-cert"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.CF_USB_BROKER_SERVER_KEY }}
        - name: "CF_USB_BROKER_SERVER_KEY"
          valueFrom:
            secretKeyRef:
              key: "cf-usb-broker-server-key"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.CF_USB_BROKER_SERVER_KEY }}
        - name: "CF_USB_BROKER_SERVER_KEY"
          valueFrom:
            secretKeyRef:
              key: "cf-usb-broker-server-key"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.CF_USB_PASSWORD }}
        - name: "CF_USB_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "cf-usb-password"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.CF_USB_PASSWORD }}
        - name: "CF_USB_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "cf-usb-password"
              name: "secrets"
        {{- end }}

        - name: "DOMAIN"
          value: {{ required "DOMAIN configuration missing" .Values.env.DOMAIN | quote }}

        {{- if not .Values.secrets.INTERNAL_CA_CERT }}
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.INTERNAL_CA_CERT }}
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.INTERNAL_CA_KEY }}
        - name: "INTERNAL_CA_KEY"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-key"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.INTERNAL_CA_KEY }}
        - name: "INTERNAL_CA_KEY"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-key"
              name: "secrets"
        {{- end }}

        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_SERVICE_DOMAIN_SUFFIX"
          value: {{ .Values.env.KUBE_SERVICE_DOMAIN_SUFFIX | quote }}
        - name: "KUBE_SIZING_NATS_COUNT"
          value: {{ .Values.sizing.nats.count | quote }}

        {{- if .Values.secrets.MONIT_PASSWORD }}
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.MONIT_PASSWORD }}
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.MYSQL_CF_USB_PASSWORD }}
        - name: "MYSQL_CF_USB_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "mysql-cf-usb-password"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.MYSQL_CF_USB_PASSWORD }}
        - name: "MYSQL_CF_USB_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "mysql-cf-usb-password"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if not .Values.secrets.NATS_PASSWORD }}
        - name: "NATS_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "nats-password"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.NATS_PASSWORD }}
        - name: "NATS_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "nats-password"
              name: "secrets"
        {{- end }}

        - name: "SCF_LOG_HOST"
          value: {{ .Values.env.SCF_LOG_HOST | quote }}
        - name: "SCF_LOG_PORT"
          value: {{ .Values.env.SCF_LOG_PORT | quote }}
        - name: "SCF_LOG_PROTOCOL"
          value: {{ required "SCF_LOG_PROTOCOL configuration missing" .Values.env.SCF_LOG_PROTOCOL | quote }}
        - name: "UAA_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "uaa-ca-cert"
              name: "secrets"

        {{- if not .Values.secrets.UAA_CLIENTS_CF_USB_SECRET }}
        - name: "UAA_CLIENTS_CF_USB_SECRET"
          valueFrom:
            secretKeyRef:
              key: "uaa-clients-cf-usb-secret"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.UAA_CLIENTS_CF_USB_SECRET }}
        - name: "UAA_CLIENTS_CF_USB_SECRET"
          valueFrom:
            secretKeyRef:
              key: "uaa-clients-cf-usb-secret"
              name: "secrets"
        {{- end }}

        - name: "UAA_HOST"
          value: {{ required "UAA_HOST configuration missing" .Values.env.UAA_HOST | quote }}
        - name: "UAA_PORT"
          value: {{ .Values.env.UAA_PORT | quote }}
        image: "{{ .Values.kube.registry.hostname }}/{{ .Values.kube.organization }}/scf-cf-usb:8be601226398532477dd9a1b29d5b29de5ebb564"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "cf-usb"
        ports:
        - containerPort: 24054
          name: "usb"
          protocol: "TCP"
        - containerPort: 24053
          name: "usb2"
          protocol: "TCP"
        readinessProbe:
          tcpSocket:
            port: 24054
        resources:
          requests:
            {{- if and .Values.sizing.memory.requests .Values.sizing.cf_usb.memory.request }}
            memory: "{{ int .Values.sizing.cf_usb.memory.request }}Mi"
            {{- end }}

            {{- if and .Values.sizing.cpu.requests .Values.sizing.cf_usb.cpu.request }}
            cpu: "{{ int .Values.sizing.cf_usb.cpu.request }}m"
            {{- end }}

          limits:
            {{- if and .Values.sizing.memory.limits .Values.sizing.cf_usb.memory.limit }}
            memory: "{{ int .Values.sizing.cf_usb.memory.limit }}Mi"
            {{- end }}

            {{- if and .Values.sizing.cpu.limits .Values.sizing.cf_usb.cpu.limit }}
            cpu: "{{ int .Values.sizing.cf_usb.cpu.limit }}m"
            {{- end }}

        securityContext:
          {{- if has "ALL" .Values.sizing.cf_usb.capabilities }}
          privileged: true
          {{- end }}

          {{- if not (has "ALL" .Values.sizing.cf_usb.capabilities) }}
          capabilities:
            add:
            {{- range .Values.sizing.cf_usb.capabilities }}
            - {{ . | upper }}
            {{- end }}
          {{- end }}

        volumeMounts: ~
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 600
      volumes: ~
---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "cf-usb"
  spec:
    ports:
    - name: "usb"
      port: 24054
      protocol: "TCP"
      targetPort: "usb"
    - name: "usb2"
      port: 24053
      protocol: "TCP"
      targetPort: "usb2"
    selector:
      skiff-role-name: "cf-usb"
    type: {{ if .Values.services.loadbalanced }} LoadBalancer {{ else }} ClusterIP {{ end }}
kind: "List"
