---
{{- if .Values.enable.cf_usb }}
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "cf-usb-group-set"
    labels:
      app.kubernetes.io/component: "cf-usb-group-set"
      skiff-role-name: "cf-usb-group-set"
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
      app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
      app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" | quote }}
      app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
      helm.sh/chart: {{ printf "%s-%s" .Chart.Name (.Chart.Version | replace "+" "_") | quote }}
      {{- if .Values.config.use_istio }}
      app: "cf-usb-group-set"
      {{- end }}
  spec:
    clusterIP: "None"
    ports:
    - name: "usb"
      port: 24054
      protocol: "TCP"
      targetPort: 0
    - name: "usb2"
      port: 24053
      protocol: "TCP"
      targetPort: 0
    selector:
      app.kubernetes.io/component: "cf-usb-group"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "cf-usb-set"
    labels:
      app.kubernetes.io/component: "cf-usb-set"
      skiff-role-name: "cf-usb-set"
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
      app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
      app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" | quote }}
      app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
      helm.sh/chart: {{ printf "%s-%s" .Chart.Name (.Chart.Version | replace "+" "_") | quote }}
      {{- if .Values.config.use_istio }}
      app: "cf-usb-set"
      {{- end }}
  spec:
    clusterIP: "None"
    ports:
    - name: "usb"
      port: 24054
      protocol: "TCP"
      targetPort: 0
    - name: "usb2"
      port: 24053
      protocol: "TCP"
      targetPort: 0
    selector:
      app.kubernetes.io/component: "cf-usb-group"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "cf-usb"
    labels:
      app.kubernetes.io/component: "cf-usb"
      skiff-role-name: "cf-usb"
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
      app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
      app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" | quote }}
      app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
      helm.sh/chart: {{ printf "%s-%s" .Chart.Name (.Chart.Version | replace "+" "_") | quote }}
      {{- if .Values.config.use_istio }}
      app: "cf-usb"
      {{- end }}
  spec:
    ports:
    - name: "usb"
      port: 24054
      protocol: "TCP"
      targetPort: 24054
    - name: "usb2"
      port: 24053
      protocol: "TCP"
      targetPort: 24053
    selector:
      app.kubernetes.io/component: "cf-usb-group"
kind: "List"
{{- end }}
---
# The cf-usb-group instance group contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# - route_registrar: Used for registering routes
#
# Also: cf-usb and bpm
{{- if .Values.enable.cf_usb }}

{{- if and (ne (typeOf .Values.sizing.cf_usb_group.count) "<nil>") (gt (int .Values.sizing.cf_usb_group.count) 3) }}
_maxReplicas: {{ fail "cf_usb_group cannot have more than 3 instances" }}
{{- end }}

{{- if and .Values.config.HA .Values.config.HA_strict (ne (typeOf .Values.sizing.cf_usb_group.count) "<nil>") (lt (int .Values.sizing.cf_usb_group.count) 2) }}
_minHAReplicas: {{ fail "cf_usb_group must have at least 2 instances for HA" }}
{{- end }}

{{- if and (ne (typeOf .Values.sizing.cf_usb_group.count) "<nil>") (lt (int .Values.sizing.cf_usb_group.count) 1) }}
_minReplicas: {{ fail "cf_usb_group must have at least 1 instances" }}
{{- end }}

{{- if .Values.sizing.HA }}
_moved_sizing_HA: {{ fail "Bad use of moved variable sizing.HA. The new name to use is config.HA" }}
{{- end }}

{{- if .Values.sizing.cpu }}
_moved_sizing_cpu_limits: {{ if .Values.sizing.cpu.limits }} {{ fail "Bad use of moved variable sizing.cpu.limits. The new name to use is config.cpu.limits" }} {{else}} ok {{end}}
{{- end }}

{{- if .Values.sizing.cpu }}
_moved_sizing_cpu_requests: {{ if .Values.sizing.cpu.requests }} {{ fail "Bad use of moved variable sizing.cpu.requests. The new name to use is config.cpu.requests" }} {{else}} ok {{end}}
{{- end }}

{{- if .Values.sizing.memory }}
_moved_sizing_memory_limits: {{ if .Values.sizing.memory.limits }} {{ fail "Bad use of moved variable sizing.memory.limits. The new name to use is config.memory.limits" }} {{else}} ok {{end}}
{{- end }}

{{- if .Values.sizing.memory }}
_moved_sizing_memory_requests: {{ if .Values.sizing.memory.requests }} {{ fail "Bad use of moved variable sizing.memory.requests. The new name to use is config.memory.requests" }} {{else}} ok {{end}}
{{- end }}

apiVersion: {{ if (.Capabilities.APIVersions.Has "apps/v1") }}apps/v1{{ else }}apps/v1beta1{{ end }}
kind: "StatefulSet"
metadata:
  name: "cf-usb-group"
  labels:
    app.kubernetes.io/component: "cf-usb-group"
    skiff-role-name: "cf-usb-group"
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" | quote }}
    app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name (.Chart.Version | replace "+" "_") | quote }}

    {{- if .Values.config.use_istio }}
    app: "cf-usb-group"
    {{- end }}

    {{- if .Values.config.use_istio }}
    version: {{ default .Chart.Version .Chart.AppVersion | quote }}
    {{- end }}

spec:
  podManagementPolicy: "OrderedReady"
  replicas: {{ if (ne (typeOf .Values.sizing.cf_usb_group.count) "<nil>") }}{{ .Values.sizing.cf_usb_group.count }}{{ else }}{{ if .Values.config.HA }}{{ 2 }}{{ else }}{{ 1 }}{{ end }}{{ end }}
  selector:
    matchLabels:
      skiff-role-name: "cf-usb-group"
  serviceName: "cf-usb-group-set"
  template:
    metadata:
      name: "cf-usb-group"
      labels:
        app.kubernetes.io/component: "cf-usb-group"
        skiff-role-name: "cf-usb-group"
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" | quote }}
        app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
        helm.sh/chart: {{ printf "%s-%s" .Chart.Name (.Chart.Version | replace "+" "_") | quote }}

        {{- if .Values.config.use_istio }}
        app: "cf-usb-group"
        {{- end }}

        {{- if .Values.config.use_istio }}
        version: {{ default .Chart.Version .Chart.AppVersion | quote }}
        {{- end }}

      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- if .Values.config.use_istio }}
        sidecar.istio.io/inject: "false"
        {{- end }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: "app.kubernetes.io/component"
                  operator: "In"
                  values:
                  - "cf-usb-group"
              topologyKey: {{if eq (typeOf .Values.kube.podAntiAffinityTopologyKey) "<nil>"}}kubernetes.io/hostname{{else}}{{.Values.kube.podAntiAffinityTopologyKey}}{{end}}
            weight: 100
        {{- if .Values.sizing.cf_usb_group.affinity.nodeAffinity }}
        nodeAffinity: {{ toJson .Values.sizing.cf_usb_group.affinity.nodeAffinity }}
        {{- end }}
      containers:
      {{- if .Values.enable.cf_usb }}
      - env:
        - name: "AZ_LABEL_NAME"
          value: {{if ne (typeOf .Values.env.AZ_LABEL_NAME) "<nil>"}}{{if has (kindOf .Values.env.AZ_LABEL_NAME) (list "map" "slice")}}{{.Values.env.AZ_LABEL_NAME | toJson | quote}}{{else}}{{.Values.env.AZ_LABEL_NAME | quote}}{{end}}{{else}}""{{end}}
        - name: "CATS_SUITES"
          value: {{if ne (typeOf .Values.env.CATS_SUITES) "<nil>"}}{{if has (kindOf .Values.env.CATS_SUITES) (list "map" "slice")}}{{.Values.env.CATS_SUITES | toJson | quote}}{{else}}{{.Values.env.CATS_SUITES | quote}}{{end}}{{else}}""{{end}}

        {{- if not .Values.secrets.CF_USB_BROKER_SERVER_CERT }}
        - name: "CF_USB_BROKER_SERVER_CERT"
          valueFrom:
            secretKeyRef:
              key: "cf-usb-broker-server-cert"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.CF_USB_BROKER_SERVER_CERT }}
        - name: "CF_USB_BROKER_SERVER_CERT"
          valueFrom:
            secretKeyRef:
              key: "cf-usb-broker-server-cert"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.CF_USB_BROKER_SERVER_CERT_KEY }}
        - name: "CF_USB_BROKER_SERVER_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "cf-usb-broker-server-cert-key"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.CF_USB_BROKER_SERVER_CERT_KEY }}
        - name: "CF_USB_BROKER_SERVER_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "cf-usb-broker-server-cert-key"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.CF_USB_PASSWORD }}
        - name: "CF_USB_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "cf-usb-password"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.CF_USB_PASSWORD }}
        - name: "CF_USB_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "cf-usb-password"
              name: "secrets"
        {{- end }}

        - name: "CONFIGGIN_IMPORT_ROUTING_API"
          valueFrom:
            secretKeyRef:
              name: "routing-api"
              key: {{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}
        - name: "CONFIGGIN_SA_TOKEN"
          valueFrom:
            secretKeyRef:
              name: "configgin"
              key: "token"
        - name: "CONFIGGIN_VERSION_TAG"
          value: {{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}
        - name: "DB_EXTERNAL_HOST"
          value: {{if ne (typeOf .Values.env.DB_EXTERNAL_HOST) "<nil>"}}{{if has (kindOf .Values.env.DB_EXTERNAL_HOST) (list "map" "slice")}}{{.Values.env.DB_EXTERNAL_HOST | toJson | quote}}{{else}}{{.Values.env.DB_EXTERNAL_HOST | quote}}{{end}}{{else}}""{{end}}
        - name: "DOMAIN"
          value: {{if ne (typeOf .Values.env.DOMAIN) "<nil>"}}{{if has (kindOf .Values.env.DOMAIN) (list "map" "slice")}}{{.Values.env.DOMAIN | toJson | quote}}{{else}}{{.Values.env.DOMAIN | quote}}{{end}}{{else}}{{fail "env.DOMAIN has not been set"}}{{end}}
        - name: "GARDEN_ROOTFS_DRIVER"
          value: {{if ne (typeOf .Values.env.GARDEN_ROOTFS_DRIVER) "<nil>"}}{{if has (kindOf .Values.env.GARDEN_ROOTFS_DRIVER) (list "map" "slice")}}{{.Values.env.GARDEN_ROOTFS_DRIVER | toJson | quote}}{{else}}{{.Values.env.GARDEN_ROOTFS_DRIVER | quote}}{{end}}{{else}}{{fail "env.GARDEN_ROOTFS_DRIVER has not been set"}}{{end}}

        {{- if .Values.secrets.INTERNAL_CA_CERT }}
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.INTERNAL_CA_CERT }}
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        - name: "KUBERNETES_CLUSTER_DOMAIN"
          value: {{if ne (typeOf .Values.env.KUBERNETES_CLUSTER_DOMAIN) "<nil>"}}{{if has (kindOf .Values.env.KUBERNETES_CLUSTER_DOMAIN) (list "map" "slice")}}{{.Values.env.KUBERNETES_CLUSTER_DOMAIN | toJson | quote}}{{else}}{{.Values.env.KUBERNETES_CLUSTER_DOMAIN | quote}}{{end}}{{else}}""{{end}}
        - name: "KUBERNETES_CONTAINER_NAME"
          value: "cf-usb-group"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"

        {{- if not .Values.secrets.MONIT_PASSWORD }}
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.MONIT_PASSWORD }}
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        {{- end }}

        {{- if .Values.secrets.MYSQL_CF_USB_PASSWORD }}
        - name: "MYSQL_CF_USB_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "mysql-cf-usb-password"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.MYSQL_CF_USB_PASSWORD }}
        - name: "MYSQL_CF_USB_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "mysql-cf-usb-password"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.NATS_PASSWORD }}
        - name: "NATS_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "nats-password"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.NATS_PASSWORD }}
        - name: "NATS_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "nats-password"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        - name: "PZ_LABEL_NAME"
          value: {{if ne (typeOf .Values.env.PZ_LABEL_NAME) "<nil>"}}{{if has (kindOf .Values.env.PZ_LABEL_NAME) (list "map" "slice")}}{{.Values.env.PZ_LABEL_NAME | toJson | quote}}{{else}}{{.Values.env.PZ_LABEL_NAME | quote}}{{end}}{{else}}""{{end}}
        - name: "SCF_LOG_HOST"
          value: {{if ne (typeOf .Values.env.SCF_LOG_HOST) "<nil>"}}{{if has (kindOf .Values.env.SCF_LOG_HOST) (list "map" "slice")}}{{.Values.env.SCF_LOG_HOST | toJson | quote}}{{else}}{{.Values.env.SCF_LOG_HOST | quote}}{{end}}{{else}}""{{end}}
        - name: "SCF_LOG_PORT"
          value: {{if ne (typeOf .Values.env.SCF_LOG_PORT) "<nil>"}}{{if has (kindOf .Values.env.SCF_LOG_PORT) (list "map" "slice")}}{{.Values.env.SCF_LOG_PORT | toJson | quote}}{{else}}{{.Values.env.SCF_LOG_PORT | quote}}{{end}}{{else}}""{{end}}
        - name: "SCF_LOG_PROTOCOL"
          value: {{if ne (typeOf .Values.env.SCF_LOG_PROTOCOL) "<nil>"}}{{if has (kindOf .Values.env.SCF_LOG_PROTOCOL) (list "map" "slice")}}{{.Values.env.SCF_LOG_PROTOCOL | toJson | quote}}{{else}}{{.Values.env.SCF_LOG_PROTOCOL | quote}}{{end}}{{else}}{{fail "env.SCF_LOG_PROTOCOL has not been set"}}{{end}}
        - name: "UAA_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "uaa-ca-cert"
              name: "secrets"

        {{- if .Values.secrets.UAA_CLIENTS_CF_USB_SECRET }}
        - name: "UAA_CLIENTS_CF_USB_SECRET"
          valueFrom:
            secretKeyRef:
              key: "uaa-clients-cf-usb-secret"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.UAA_CLIENTS_CF_USB_SECRET }}
        - name: "UAA_CLIENTS_CF_USB_SECRET"
          valueFrom:
            secretKeyRef:
              key: "uaa-clients-cf-usb-secret"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        - name: "UAA_HOST"
          value: {{if ne (typeOf .Values.env.UAA_HOST) "<nil>"}}{{if has (kindOf .Values.env.UAA_HOST) (list "map" "slice")}}{{.Values.env.UAA_HOST | toJson | quote}}{{else}}{{.Values.env.UAA_HOST | quote}}{{end}}{{else}}{{fail "env.UAA_HOST has not been set"}}{{end}}
        - name: "UAA_PORT"
          value: {{if ne (typeOf .Values.env.UAA_PORT) "<nil>"}}{{if has (kindOf .Values.env.UAA_PORT) (list "map" "slice")}}{{.Values.env.UAA_PORT | toJson | quote}}{{else}}{{.Values.env.UAA_PORT | quote}}{{end}}{{else}}""{{end}}
        - name: "VCAP_HARD_NPROC"
          value: {{ .Values.kube.limits.nproc.hard | quote }}
        - name: "VCAP_SOFT_NPROC"
          value: {{ .Values.kube.limits.nproc.soft | quote }}
        image: "{{ .Values.kube.registry.hostname }}/{{ .Values.kube.organization }}/scf-cf-usb-group:43fd573f368c9298867830eae61503182198005d"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "cf-usb-group"
        ports:
        - containerPort: 24054
          name: "usb"
          protocol: "TCP"
        - containerPort: 24053
          name: "usb2"
          protocol: "TCP"
        readinessProbe:
          exec:
            command:
            - "/opt/fissile/readiness-probe.sh"
        resources:
          requests:
            {{- if and .Values.config.memory.requests .Values.sizing.cf_usb_group.memory.request }}
            memory: "{{ int .Values.sizing.cf_usb_group.memory.request }}Mi"
            {{- end }}

            {{- if and .Values.config.cpu.requests .Values.sizing.cf_usb_group.cpu.request }}
            cpu: "{{ int .Values.sizing.cf_usb_group.cpu.request }}m"
            {{- end }}

          limits:
            {{- if and .Values.config.memory.limits .Values.sizing.cf_usb_group.memory.limit }}
            memory: "{{ int .Values.sizing.cf_usb_group.memory.limit }}Mi"
            {{- end }}

            {{- if and .Values.config.cpu.limits .Values.sizing.cf_usb_group.cpu.limit }}
            cpu: "{{ int .Values.sizing.cf_usb_group.cpu.limit }}m"
            {{- end }}

        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
        volumeMounts:
        - mountPath: "/opt/fissile/config"
          name: "deployment-manifest"
          readOnly: true
      {{- end }}
      dnsPolicy: "ClusterFirst"

      {{- if ne .Values.kube.registry.username "" }}
      imagePullSecrets:
      - name: "registry-credentials"
      {{- end }}

      restartPolicy: "Always"

      {{- if and (eq (printf "%s" .Values.kube.auth) "rbac") (.Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1") }}
      serviceAccountName: "default"
      {{- end }}

      terminationGracePeriodSeconds: 600
      volumes:
      - name: "deployment-manifest"
        secret:
          secretName: "deployment-manifest"
          items:
          - key: "deployment-manifest"
            path: "deployment-manifest.yml"
  {{- if or (gt (int .Capabilities.KubeVersion.Major) 1) (and (eq (int .Capabilities.KubeVersion.Major) 1) (ge (.Capabilities.KubeVersion.Minor | trimSuffix "+" | int) 7)) }}
  updateStrategy:
    type: "RollingUpdate"
  {{- end }}
{{- end }}
