---
# The consul role contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure HCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# Also: consul_agent, metron_agent

{{- if gt (int .Values.sizing.consul.count) 3 }}
_maxReplicas: {{ fail "consul cannot have more than 3 instances" }}
{{- end }}

{{- if and .Values.sizing.HA (and (ne (int .Values.sizing.consul.count) 1) (lt (int .Values.sizing.consul.count) 3)) }}
_minHAReplicas: {{ fail "consul must have at least 3 instances for HA" }}
{{- end }}

{{- if lt (int .Values.sizing.consul.count) 1 }}
_minReplicas: {{ fail "consul must have at least 1 instances" }}
{{- end }}

{{- if eq (mod (int .Values.sizing.consul.count) 2) 0 }}
_oddReplicas: {{ fail "consul must have an odd instance count" }}
{{- end }}

apiVersion: "apps/v1beta1"
kind: "StatefulSet"
metadata:
  name: "consul"
  labels:
    skiff-role-name: "consul"
spec:
  replicas: {{ if and .Values.sizing.HA (eq (int .Values.sizing.consul.count) 1) -}} 3 {{- else -}} {{ .Values.sizing.consul.count }} {{- end }}
  serviceName: "consul-set"
  template:
    metadata:
      annotations:
        {{- if not (or (gt (int .Capabilities.KubeVersion.Major) 1) (and (eq (int .Capabilities.KubeVersion.Major) 1) (ge (int .Capabilities.KubeVersion.Minor) 6))) }}
        scheduler.alpha.kubernetes.io/affinity: "{\"podAntiAffinity\":{\"preferredDuringSchedulingIgnoredDuringExecution\":[{\"podAffinityTerm\":{\"labelSelector\":{\"matchExpressions\":[{\"key\":\"skiff-role-name\",\"operator\":\"In\",\"values\":[\"consul\"]}]},\"topologyKey\":\"beta.kubernetes.io/os\"},\"weight\":100}]}}"
        {{- end }}
      labels:
        skiff-role-name: "consul"
      name: "consul"
    spec:
      {{- if or (gt (int .Capabilities.KubeVersion.Major) 1) (and (eq (int .Capabilities.KubeVersion.Major) 1) (ge (int .Capabilities.KubeVersion.Minor) 6)) }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: "skiff-role-name"
                  operator: "In"
                  values:
                  - "consul"
              topologyKey: "beta.kubernetes.io/os"
            weight: 100
      {{- end }}
      containers:
      - env:
        - name: "CATS_SUITES"
          value: {{ .Values.env.CATS_SUITES | quote }}
        - name: "CONSUL_AGENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "consul-agent-cert"
              name: "secret"
        - name: "CONSUL_AGENT_KEY"
          valueFrom:
            secretKeyRef:
              key: "consul-agent-key"
              name: "secret"
        - name: "CONSUL_ENCRYPTION_KEYS"
          valueFrom:
            secretKeyRef:
              key: "consul-encryption-keys"
              name: "secret"
        - name: "CONSUL_SERVER_CERT"
          valueFrom:
            secretKeyRef:
              key: "consul-server-cert"
              name: "secret"
        - name: "CONSUL_SERVER_KEY"
          valueFrom:
            secretKeyRef:
              key: "consul-server-key"
              name: "secret"
        - name: "HCF_LOG_HOST"
          value: {{ .Values.env.HCF_LOG_HOST | quote }}
        - name: "HCF_LOG_PORT"
          value: {{ .Values.env.HCF_LOG_PORT | quote }}
        - name: "HCF_LOG_PROTOCOL"
          value: {{ required "HCF_LOG_PROTOCOL configuration missing" .Values.env.HCF_LOG_PROTOCOL | quote }}
        - name: "HCP_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "hcp-ca-cert"
              name: "secret"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secret"
        - name: "INTERNAL_CA_KEY"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-key"
              name: "secret"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_SERVICE_DOMAIN_SUFFIX"
          value: {{ .Values.env.KUBE_SERVICE_DOMAIN_SUFFIX | quote }}
        - name: "KUBE_SIZING_CONSUL_COUNT"
          value: {{ .Values.sizing.consul.count | quote }}
        - name: "LOG_LEVEL"
          value: {{ required "LOG_LEVEL configuration missing" .Values.env.LOG_LEVEL | quote }}
        - name: "METRON_CERT"
          valueFrom:
            secretKeyRef:
              key: "metron-cert"
              name: "secret"
        - name: "METRON_KEY"
          valueFrom:
            secretKeyRef:
              key: "metron-key"
              name: "secret"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secret"
        image: "{{ .Values.kube.registry.hostname }}/{{ .Values.kube.organization }}/scf-consul:3e9d2c31017acdc9f0496bc402f05f235c4e66b2"
        livenessProbe: ~
        name: "consul"
        ports:
        - containerPort: 8300
          name: "server-rpc"
          protocol: "TCP"
        - containerPort: 8301
          name: "serf-lan-tcp"
          protocol: "TCP"
        - containerPort: 8301
          name: "serf-lan-udp"
          protocol: "UDP"
        - containerPort: 8302
          name: "serf-wan-tcp"
          protocol: "TCP"
        - containerPort: 8302
          name: "serf-wan-udp"
          protocol: "UDP"
        - containerPort: 8400
          name: "cli-rpc"
          protocol: "TCP"
        - containerPort: 8500
          name: "http-api"
          protocol: "TCP"
        readinessProbe:
          tcpSocket:
            port: 8300
        resources: ~
        securityContext: ~
        volumeMounts:
        - mountPath: "/var/vcap/store"
          name: "consul-data"
          readOnly: false
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
  {{- if or (gt (int .Capabilities.KubeVersion.Major) 1) (and (eq (int .Capabilities.KubeVersion.Major) 1) (ge (int .Capabilities.KubeVersion.Minor) 7)) }}
  updateStrategy:
    type: "RollingUpdate"
  {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: "consul-data"
      annotations:
        volume.beta.kubernetes.io/storage-class: {{ .Values.kube.storage_class.persistent | quote }}
    spec:
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: "{{ .Values.sizing.consul.disk_sizes.consul_data }}G"
---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "consul-set"
  spec:
    {{- if not .Values.services.loadbalanced }}
    clusterIP: "None"
    {{- end }}
    ports:
    - name: "server-rpc"
      port: 8300
      protocol: "TCP"
      targetPort: 0
    - name: "serf-lan-tcp"
      port: 8301
      protocol: "TCP"
      targetPort: 0
    - name: "serf-lan-udp"
      port: 8301
      protocol: "UDP"
      targetPort: 0
    - name: "serf-wan-tcp"
      port: 8302
      protocol: "TCP"
      targetPort: 0
    - name: "serf-wan-udp"
      port: 8302
      protocol: "UDP"
      targetPort: 0
    - name: "cli-rpc"
      port: 8400
      protocol: "TCP"
      targetPort: 0
    - name: "http-api"
      port: 8500
      protocol: "TCP"
      targetPort: 0
    selector:
      skiff-role-name: "consul"
    type: {{ if .Values.services.loadbalanced }} LoadBalancer {{ else }} ClusterIP {{ end }}
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "consul"
  spec:
    ports:
    - name: "server-rpc"
      port: 8300
      protocol: "TCP"
      targetPort: "server-rpc"
    - name: "serf-lan-tcp"
      port: 8301
      protocol: "TCP"
      targetPort: "serf-lan-tcp"
    - name: "serf-lan-udp"
      port: 8301
      protocol: "UDP"
      targetPort: "serf-lan-udp"
    - name: "serf-wan-tcp"
      port: 8302
      protocol: "TCP"
      targetPort: "serf-wan-tcp"
    - name: "serf-wan-udp"
      port: 8302
      protocol: "UDP"
      targetPort: "serf-wan-udp"
    - name: "cli-rpc"
      port: 8400
      protocol: "TCP"
      targetPort: "cli-rpc"
    - name: "http-api"
      port: 8500
      protocol: "TCP"
      targetPort: "http-api"
    selector:
      skiff-role-name: "consul"
    type: {{ if .Values.services.loadbalanced }} LoadBalancer {{ else }} ClusterIP {{ end }}
kind: "List"
