---
# The consul role contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# Also: consul_agent
{{- if gt (int .Values.sizing.consul.count) 0 }}

{{- if gt (int .Values.sizing.consul.count) 1 }}
_maxReplicas: {{ fail "consul cannot have more than 1 instances" }}
{{- end }}

{{- if eq (mod (int .Values.sizing.consul.count) 2) 0 }}
_oddReplicas: {{ fail "consul must have an odd instance count" }}
{{- end }}

apiVersion: "apps/v1beta1"
kind: "StatefulSet"
metadata:
  name: "consul"
  labels:
    skiff-role-name: "consul"
spec:
  replicas: {{ if and .Values.sizing.HA (eq (int .Values.sizing.consul.count) 0) -}} 1 {{- else -}} {{ .Values.sizing.consul.count }} {{- end }}
  serviceName: "consul-set"
  template:
    metadata:
      name: "consul"
      labels:
        skiff-role-name: "consul"
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
    spec:
      containers:
      - env:
        - name: "CATS_SUITES"
          value: {{ .Values.env.CATS_SUITES | quote }}

        {{- if not .Values.secrets.CONSUL_SERVER_CERT }}
        - name: "CONSUL_SERVER_CERT"
          valueFrom:
            secretKeyRef:
              key: "consul-server-cert"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.CONSUL_SERVER_CERT }}
        - name: "CONSUL_SERVER_CERT"
          valueFrom:
            secretKeyRef:
              key: "consul-server-cert"
              name: "secrets"
        {{- end }}

        - name: "CONSUL_SERVER_ENCRYPT_KEY"
          valueFrom:
            secretKeyRef:
              key: "consul-server-encrypt-key"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"

        {{- if not .Values.secrets.CONSUL_SERVER_KEY }}
        - name: "CONSUL_SERVER_KEY"
          valueFrom:
            secretKeyRef:
              key: "consul-server-key"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.CONSUL_SERVER_KEY }}
        - name: "CONSUL_SERVER_KEY"
          valueFrom:
            secretKeyRef:
              key: "consul-server-key"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.INTERNAL_CA_CERT }}
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.INTERNAL_CA_CERT }}
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        {{- end }}

        {{- if .Values.secrets.INTERNAL_CA_KEY }}
        - name: "INTERNAL_CA_KEY"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-key"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.INTERNAL_CA_KEY }}
        - name: "INTERNAL_CA_KEY"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-key"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_SERVICE_DOMAIN_SUFFIX"
          value: {{ .Values.env.KUBE_SERVICE_DOMAIN_SUFFIX | quote }}

        {{- if not .Values.secrets.MONIT_PASSWORD }}
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.MONIT_PASSWORD }}
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        {{- end }}

        - name: "SCF_LOG_HOST"
          value: {{ .Values.env.SCF_LOG_HOST | quote }}
        - name: "SCF_LOG_PORT"
          value: {{ .Values.env.SCF_LOG_PORT | quote }}
        - name: "SCF_LOG_PROTOCOL"
          value: {{ required "SCF_LOG_PROTOCOL configuration missing" .Values.env.SCF_LOG_PROTOCOL | quote }}
        image: "{{ .Values.kube.registry.hostname }}/{{ .Values.kube.organization }}/scf-consul:a9283c11b954f06b703c7125141fb9ed41f24685"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "consul"
        ports:
        - containerPort: 8300
          name: "consul-server"
          protocol: "TCP"
        - containerPort: 8500
          name: "consul-http"
          protocol: "TCP"
        - containerPort: 8301
          name: "serf-tcp"
          protocol: "TCP"
        - containerPort: 8301
          name: "serf-udp"
          protocol: "UDP"
        readinessProbe:
          tcpSocket:
            port: 8300
        resources:
          requests:
            {{- if and .Values.sizing.memory.requests .Values.sizing.consul.memory.request }}
            memory: "{{ int .Values.sizing.consul.memory.request }}Mi"
            {{- end }}

            {{- if and .Values.sizing.cpu.requests .Values.sizing.consul.cpu.request }}
            cpu: "{{ int .Values.sizing.consul.cpu.request }}m"
            {{- end }}

          limits:
            {{- if and .Values.sizing.memory.limits .Values.sizing.consul.memory.limit }}
            memory: "{{ int .Values.sizing.consul.memory.limit }}Mi"
            {{- end }}

            {{- if and .Values.sizing.cpu.limits .Values.sizing.consul.cpu.limit }}
            cpu: "{{ int .Values.sizing.consul.cpu.limit }}m"
            {{- end }}

        securityContext:
          {{- if has "ALL" .Values.sizing.consul.capabilities }}
          privileged: true
          {{- end }}

          {{- if not (has "ALL" .Values.sizing.consul.capabilities) }}
          capabilities:
            add:
            {{- range .Values.sizing.consul.capabilities }}
            - {{ . | upper }}
            {{- end }}
          {{- end }}

        volumeMounts: ~
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 600
      volumes: ~
  {{- if or (gt (int .Capabilities.KubeVersion.Major) 1) (and (eq (int .Capabilities.KubeVersion.Major) 1) (ge (.Capabilities.KubeVersion.Minor | trimSuffix "+" | int) 7)) }}
  updateStrategy:
    type: "RollingUpdate"
  {{- end }}
{{- end }}
---
{{- if gt (int .Values.sizing.consul.count) 0 }}
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "consul-set"
  spec:
    {{- if not .Values.services.loadbalanced }}
    clusterIP: "None"
    {{- end }}
    ports:
    - name: "consul-server"
      port: 8300
      protocol: "TCP"
      targetPort: 0
    - name: "consul-http"
      port: 8500
      protocol: "TCP"
      targetPort: 0
    - name: "serf-tcp"
      port: 8301
      protocol: "TCP"
      targetPort: 0
    - name: "serf-udp"
      port: 8301
      protocol: "UDP"
      targetPort: 0
    selector:
      skiff-role-name: "consul"
    type: {{ if .Values.services.loadbalanced }} LoadBalancer {{ else }} ClusterIP {{ end }}
kind: "List"
{{- end }}
