---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "deployment-manifest"
  labels:
    app.kubernetes.io/component: "deployment-manifest"
    skiff-role-name: "deployment-manifest"
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" | quote }}
    app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name (.Chart.Version | replace "+" "_") | quote }}
data:
  deployment-manifest: {{ .Values.bosh | toYaml | b64enc }}
type: "Opaque"
