---
# The diego-api role contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# Also: bbs, metron_agent

{{- if gt (int .Values.sizing.diego_api.count) 3 }}
_maxReplicas: {{ fail "diego_api cannot have more than 3 instances" }}
{{- end }}

{{- if and .Values.sizing.HA (and (ne (int .Values.sizing.diego_api.count) 1) (lt (int .Values.sizing.diego_api.count) 3)) }}
_minHAReplicas: {{ fail "diego_api must have at least 3 instances for HA" }}
{{- end }}

{{- if lt (int .Values.sizing.memory.limit_factor) 1 }}
_minLimitFactor: {{ fail "The memory limit factor must be at least 1" }}
{{- end }}

{{- if lt (int .Values.sizing.diego_api.count) 1 }}
_minReplicas: {{ fail "diego_api must have at least 1 instances" }}
{{- end }}

{{- if eq (mod (int .Values.sizing.diego_api.count) 2) 0 }}
_oddReplicas: {{ fail "diego_api must have an odd instance count" }}
{{- end }}

apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "diego-api"
  labels:
    skiff-role-name: "diego-api"
spec:
  replicas: {{ if and .Values.sizing.HA (eq (int .Values.sizing.diego_api.count) 1) -}} 3 {{- else -}} {{ .Values.sizing.diego_api.count }} {{- end }}
  selector:
    matchLabels:
      skiff-role-name: "diego-api"
  template:
    metadata:
      annotations:
        {{- if not (or (gt (int .Capabilities.KubeVersion.Major) 1) (and (eq (int .Capabilities.KubeVersion.Major) 1) (ge (int .Capabilities.KubeVersion.Minor) 6))) }}
        scheduler.alpha.kubernetes.io/affinity: "{\"podAntiAffinity\":{\"preferredDuringSchedulingIgnoredDuringExecution\":[{\"podAffinityTerm\":{\"labelSelector\":{\"matchExpressions\":[{\"key\":\"skiff-role-name\",\"operator\":\"In\",\"values\":[\"diego-api\"]}]},\"topologyKey\":\"beta.kubernetes.io/os\"},\"weight\":100}]}}"
        {{- end }}
      labels:
        skiff-role-name: "diego-api"
      name: "diego-api"
    spec:
      {{- if or (gt (int .Capabilities.KubeVersion.Major) 1) (and (eq (int .Capabilities.KubeVersion.Major) 1) (ge (int .Capabilities.KubeVersion.Minor) 6)) }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: "skiff-role-name"
                  operator: "In"
                  values:
                  - "diego-api"
              topologyKey: "beta.kubernetes.io/os"
            weight: 100
      {{- end }}
      containers:
      - env:
        - name: "BBS_ACTIVE_KEY_PASSPHRASE"
          valueFrom:
            secretKeyRef:
              key: "bbs-active-key-passphrase"
              name: "secret-{{ .Release.Revision }}"
        - name: "BBS_AUCTIONEER_CERT"
          valueFrom:
            secretKeyRef:
              key: "bbs-auctioneer-cert"
              name: "secret-{{ .Release.Revision }}"
        - name: "BBS_AUCTIONEER_KEY"
          valueFrom:
            secretKeyRef:
              key: "bbs-auctioneer-key"
              name: "secret-{{ .Release.Revision }}"
        - name: "BBS_REP_CERT"
          valueFrom:
            secretKeyRef:
              key: "bbs-rep-cert"
              name: "secret-{{ .Release.Revision }}"
        - name: "BBS_REP_KEY"
          valueFrom:
            secretKeyRef:
              key: "bbs-rep-key"
              name: "secret-{{ .Release.Revision }}"
        - name: "BBS_SERVER_CRT"
          valueFrom:
            secretKeyRef:
              key: "bbs-server-crt"
              name: "secret-{{ .Release.Revision }}"
        - name: "BBS_SERVER_KEY"
          valueFrom:
            secretKeyRef:
              key: "bbs-server-key"
              name: "secret-{{ .Release.Revision }}"
        - name: "CATS_SUITES"
          value: {{ .Values.env.CATS_SUITES | quote }}
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secret-{{ .Release.Revision }}"
        - name: "INTERNAL_CA_KEY"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-key"
              name: "secret-{{ .Release.Revision }}"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_AZ"
          value: "z1"
        - name: "KUBE_SERVICE_DOMAIN_SUFFIX"
          value: {{ .Values.env.KUBE_SERVICE_DOMAIN_SUFFIX | quote }}
        - name: "LOG_LEVEL"
          value: {{ required "LOG_LEVEL configuration missing" .Values.env.LOG_LEVEL | quote }}
        - name: "METRON_CERT"
          valueFrom:
            secretKeyRef:
              key: "metron-cert"
              name: "secret-{{ .Release.Revision }}"
        - name: "METRON_KEY"
          valueFrom:
            secretKeyRef:
              key: "metron-key"
              name: "secret-{{ .Release.Revision }}"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secret-{{ .Release.Revision }}"
        - name: "MYSQL_DIEGO_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "mysql-diego-password"
              name: "secret-{{ .Release.Revision }}"
        - name: "RELEASE_REVISION"
          value: {{ .Release.Revision | quote }}
        - name: "SCF_LOG_HOST"
          value: {{ .Values.env.SCF_LOG_HOST | quote }}
        - name: "SCF_LOG_PORT"
          value: {{ .Values.env.SCF_LOG_PORT | quote }}
        - name: "SCF_LOG_PROTOCOL"
          value: {{ required "SCF_LOG_PROTOCOL configuration missing" .Values.env.SCF_LOG_PROTOCOL | quote }}
        - name: "UAA_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "uaa-ca-cert"
              name: "secret-{{ .Release.Revision }}"
        image: "{{ .Values.kube.registry.hostname }}/{{ .Values.kube.organization }}/scf-diego-api:71f222173d44e452f09112700a18bd43590bc0d7"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "diego-api"
        ports:
        - containerPort: 8889
          name: "cell-bbs-api"
          protocol: "TCP"
        - containerPort: 17017
          name: "cell-bbs-dbg"
          protocol: "TCP"
        readinessProbe:
          exec:
            command:
            - "/var/vcap/jobs/global-properties/bin/readiness/diego-api"
          failureThreshold: 0
          initialDelaySeconds: 0
          periodSeconds: 0
          successThreshold: 0
          timeoutSeconds: 0
        resources:
          {{- if .Values.sizing.memory.requests }}
          requests:
            memory: "{{ int .Values.sizing.diego_api.memory }}Mi"
          {{- end }}

          {{- if .Values.sizing.memory.limits }}
          limits:
            memory: "{{ (mul (int .Values.sizing.memory.limit_factor) (int .Values.sizing.diego_api.memory)) }}Mi"
          {{- end }}

        securityContext: ~
        volumeMounts: ~
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 600
---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "diego-api"
  spec:
    ports:
    - name: "cell-bbs-api"
      port: 8889
      protocol: "TCP"
      targetPort: "cell-bbs-api"
    - name: "cell-bbs-dbg"
      port: 17017
      protocol: "TCP"
      targetPort: "cell-bbs-dbg"
    selector:
      skiff-role-name: "diego-api"
    type: {{ if .Values.services.loadbalanced }} LoadBalancer {{ else }} ClusterIP {{ end }}
kind: "List"
