---
# The diego-api role contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# - patch-properties: Dummy BOSH job used to host parameters that are used in
#   SCF patches for upstream bugs
#
# Also: bbs, cfdot, metron_agent

{{- if gt (int .Values.sizing.diego_api.count) 3 }}
_maxReplicas: {{ fail "diego_api cannot have more than 3 instances" }}
{{- end }}

{{- if and .Values.sizing.HA (and (ne (int .Values.sizing.diego_api.count) 1) (lt (int .Values.sizing.diego_api.count) 3)) }}
_minHAReplicas: {{ fail "diego_api must have at least 3 instances for HA" }}
{{- end }}

{{- if lt (int .Values.sizing.diego_api.count) 1 }}
_minReplicas: {{ fail "diego_api must have at least 1 instances" }}
{{- end }}

{{- if eq (mod (int .Values.sizing.diego_api.count) 2) 0 }}
_oddReplicas: {{ fail "diego_api must have an odd instance count" }}
{{- end }}

apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "diego-api"
  labels:
    skiff-role-name: "diego-api"
spec:
  replicas: {{ if and .Values.sizing.HA (eq (int .Values.sizing.diego_api.count) 1) -}} 3 {{- else -}} {{ .Values.sizing.diego_api.count }} {{- end }}
  selector:
    matchLabels:
      skiff-role-name: "diego-api"
  template:
    metadata:
      name: "diego-api"
      labels:
        skiff-role-name: "diego-api"
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: "skiff-role-name"
                  operator: "In"
                  values:
                  - "diego-api"
              topologyKey: "beta.kubernetes.io/os"
            weight: 100
        {{- if .Values.sizing.diego_api.affinity.nodeAffinity }}
        nodeAffinity: {{ toJson .Values.sizing.diego_api.affinity.nodeAffinity }}
        {{- end }}
      containers:
      - env:
        - name: "BBS_ACTIVE_KEY_PASSPHRASE"
          valueFrom:
            secretKeyRef:
              key: "bbs-active-key-passphrase"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"

        {{- if not .Values.secrets.BBS_AUCTIONEER_CERT }}
        - name: "BBS_AUCTIONEER_CERT"
          valueFrom:
            secretKeyRef:
              key: "bbs-auctioneer-cert"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.BBS_AUCTIONEER_CERT }}
        - name: "BBS_AUCTIONEER_CERT"
          valueFrom:
            secretKeyRef:
              key: "bbs-auctioneer-cert"
              name: "secrets"
        {{- end }}

        {{- if .Values.secrets.BBS_AUCTIONEER_KEY }}
        - name: "BBS_AUCTIONEER_KEY"
          valueFrom:
            secretKeyRef:
              key: "bbs-auctioneer-key"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.BBS_AUCTIONEER_KEY }}
        - name: "BBS_AUCTIONEER_KEY"
          valueFrom:
            secretKeyRef:
              key: "bbs-auctioneer-key"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.BBS_REP_CERT }}
        - name: "BBS_REP_CERT"
          valueFrom:
            secretKeyRef:
              key: "bbs-rep-cert"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.BBS_REP_CERT }}
        - name: "BBS_REP_CERT"
          valueFrom:
            secretKeyRef:
              key: "bbs-rep-cert"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if not .Values.secrets.BBS_REP_KEY }}
        - name: "BBS_REP_KEY"
          valueFrom:
            secretKeyRef:
              key: "bbs-rep-key"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.BBS_REP_KEY }}
        - name: "BBS_REP_KEY"
          valueFrom:
            secretKeyRef:
              key: "bbs-rep-key"
              name: "secrets"
        {{- end }}

        {{- if .Values.secrets.BBS_SERVER_CRT }}
        - name: "BBS_SERVER_CRT"
          valueFrom:
            secretKeyRef:
              key: "bbs-server-crt"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.BBS_SERVER_CRT }}
        - name: "BBS_SERVER_CRT"
          valueFrom:
            secretKeyRef:
              key: "bbs-server-crt"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if not .Values.secrets.BBS_SERVER_KEY }}
        - name: "BBS_SERVER_KEY"
          valueFrom:
            secretKeyRef:
              key: "bbs-server-key"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.BBS_SERVER_KEY }}
        - name: "BBS_SERVER_KEY"
          valueFrom:
            secretKeyRef:
              key: "bbs-server-key"
              name: "secrets"
        {{- end }}

        - name: "CATS_SUITES"
          value: {{ .Values.env.CATS_SUITES | quote }}

        {{- if not .Values.secrets.INTERNAL_CA_CERT }}
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.INTERNAL_CA_CERT }}
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.INTERNAL_CA_KEY }}
        - name: "INTERNAL_CA_KEY"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-key"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.INTERNAL_CA_KEY }}
        - name: "INTERNAL_CA_KEY"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-key"
              name: "secrets"
        {{- end }}

        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_AZ"
          value: "z1"
        - name: "KUBE_SERVICE_DOMAIN_SUFFIX"
          value: {{ .Values.env.KUBE_SERVICE_DOMAIN_SUFFIX | quote }}

        {{- if .Values.secrets.LOGGREGATOR_CLIENT_CERT }}
        - name: "LOGGREGATOR_CLIENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "loggregator-client-cert"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.LOGGREGATOR_CLIENT_CERT }}
        - name: "LOGGREGATOR_CLIENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "loggregator-client-cert"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.LOGGREGATOR_CLIENT_KEY }}
        - name: "LOGGREGATOR_CLIENT_KEY"
          valueFrom:
            secretKeyRef:
              key: "loggregator-client-key"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.LOGGREGATOR_CLIENT_KEY }}
        - name: "LOGGREGATOR_CLIENT_KEY"
          valueFrom:
            secretKeyRef:
              key: "loggregator-client-key"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        - name: "LOG_LEVEL"
          value: {{ required "LOG_LEVEL configuration missing" .Values.env.LOG_LEVEL | quote }}

        {{- if not .Values.secrets.METRON_CERT }}
        - name: "METRON_CERT"
          valueFrom:
            secretKeyRef:
              key: "metron-cert"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.METRON_CERT }}
        - name: "METRON_CERT"
          valueFrom:
            secretKeyRef:
              key: "metron-cert"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.METRON_KEY }}
        - name: "METRON_KEY"
          valueFrom:
            secretKeyRef:
              key: "metron-key"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.METRON_KEY }}
        - name: "METRON_KEY"
          valueFrom:
            secretKeyRef:
              key: "metron-key"
              name: "secrets"
        {{- end }}

        {{- if .Values.secrets.MONIT_PASSWORD }}
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.MONIT_PASSWORD }}
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.MYSQL_DIEGO_PASSWORD }}
        - name: "MYSQL_DIEGO_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "mysql-diego-password"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.MYSQL_DIEGO_PASSWORD }}
        - name: "MYSQL_DIEGO_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "mysql-diego-password"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        - name: "SCF_LOG_HOST"
          value: {{ .Values.env.SCF_LOG_HOST | quote }}
        - name: "SCF_LOG_PORT"
          value: {{ .Values.env.SCF_LOG_PORT | quote }}
        - name: "SCF_LOG_PROTOCOL"
          value: {{ required "SCF_LOG_PROTOCOL configuration missing" .Values.env.SCF_LOG_PROTOCOL | quote }}
        - name: "UAA_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "uaa-ca-cert"
              name: "secrets"
        image: "{{ .Values.kube.registry.hostname }}/{{ .Values.kube.organization }}/scf-diego-api:551bfe91dfa1cacb6b8c51c15b27e641727c9f7c"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "diego-api"
        ports:
        - containerPort: 8889
          name: "cell-bbs-api"
          protocol: "TCP"
        - containerPort: 17017
          name: "cell-bbs-dbg"
          protocol: "TCP"
        readinessProbe:
          exec:
            command:
            - "/var/vcap/jobs/global-properties/bin/readiness/diego-api"
          failureThreshold: 0
          initialDelaySeconds: 0
          periodSeconds: 0
          successThreshold: 0
          timeoutSeconds: 0
        resources:
          requests:
            {{- if and .Values.sizing.memory.requests .Values.sizing.diego_api.memory.request }}
            memory: "{{ int .Values.sizing.diego_api.memory.request }}Mi"
            {{- end }}

            {{- if and .Values.sizing.cpu.requests .Values.sizing.diego_api.cpu.request }}
            cpu: "{{ int .Values.sizing.diego_api.cpu.request }}m"
            {{- end }}

          limits:
            {{- if and .Values.sizing.memory.limits .Values.sizing.diego_api.memory.limit }}
            memory: "{{ int .Values.sizing.diego_api.memory.limit }}Mi"
            {{- end }}

            {{- if and .Values.sizing.cpu.limits .Values.sizing.diego_api.cpu.limit }}
            cpu: "{{ int .Values.sizing.diego_api.cpu.limit }}m"
            {{- end }}

        securityContext:
          {{- if has "ALL" .Values.sizing.diego_api.capabilities }}
          privileged: true
          {{- end }}

          {{- if not (has "ALL" .Values.sizing.diego_api.capabilities) }}
          capabilities:
            add:
            {{- range .Values.sizing.diego_api.capabilities }}
            - {{ . | upper }}
            {{- end }}
          {{- end }}

        volumeMounts: ~
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 600
      volumes: ~
---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "diego-api"
  spec:
    ports:
    - name: "cell-bbs-api"
      port: 8889
      protocol: "TCP"
      targetPort: "cell-bbs-api"
    - name: "cell-bbs-dbg"
      port: 17017
      protocol: "TCP"
      targetPort: "cell-bbs-dbg"
    selector:
      skiff-role-name: "diego-api"
    type: {{ if .Values.services.loadbalanced }} LoadBalancer {{ else }} ClusterIP {{ end }}
kind: "List"
