---
# The diego-locket role contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# Also: locket, metron_agent

{{- if gt (int .Values.sizing.diego_locket.count) 3 }}
_maxReplicas: {{ fail "diego_locket cannot have more than 3 instances" }}
{{- end }}

{{- if and .Values.sizing.HA (and (ne (int .Values.sizing.diego_locket.count) 1) (lt (int .Values.sizing.diego_locket.count) 3)) }}
_minHAReplicas: {{ fail "diego_locket must have at least 3 instances for HA" }}
{{- end }}

{{- if lt (int .Values.sizing.diego_locket.count) 1 }}
_minReplicas: {{ fail "diego_locket must have at least 1 instances" }}
{{- end }}

apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "diego-locket"
  labels:
    skiff-role-name: "diego-locket"
spec:
  replicas: {{ if and .Values.sizing.HA (eq (int .Values.sizing.diego_locket.count) 1) -}} 3 {{- else -}} {{ .Values.sizing.diego_locket.count }} {{- end }}
  selector:
    matchLabels:
      skiff-role-name: "diego-locket"
  template:
    metadata:
      name: "diego-locket"
      labels:
        skiff-role-name: "diego-locket"
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: "skiff-role-name"
                  operator: "In"
                  values:
                  - "diego-locket"
              topologyKey: "beta.kubernetes.io/os"
            weight: 100
        {{- if .Values.sizing.diego_locket.affinity.nodeAffinity }}
        nodeAffinity: {{ toJson .Values.sizing.diego_locket.affinity.nodeAffinity }}
        {{- end }}
      containers:
      - env:
        - name: "CATS_SUITES"
          value: {{ .Values.env.CATS_SUITES | quote }}

        {{- if not .Values.secrets.DIEGO_CLIENT_CERT }}
        - name: "DIEGO_CLIENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "diego-client-cert"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.DIEGO_CLIENT_CERT }}
        - name: "DIEGO_CLIENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "diego-client-cert"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.DIEGO_CLIENT_KEY }}
        - name: "DIEGO_CLIENT_KEY"
          valueFrom:
            secretKeyRef:
              key: "diego-client-key"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.DIEGO_CLIENT_KEY }}
        - name: "DIEGO_CLIENT_KEY"
          valueFrom:
            secretKeyRef:
              key: "diego-client-key"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.INTERNAL_CA_CERT }}
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.INTERNAL_CA_CERT }}
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.INTERNAL_CA_KEY }}
        - name: "INTERNAL_CA_KEY"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-key"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.INTERNAL_CA_KEY }}
        - name: "INTERNAL_CA_KEY"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-key"
              name: "secrets"
        {{- end }}

        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_AZ"
          value: "z1"
        - name: "KUBE_SERVICE_DOMAIN_SUFFIX"
          value: {{ .Values.env.KUBE_SERVICE_DOMAIN_SUFFIX | quote }}

        {{- if not .Values.secrets.LOGGREGATOR_CLIENT_CERT }}
        - name: "LOGGREGATOR_CLIENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "loggregator-client-cert"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.LOGGREGATOR_CLIENT_CERT }}
        - name: "LOGGREGATOR_CLIENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "loggregator-client-cert"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.LOGGREGATOR_CLIENT_KEY }}
        - name: "LOGGREGATOR_CLIENT_KEY"
          valueFrom:
            secretKeyRef:
              key: "loggregator-client-key"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.LOGGREGATOR_CLIENT_KEY }}
        - name: "LOGGREGATOR_CLIENT_KEY"
          valueFrom:
            secretKeyRef:
              key: "loggregator-client-key"
              name: "secrets"
        {{- end }}

        - name: "LOG_LEVEL"
          value: {{ required "LOG_LEVEL configuration missing" .Values.env.LOG_LEVEL | quote }}

        {{- if not .Values.secrets.METRON_CERT }}
        - name: "METRON_CERT"
          valueFrom:
            secretKeyRef:
              key: "metron-cert"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.METRON_CERT }}
        - name: "METRON_CERT"
          valueFrom:
            secretKeyRef:
              key: "metron-cert"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.METRON_KEY }}
        - name: "METRON_KEY"
          valueFrom:
            secretKeyRef:
              key: "metron-key"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.METRON_KEY }}
        - name: "METRON_KEY"
          valueFrom:
            secretKeyRef:
              key: "metron-key"
              name: "secrets"
        {{- end }}

        {{- if .Values.secrets.MONIT_PASSWORD }}
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.MONIT_PASSWORD }}
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.MYSQL_DIEGO_LOCKET_PASSWORD }}
        - name: "MYSQL_DIEGO_LOCKET_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "mysql-diego-locket-password"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.MYSQL_DIEGO_LOCKET_PASSWORD }}
        - name: "MYSQL_DIEGO_LOCKET_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "mysql-diego-locket-password"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        - name: "SCF_LOG_HOST"
          value: {{ .Values.env.SCF_LOG_HOST | quote }}
        - name: "SCF_LOG_PORT"
          value: {{ .Values.env.SCF_LOG_PORT | quote }}
        - name: "SCF_LOG_PROTOCOL"
          value: {{ required "SCF_LOG_PROTOCOL configuration missing" .Values.env.SCF_LOG_PROTOCOL | quote }}
        - name: "UAA_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "uaa-ca-cert"
              name: "secrets"
        image: "{{ .Values.kube.registry.hostname }}/{{ .Values.kube.organization }}/scf-diego-locket:47ee770cc1157e49b0e647904f54632356540078"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "diego-locket"
        ports:
        - containerPort: 8891
          name: "locket"
          protocol: "TCP"
        readinessProbe:
          tcpSocket:
            port: 8891
        resources:
          requests:
            {{- if and .Values.sizing.memory.requests .Values.sizing.diego_locket.memory.request }}
            memory: "{{ int .Values.sizing.diego_locket.memory.request }}Mi"
            {{- end }}

            {{- if and .Values.sizing.cpu.requests .Values.sizing.diego_locket.cpu.request }}
            cpu: "{{ int .Values.sizing.diego_locket.cpu.request }}m"
            {{- end }}

          limits:
            {{- if and .Values.sizing.memory.limits .Values.sizing.diego_locket.memory.limit }}
            memory: "{{ int .Values.sizing.diego_locket.memory.limit }}Mi"
            {{- end }}

            {{- if and .Values.sizing.cpu.limits .Values.sizing.diego_locket.cpu.limit }}
            cpu: "{{ int .Values.sizing.diego_locket.cpu.limit }}m"
            {{- end }}

        securityContext:
          {{- if has "ALL" .Values.sizing.diego_locket.capabilities }}
          privileged: true
          {{- end }}

          {{- if not (has "ALL" .Values.sizing.diego_locket.capabilities) }}
          capabilities:
            add:
            {{- range .Values.sizing.diego_locket.capabilities }}
            - {{ . | upper }}
            {{- end }}
          {{- end }}

        volumeMounts: ~
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 600
      volumes: ~
---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "diego-locket"
  spec:
    ports:
    - name: "locket"
      port: 8891
      protocol: "TCP"
      targetPort: "locket"
    selector:
      skiff-role-name: "diego-locket"
    type: {{ if .Values.services.loadbalanced }} LoadBalancer {{ else }} ClusterIP {{ end }}
kind: "List"
