---
# The diego-cell role contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# - wait-for-uaa: Wait for UAA to be ready before starting any jobs
#
# Also: rep, route_emitter, garden, cflinuxfs2-rootfs-setup,
# opensuse42-rootfs-setup, cf-sle12-setup, metron_agent, nfsv3driver

{{- if gt (int .Values.sizing.diego_cell.count) 254 }}
_maxReplicas: {{ fail "diego_cell cannot have more than 254 instances" }}
{{- end }}

{{- if and .Values.sizing.HA (and (ne (int .Values.sizing.diego_cell.count) 1) (lt (int .Values.sizing.diego_cell.count) 3)) }}
_minHAReplicas: {{ fail "diego_cell must have at least 3 instances for HA" }}
{{- end }}

{{- if lt (int .Values.sizing.diego_cell.count) 1 }}
_minReplicas: {{ fail "diego_cell must have at least 1 instances" }}
{{- end }}

apiVersion: "apps/v1beta1"
kind: "StatefulSet"
metadata:
  name: "diego-cell"
  labels:
    skiff-role-name: "diego-cell"
spec:
  replicas: {{ if and .Values.sizing.HA (eq (int .Values.sizing.diego_cell.count) 1) -}} 3 {{- else -}} {{ .Values.sizing.diego_cell.count }} {{- end }}
  serviceName: "diego-cell-set"
  template:
    metadata:
      name: "diego-cell"
      labels:
        skiff-role-name: "diego-cell"
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- if not (or (gt (int .Capabilities.KubeVersion.Major) 1) (and (eq (int .Capabilities.KubeVersion.Major) 1) (ge (.Capabilities.KubeVersion.Minor | trimSuffix "+" | int) 6))) }}
        scheduler.alpha.kubernetes.io/affinity: "{\"podAntiAffinity\":{\"preferredDuringSchedulingIgnoredDuringExecution\":[{\"podAffinityTerm\":{\"labelSelector\":{\"matchExpressions\":[{\"key\":\"skiff-role-name\",\"operator\":\"In\",\"values\":[\"diego-cell\"]}]},\"topologyKey\":\"beta.kubernetes.io/os\"},\"weight\":100},{\"podAffinityTerm\":{\"labelSelector\":{\"matchExpressions\":[{\"key\":\"skiff-role-name\",\"operator\":\"In\",\"values\":[\"router\"]}]},\"topologyKey\":\"beta.kubernetes.io/os\"},\"weight\":100}]}}"
        {{- end }}
    spec:
      {{- if or (gt (int .Capabilities.KubeVersion.Major) 1) (and (eq (int .Capabilities.KubeVersion.Major) 1) (ge (.Capabilities.KubeVersion.Minor | trimSuffix "+" | int) 6)) }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: "skiff-role-name"
                  operator: "In"
                  values:
                  - "diego-cell"
              topologyKey: "beta.kubernetes.io/os"
            weight: 100
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: "skiff-role-name"
                  operator: "In"
                  values:
                  - "router"
              topologyKey: "beta.kubernetes.io/os"
            weight: 100
        {{- if .Values.sizing.diego_cell.affinity.nodeAffinity }}
        nodeAffinity: {{ toJson .Values.sizing.diego_cell.affinity.nodeAffinity }}
        {{- end }}
      {{- end }}
      containers:
      - env:
        {{- if not .Values.secrets.BBS_CLIENT_CRT }}
        - name: "BBS_CLIENT_CRT"
          valueFrom:
            secretKeyRef:
              key: "bbs-client-crt"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.BBS_CLIENT_CRT }}
        - name: "BBS_CLIENT_CRT"
          valueFrom:
            secretKeyRef:
              key: "bbs-client-crt"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.BBS_CLIENT_KEY }}
        - name: "BBS_CLIENT_KEY"
          valueFrom:
            secretKeyRef:
              key: "bbs-client-key"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.BBS_CLIENT_KEY }}
        - name: "BBS_CLIENT_KEY"
          valueFrom:
            secretKeyRef:
              key: "bbs-client-key"
              name: "secrets"
        {{- end }}

        - name: "CATS_SUITES"
          value: {{ .Values.env.CATS_SUITES | quote }}
        - name: "DIEGO_CELL_DISK_CAPACITY_MB"
          value: {{ required "DIEGO_CELL_DISK_CAPACITY_MB configuration missing" .Values.env.DIEGO_CELL_DISK_CAPACITY_MB | quote }}
        - name: "DIEGO_CELL_MEMORY_CAPACITY_MB"
          value: {{ required "DIEGO_CELL_MEMORY_CAPACITY_MB configuration missing" .Values.env.DIEGO_CELL_MEMORY_CAPACITY_MB | quote }}
        - name: "DIEGO_CELL_NETWORK_MTU"
          value: {{ required "DIEGO_CELL_NETWORK_MTU configuration missing" .Values.env.DIEGO_CELL_NETWORK_MTU | quote }}
        - name: "DIEGO_CELL_SUBNET"
          value: {{ required "DIEGO_CELL_SUBNET configuration missing" .Values.env.DIEGO_CELL_SUBNET | quote }}

        {{- if not .Values.secrets.DIEGO_CLIENT_CERT }}
        - name: "DIEGO_CLIENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "diego-client-cert"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.DIEGO_CLIENT_CERT }}
        - name: "DIEGO_CLIENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "diego-client-cert"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.DIEGO_CLIENT_KEY }}
        - name: "DIEGO_CLIENT_KEY"
          valueFrom:
            secretKeyRef:
              key: "diego-client-key"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.DIEGO_CLIENT_KEY }}
        - name: "DIEGO_CLIENT_KEY"
          valueFrom:
            secretKeyRef:
              key: "diego-client-key"
              name: "secrets"
        {{- end }}

        - name: "GARDEN_DOCKER_REGISTRY"
          value: {{ required "GARDEN_DOCKER_REGISTRY configuration missing" .Values.env.GARDEN_DOCKER_REGISTRY | quote }}
        - name: "GARDEN_INSECURE_DOCKER_REGISTRIES"
          value: {{ .Values.env.GARDEN_INSECURE_DOCKER_REGISTRIES | quote }}
        - name: "GARDEN_LINUX_DNS_SERVER"
          value: {{ .Values.env.GARDEN_LINUX_DNS_SERVER | quote }}
        - name: "GARDEN_ROOTFS_DRIVER"
          value: {{ required "GARDEN_ROOTFS_DRIVER configuration missing" .Values.env.GARDEN_ROOTFS_DRIVER | quote }}
        - name: "HTTPS_PROXY"
          value: {{ .Values.env.HTTPS_PROXY | quote }}
        - name: "HTTP_PROXY"
          value: {{ .Values.env.HTTP_PROXY | quote }}

        {{- if not .Values.secrets.INTERNAL_CA_CERT }}
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.INTERNAL_CA_CERT }}
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.INTERNAL_CA_KEY }}
        - name: "INTERNAL_CA_KEY"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-key"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.INTERNAL_CA_KEY }}
        - name: "INTERNAL_CA_KEY"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-key"
              name: "secrets"
        {{- end }}

        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_AZ"
          value: "z1"
        - name: "KUBE_SERVICE_DOMAIN_SUFFIX"
          value: {{ .Values.env.KUBE_SERVICE_DOMAIN_SUFFIX | quote }}
        - name: "KUBE_SIZING_NATS_COUNT"
          value: {{ .Values.sizing.nats.count | quote }}
        - name: "LOG_LEVEL"
          value: {{ required "LOG_LEVEL configuration missing" .Values.env.LOG_LEVEL | quote }}

        {{- if not .Values.secrets.METRON_CERT }}
        - name: "METRON_CERT"
          valueFrom:
            secretKeyRef:
              key: "metron-cert"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.METRON_CERT }}
        - name: "METRON_CERT"
          valueFrom:
            secretKeyRef:
              key: "metron-cert"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.METRON_KEY }}
        - name: "METRON_KEY"
          valueFrom:
            secretKeyRef:
              key: "metron-key"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.METRON_KEY }}
        - name: "METRON_KEY"
          valueFrom:
            secretKeyRef:
              key: "metron-key"
              name: "secrets"
        {{- end }}

        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        - name: "NATS_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "nats-password"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        - name: "NO_PROXY"
          value: {{ .Values.env.NO_PROXY | quote }}
        - name: "PERSI_NFS_DRIVER_ALLOWED_IN_MOUNT"
          value: {{ .Values.env.PERSI_NFS_DRIVER_ALLOWED_IN_MOUNT | quote }}
        - name: "PERSI_NFS_DRIVER_ALLOWED_IN_SOURCE"
          value: {{ .Values.env.PERSI_NFS_DRIVER_ALLOWED_IN_SOURCE | quote }}
        - name: "PERSI_NFS_DRIVER_DEFAULT_IN_MOUNT"
          value: {{ .Values.env.PERSI_NFS_DRIVER_DEFAULT_IN_MOUNT | quote }}
        - name: "PERSI_NFS_DRIVER_DEFAULT_IN_SOURCE"
          value: {{ .Values.env.PERSI_NFS_DRIVER_DEFAULT_IN_SOURCE | quote }}
        - name: "PERSI_NFS_DRIVER_DISABLE"
          value: {{ .Values.env.PERSI_NFS_DRIVER_DISABLE | quote }}
        - name: "PERSI_NFS_DRIVER_LDAP_HOST"
          value: {{ .Values.env.PERSI_NFS_DRIVER_LDAP_HOST | quote }}
        - name: "PERSI_NFS_DRIVER_LDAP_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "persi-nfs-driver-ldap-password"
              name: "secrets"
        - name: "PERSI_NFS_DRIVER_LDAP_PORT"
          value: {{ .Values.env.PERSI_NFS_DRIVER_LDAP_PORT | quote }}
        - name: "PERSI_NFS_DRIVER_LDAP_PROTOCOL"
          value: {{ .Values.env.PERSI_NFS_DRIVER_LDAP_PROTOCOL | quote }}
        - name: "PERSI_NFS_DRIVER_LDAP_USER"
          value: {{ .Values.env.PERSI_NFS_DRIVER_LDAP_USER | quote }}
        - name: "PERSI_NFS_DRIVER_LDAP_USER_FQDN"
          value: {{ .Values.env.PERSI_NFS_DRIVER_LDAP_USER_FQDN | quote }}

        {{- if not .Values.secrets.REP_SERVER_CERT }}
        - name: "REP_SERVER_CERT"
          valueFrom:
            secretKeyRef:
              key: "rep-server-cert"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.REP_SERVER_CERT }}
        - name: "REP_SERVER_CERT"
          valueFrom:
            secretKeyRef:
              key: "rep-server-cert"
              name: "secrets"
        {{- end }}

        {{- if .Values.secrets.REP_SERVER_KEY }}
        - name: "REP_SERVER_KEY"
          valueFrom:
            secretKeyRef:
              key: "rep-server-key"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.REP_SERVER_KEY }}
        - name: "REP_SERVER_KEY"
          valueFrom:
            secretKeyRef:
              key: "rep-server-key"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        - name: "ROOTFS_TRUSTED_CERTS"
          value: {{ .Values.env.ROOTFS_TRUSTED_CERTS | quote }}
        - name: "SCF_LOG_HOST"
          value: {{ .Values.env.SCF_LOG_HOST | quote }}
        - name: "SCF_LOG_PORT"
          value: {{ .Values.env.SCF_LOG_PORT | quote }}
        - name: "SCF_LOG_PROTOCOL"
          value: {{ required "SCF_LOG_PROTOCOL configuration missing" .Values.env.SCF_LOG_PROTOCOL | quote }}
        - name: "SUSE_STACK"
          value: "sle12"
        - name: "SUSE_STACK_DIRNAME"
          value: "cf-sle12"
        - name: "TRUSTED_CERTS"
          value: {{ .Values.env.TRUSTED_CERTS | quote }}
        - name: "UAA_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "uaa-ca-cert"
              name: "secrets"
        - name: "UAA_CLIENTS_TCP_EMITTER_SECRET"
          valueFrom:
            secretKeyRef:
              key: "uaa-clients-tcp-emitter-secret"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        - name: "UAA_HOST"
          value: {{ required "UAA_HOST configuration missing" .Values.env.UAA_HOST | quote }}
        - name: "UAA_PORT"
          value: {{ .Values.env.UAA_PORT | quote }}
        image: "{{ .Values.kube.registry.hostname }}/{{ .Values.kube.organization }}/scf-diego-cell:3ea7162adec29c32b5e5f6d51d3c51a3391fdcfe"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "diego-cell"
        ports:
        - containerPort: 1801
          name: "rep-server"
          protocol: "TCP"
        - containerPort: 7589
          name: "nfs-driver"
          protocol: "TCP"
        - containerPort: 7590
          name: "nfs-admin"
          protocol: "TCP"
        readinessProbe:
          failureThreshold: 0
          httpGet:
            path: "/ping"
            port: 1800
            scheme: "HTTP"
          initialDelaySeconds: 0
          periodSeconds: 0
          successThreshold: 0
          timeoutSeconds: 0
        resources:
          requests:
            {{- if and .Values.sizing.memory.requests .Values.sizing.diego_cell.memory.request }}
            memory: "{{ int .Values.sizing.diego_cell.memory.request }}Mi"
            {{- end }}

            {{- if and .Values.sizing.cpu.requests .Values.sizing.diego_cell.cpu.request }}
            cpu: "{{ int .Values.sizing.diego_cell.cpu.request }}m"
            {{- end }}

          limits:
            {{- if and .Values.sizing.memory.limits .Values.sizing.diego_cell.memory.limit }}
            memory: "{{ int .Values.sizing.diego_cell.memory.limit }}Mi"
            {{- end }}

            {{- if and .Values.sizing.cpu.limits .Values.sizing.diego_cell.cpu.limit }}
            cpu: "{{ int .Values.sizing.diego_cell.cpu.limit }}m"
            {{- end }}

        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: "/var/vcap/data/grootfs"
          name: "grootfs-data"
          readOnly: false
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 600
  {{- if or (gt (int .Capabilities.KubeVersion.Major) 1) (and (eq (int .Capabilities.KubeVersion.Major) 1) (ge (.Capabilities.KubeVersion.Minor | trimSuffix "+" | int) 7)) }}
  updateStrategy:
    type: "RollingUpdate"
  {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: "grootfs-data"
      annotations:
        volume.beta.kubernetes.io/storage-class: {{ .Values.kube.storage_class.persistent | quote }}
    spec:
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: "{{ .Values.sizing.diego_cell.disk_sizes.grootfs_data }}G"
---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "diego-cell-set"
  spec:
    {{- if not .Values.services.loadbalanced }}
    clusterIP: "None"
    {{- end }}
    ports:
    - name: "rep-server"
      port: 1801
      protocol: "TCP"
      targetPort: 0
    - name: "nfs-driver"
      port: 7589
      protocol: "TCP"
      targetPort: 0
    - name: "nfs-admin"
      port: 7590
      protocol: "TCP"
      targetPort: 0
    selector:
      skiff-role-name: "diego-cell"
    type: {{ if .Values.services.loadbalanced }} LoadBalancer {{ else }} ClusterIP {{ end }}
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "diego-cell"
  spec:
    ports:
    - name: "rep-server"
      port: 1801
      protocol: "TCP"
      targetPort: "rep-server"
    - name: "nfs-driver"
      port: 7589
      protocol: "TCP"
      targetPort: "nfs-driver"
    - name: "nfs-admin"
      port: 7590
      protocol: "TCP"
      targetPort: "nfs-admin"
    selector:
      skiff-role-name: "diego-cell"
    type: {{ if .Values.services.loadbalanced }} LoadBalancer {{ else }} ClusterIP {{ end }}
kind: "List"
