---
apiVersion: "v1"
data:
  # The password for the cluster administrator.
  cluster-admin-password: {{ required "secrets.CLUSTER_ADMIN_PASSWORD has not been set" .Values.secrets.CLUSTER_ADMIN_PASSWORD | b64enc | quote }}

  # LDAP service account password (required for LDAP integration only)
  persi-nfs-driver-ldap-password: {{ required "secrets.PERSI_NFS_DRIVER_LDAP_PASSWORD has not been set" .Values.secrets.PERSI_NFS_DRIVER_LDAP_PASSWORD | b64enc | quote }}

  # The password of the admin client - a client named admin with uaa.admin as an
  # authority.
  uaa-admin-client-secret: {{ required "secrets.UAA_ADMIN_CLIENT_SECRET has not been set" .Values.secrets.UAA_ADMIN_CLIENT_SECRET | b64enc | quote }}

  # The CA certificate for UAA
  uaa-ca-cert: {{ required "secrets.UAA_CA_CERT has not been set" .Values.secrets.UAA_CA_CERT | b64enc | quote }}

  # PEM encoded RSA private key used to identify host.
  # This value uses a generated default.
  app-ssh-key: {{ default "" .Values.secrets.APP_SSH_KEY | b64enc | quote }}

  # MD5 fingerprint of the host key of the SSH proxy that brokers connections to
  # application instances.
  # This value uses a generated default.
  app-ssh-key-fingerprint: {{ default "" .Values.secrets.APP_SSH_KEY_FINGERPRINT | b64enc | quote }}

  # PEM-encoded certificate
  # This value uses a generated default.
  auctioneer-rep-cert: {{ default "" .Values.secrets.AUCTIONEER_REP_CERT | b64enc | quote }}

  # PEM-encoded key
  # This value uses a generated default.
  auctioneer-rep-key: {{ default "" .Values.secrets.AUCTIONEER_REP_KEY | b64enc | quote }}

  # PEM-encoded server certificate
  # This value uses a generated default.
  auctioneer-server-cert: {{ default "" .Values.secrets.AUCTIONEER_SERVER_CERT | b64enc | quote }}

  # PEM-encoded server key
  # This value uses a generated default.
  auctioneer-server-key: {{ default "" .Values.secrets.AUCTIONEER_SERVER_KEY | b64enc | quote }}

  # PEM-encoded certificate
  # This value uses a generated default.
  bbs-auctioneer-cert: {{ default "" .Values.secrets.BBS_AUCTIONEER_CERT | b64enc | quote }}

  # PEM-encoded key
  # This value uses a generated default.
  bbs-auctioneer-key: {{ default "" .Values.secrets.BBS_AUCTIONEER_KEY | b64enc | quote }}

  # PEM-encoded client certificate.
  # This value uses a generated default.
  bbs-client-crt: {{ default "" .Values.secrets.BBS_CLIENT_CRT | b64enc | quote }}

  # PEM-encoded client key.
  # This value uses a generated default.
  bbs-client-key: {{ default "" .Values.secrets.BBS_CLIENT_KEY | b64enc | quote }}

  # PEM-encoded certificate
  # This value uses a generated default.
  bbs-rep-cert: {{ default "" .Values.secrets.BBS_REP_CERT | b64enc | quote }}

  # PEM-encoded key
  # This value uses a generated default.
  bbs-rep-key: {{ default "" .Values.secrets.BBS_REP_KEY | b64enc | quote }}

  # PEM-encoded client certificate.
  # This value uses a generated default.
  bbs-server-crt: {{ default "" .Values.secrets.BBS_SERVER_CRT | b64enc | quote }}

  # PEM-encoded client key.
  # This value uses a generated default.
  bbs-server-key: {{ default "" .Values.secrets.BBS_SERVER_KEY | b64enc | quote }}

  # The basic auth password that Cloud Controller uses to connect to the
  # blobstore server. Auto-generated if not provided. Passwords must be
  # alphanumeric (URL-safe).
  # This value uses a generated default.
  blobstore-password: {{ default "" .Values.secrets.BLOBSTORE_PASSWORD | b64enc | quote }}

  # The secret used for signing URLs between Cloud Controller and blobstore.
  # This value uses a generated default.
  blobstore-secure-link: {{ default "" .Values.secrets.BLOBSTORE_SECURE_LINK | b64enc | quote }}

  # The PEM-encoded certificate (optionally as a certificate chain) for serving
  # blobs over TLS/SSL.
  # This value uses a generated default.
  blobstore-tls-cert: {{ default "" .Values.secrets.BLOBSTORE_TLS_CERT | b64enc | quote }}

  # The PEM-encoded private key for signing TLS/SSL traffic.
  # This value uses a generated default.
  blobstore-tls-key: {{ default "" .Values.secrets.BLOBSTORE_TLS_KEY | b64enc | quote }}

  # The password for the bulk api.
  # This value uses a generated default.
  bulk-api-password: {{ default "" .Values.secrets.BULK_API_PASSWORD | b64enc | quote }}

  # The PEM-encoded certificate for internal cloud controller traffic.
  # This value uses a generated default.
  cc-server-crt: {{ default "" .Values.secrets.CC_SERVER_CRT | b64enc | quote }}

  # The PEM-encoded private key for internal cloud controller traffic.
  # This value uses a generated default.
  cc-server-key: {{ default "" .Values.secrets.CC_SERVER_KEY | b64enc | quote }}

  # The PEM-encoded certificate for internal cloud controller uploader traffic.
  # This value uses a generated default.
  cc-uploader-crt: {{ default "" .Values.secrets.CC_UPLOADER_CRT | b64enc | quote }}

  # The PEM-encoded private key for internal cloud controller uploader traffic.
  # This value uses a generated default.
  cc-uploader-key: {{ default "" .Values.secrets.CC_UPLOADER_KEY | b64enc | quote }}

  # PEM-encoded broker server certificate.
  # This value uses a generated default.
  cf-usb-broker-server-cert: {{ default "" .Values.secrets.CF_USB_BROKER_SERVER_CERT | b64enc | quote }}

  # PEM-encoded broker server key.
  # This value uses a generated default.
  cf-usb-broker-server-key: {{ default "" .Values.secrets.CF_USB_BROKER_SERVER_KEY | b64enc | quote }}

  # The password for access to the Universal Service Broker.
  # This value uses a generated default.
  cf-usb-password: {{ default "" .Values.secrets.CF_USB_PASSWORD | b64enc | quote }}

  # PEM-encoded consul client certificate
  # This value uses a generated default.
  consul-client-cert: {{ default "" .Values.secrets.CONSUL_CLIENT_CERT | b64enc | quote }}

  # PEM-encoded consul client key
  # This value uses a generated default.
  consul-client-key: {{ default "" .Values.secrets.CONSUL_CLIENT_KEY | b64enc | quote }}

  # PEM-encoded server certificate
  # This value uses a generated default.
  consul-server-cert: {{ default "" .Values.secrets.CONSUL_SERVER_CERT | b64enc | quote }}

  # PEM-encoded server key
  # This value uses a generated default.
  consul-server-key: {{ default "" .Values.secrets.CONSUL_SERVER_KEY | b64enc | quote }}

  # PEM-encoded client certificate
  # This value uses a generated default.
  diego-client-cert: {{ default "" .Values.secrets.DIEGO_CLIENT_CERT | b64enc | quote }}

  # PEM-encoded client key
  # This value uses a generated default.
  diego-client-key: {{ default "" .Values.secrets.DIEGO_CLIENT_KEY | b64enc | quote }}

  # PEM-encoded certificate.
  # This value uses a generated default.
  doppler-cert: {{ default "" .Values.secrets.DOPPLER_CERT | b64enc | quote }}

  # PEM-encoded key.
  # This value uses a generated default.
  doppler-key: {{ default "" .Values.secrets.DOPPLER_KEY | b64enc | quote }}

  # Basic auth password for access to the Cloud Controller's internal API.
  # This value uses a generated default.
  internal-api-password: {{ default "" .Values.secrets.INTERNAL_API_PASSWORD | b64enc | quote }}

  # PEM-encoded CA certificate used to sign the TLS certificate used by all
  # components to secure their communications.
  # This value uses a generated default.
  internal-ca-cert: {{ default "" .Values.secrets.INTERNAL_CA_CERT | b64enc | quote }}

  # PEM-encoded CA key.
  # This value uses a generated default.
  internal-ca-key: {{ default "" .Values.secrets.INTERNAL_CA_KEY | b64enc | quote }}

  # PEM-encoded client certificate for loggregator mutual authentication
  # This value uses a generated default.
  loggregator-client-cert: {{ default "" .Values.secrets.LOGGREGATOR_CLIENT_CERT | b64enc | quote }}

  # PEM-encoded client key for loggregator mutual authentication
  # This value uses a generated default.
  loggregator-client-key: {{ default "" .Values.secrets.LOGGREGATOR_CLIENT_KEY | b64enc | quote }}

  # PEM-encoded certificate.
  # This value uses a generated default.
  metron-cert: {{ default "" .Values.secrets.METRON_CERT | b64enc | quote }}

  # PEM-encoded key.
  # This value uses a generated default.
  metron-key: {{ default "" .Values.secrets.METRON_KEY | b64enc | quote }}

  # Password used for the monit API.
  # This value uses a generated default.
  monit-password: {{ default "" .Values.secrets.MONIT_PASSWORD | b64enc | quote }}

  # The password for the MySQL server admin user.
  # This value uses a generated default.
  mysql-admin-password: {{ default "" .Values.secrets.MYSQL_ADMIN_PASSWORD | b64enc | quote }}

  # The password for access to the Cloud Controller database.
  # This value uses a generated default.
  mysql-ccdb-role-password: {{ default "" .Values.secrets.MYSQL_CCDB_ROLE_PASSWORD | b64enc | quote }}

  # The password for access to the usb config database.
  # This value uses a generated default.
  mysql-cf-usb-password: {{ default "" .Values.secrets.MYSQL_CF_USB_PASSWORD | b64enc | quote }}

  # The password for the cluster logger health user.
  # This value uses a generated default.
  mysql-cluster-health-password: {{ default "" .Values.secrets.MYSQL_CLUSTER_HEALTH_PASSWORD | b64enc | quote }}

  # Database password for the diego locket service.
  # This value uses a generated default.
  mysql-diego-locket-password: {{ default "" .Values.secrets.MYSQL_DIEGO_LOCKET_PASSWORD | b64enc | quote }}

  # The password for access to MySQL by diego.
  # This value uses a generated default.
  mysql-diego-password: {{ default "" .Values.secrets.MYSQL_DIEGO_PASSWORD | b64enc | quote }}

  # Password used to authenticate to the MySQL Galera healthcheck endpoint.
  # This value uses a generated default.
  mysql-galera-healthcheck-endpoint-password: {{ default "" .Values.secrets.MYSQL_GALERA_HEALTHCHECK_ENDPOINT_PASSWORD | b64enc | quote }}

  # Database password for storing broker state for the Persi NFS Broker
  # This value uses a generated default.
  mysql-persi-nfs-password: {{ default "" .Values.secrets.MYSQL_PERSI_NFS_PASSWORD | b64enc | quote }}

  # The password for Basic Auth used to secure the MySQL proxy API.
  # This value uses a generated default.
  mysql-proxy-admin-password: {{ default "" .Values.secrets.MYSQL_PROXY_ADMIN_PASSWORD | b64enc | quote }}

  # The password for access to MySQL by the routing-api
  # This value uses a generated default.
  mysql-routing-api-password: {{ default "" .Values.secrets.MYSQL_ROUTING_API_PASSWORD | b64enc | quote }}

  # The password for access to NATS.
  # This value uses a generated default.
  nats-password: {{ default "" .Values.secrets.NATS_PASSWORD | b64enc | quote }}

  # Basic auth password to verify on incoming Service Broker requests
  # This value uses a generated default.
  persi-nfs-broker-password: {{ default "" .Values.secrets.PERSI_NFS_BROKER_PASSWORD | b64enc | quote }}

  # PEM-encoded server certificate
  # This value uses a generated default.
  rep-server-cert: {{ default "" .Values.secrets.REP_SERVER_CERT | b64enc | quote }}

  # PEM-encoded server key
  # This value uses a generated default.
  rep-server-key: {{ default "" .Values.secrets.REP_SERVER_KEY | b64enc | quote }}

  # Support for route services is disabled when no value is configured. A robust
  # passphrase is recommended.
  # This value uses a generated default.
  router-services-secret: {{ default "" .Values.secrets.ROUTER_SERVICES_SECRET | b64enc | quote }}

  # The public ssl cert for ssl termination.
  # This value uses a generated default.
  router-ssl-cert: {{ default "" .Values.secrets.ROUTER_SSL_CERT | b64enc | quote }}

  # The private ssl key for ssl termination.
  # This value uses a generated default.
  router-ssl-key: {{ default "" .Values.secrets.ROUTER_SSL_KEY | b64enc | quote }}

  # Password for HTTP basic auth to the varz/status endpoint.
  # This value uses a generated default.
  router-status-password: {{ default "" .Values.secrets.ROUTER_STATUS_PASSWORD | b64enc | quote }}

  # The password for access to the uploader of staged droplets.
  # This value uses a generated default.
  staging-upload-password: {{ default "" .Values.secrets.STAGING_UPLOAD_PASSWORD | b64enc | quote }}

  # PEM-encoded certificate
  # This value uses a generated default.
  syslog-adapt-cert: {{ default "" .Values.secrets.SYSLOG_ADAPT_CERT | b64enc | quote }}

  # PEM-encoded key.
  # This value uses a generated default.
  syslog-adapt-key: {{ default "" .Values.secrets.SYSLOG_ADAPT_KEY | b64enc | quote }}

  # PEM-encoded certificate
  # This value uses a generated default.
  syslog-rlp-cert: {{ default "" .Values.secrets.SYSLOG_RLP_CERT | b64enc | quote }}

  # PEM-encoded key.
  # This value uses a generated default.
  syslog-rlp-key: {{ default "" .Values.secrets.SYSLOG_RLP_KEY | b64enc | quote }}

  # PEM-encoded certificate
  # This value uses a generated default.
  syslog-sched-cert: {{ default "" .Values.secrets.SYSLOG_SCHED_CERT | b64enc | quote }}

  # PEM-encoded key.
  # This value uses a generated default.
  syslog-sched-key: {{ default "" .Values.secrets.SYSLOG_SCHED_KEY | b64enc | quote }}

  # PEM-encoded client certificate for internal communication between the cloud
  # controller and TPS.
  # This value uses a generated default.
  tps-cc-client-crt: {{ default "" .Values.secrets.TPS_CC_CLIENT_CRT | b64enc | quote }}

  # PEM-encoded client key for internal communication between the cloud
  # controller and TPS.
  # This value uses a generated default.
  tps-cc-client-key: {{ default "" .Values.secrets.TPS_CC_CLIENT_KEY | b64enc | quote }}

  # PEM-encoded certificate for communication with the traffic controller of the
  # log infra structure.
  # This value uses a generated default.
  trafficcontroller-cert: {{ default "" .Values.secrets.TRAFFICCONTROLLER_CERT | b64enc | quote }}

  # PEM-encoded key for communication with the traffic controller of the log
  # infra structure.
  # This value uses a generated default.
  trafficcontroller-key: {{ default "" .Values.secrets.TRAFFICCONTROLLER_KEY | b64enc | quote }}

  # The password for UAA access by the Cloud Controller.
  # This value uses a generated default.
  uaa-cc-client-secret: {{ default "" .Values.secrets.UAA_CC_CLIENT_SECRET | b64enc | quote }}

  # The password for UAA access by the Routing API.
  # This value uses a generated default.
  uaa-clients-cc-routing-secret: {{ default "" .Values.secrets.UAA_CLIENTS_CC_ROUTING_SECRET | b64enc | quote }}

  # Used for third party service dashboard SSO.
  # This value uses a generated default.
  uaa-clients-cc-service-dashboards-client-secret: {{ default "" .Values.secrets.UAA_CLIENTS_CC_SERVICE_DASHBOARDS_CLIENT_SECRET | b64enc | quote }}

  # Used for fetching service key values from CredHub.
  # This value uses a generated default.
  uaa-clients-cc-service-key-client-secret: {{ default "" .Values.secrets.UAA_CLIENTS_CC_SERVICE_KEY_CLIENT_SECRET | b64enc | quote }}

  # The password for UAA access by the Universal Service Broker.
  # This value uses a generated default.
  uaa-clients-cf-usb-secret: {{ default "" .Values.secrets.UAA_CLIENTS_CF_USB_SECRET | b64enc | quote }}

  # The password for UAA access by the Cloud Controller for fetching usernames.
  # This value uses a generated default.
  uaa-clients-cloud-controller-username-lookup-secret: {{ default "" .Values.secrets.UAA_CLIENTS_CLOUD_CONTROLLER_USERNAME_LOOKUP_SECRET | b64enc | quote }}

  # The password for UAA access by the SSH proxy.
  # This value uses a generated default.
  uaa-clients-diego-ssh-proxy-secret: {{ default "" .Values.secrets.UAA_CLIENTS_DIEGO_SSH_PROXY_SECRET | b64enc | quote }}

  # The password for UAA access by doppler.
  # This value uses a generated default.
  uaa-clients-doppler-secret: {{ default "" .Values.secrets.UAA_CLIENTS_DOPPLER_SECRET | b64enc | quote }}

  # The password for UAA access by the gorouter.
  # This value uses a generated default.
  uaa-clients-gorouter-secret: {{ default "" .Values.secrets.UAA_CLIENTS_GOROUTER_SECRET | b64enc | quote }}

  # The password for UAA access by the login client.
  # This value uses a generated default.
  uaa-clients-login-secret: {{ default "" .Values.secrets.UAA_CLIENTS_LOGIN_SECRET | b64enc | quote }}

  # The password for UAA access by the task creating the cluster administrator
  # user
  # This value uses a generated default.
  uaa-clients-scf-auto-config-secret: {{ default "" .Values.secrets.UAA_CLIENTS_SCF_AUTO_CONFIG_SECRET | b64enc | quote }}

  # The password for UAA access by the TCP emitter.
  # This value uses a generated default.
  uaa-clients-tcp-emitter-secret: {{ default "" .Values.secrets.UAA_CLIENTS_TCP_EMITTER_SECRET | b64enc | quote }}

  # The password for UAA access by the TCP router.
  # This value uses a generated default.
  uaa-clients-tcp-router-secret: {{ default "" .Values.secrets.UAA_CLIENTS_TCP_ROUTER_SECRET | b64enc | quote }}

kind: "Secret"
metadata:
  name: "secrets"
  labels:
    skiff-role-name: "secrets"
