---
# The secret-generation role contains the following jobs:
#
# - generate-secrets: This job will generate the secrets for the cluster
apiVersion: "batch/v1"
kind: "Job"
metadata:
  name: "secret-generation-{{ .Release.Revision }}"
spec:
  template:
    metadata:
      name: "secret-generation"
      labels:
        skiff-role-name: "secret-generation"
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
    spec:
      containers:
      - env:
        - name: "CATS_SUITES"
          value: {{ .Values.env.CATS_SUITES | quote }}
        - name: "DOMAIN"
          value: {{ required "DOMAIN configuration missing" .Values.env.DOMAIN | quote }}
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_SECRETS_GENERATION_COUNTER"
          value: {{ .Values.kube.secrets_generation_counter | quote }}
        - name: "KUBE_SECRETS_GENERATION_NAME"
          value: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        - name: "KUBE_SERVICE_DOMAIN_SUFFIX"
          value: {{ .Values.env.KUBE_SERVICE_DOMAIN_SUFFIX | quote }}
        - name: "SCF_LOG_HOST"
          value: {{ .Values.env.SCF_LOG_HOST | quote }}
        - name: "SCF_LOG_PORT"
          value: {{ .Values.env.SCF_LOG_PORT | quote }}
        - name: "SCF_LOG_PROTOCOL"
          value: {{ required "SCF_LOG_PROTOCOL configuration missing" .Values.env.SCF_LOG_PROTOCOL | quote }}
        image: "{{ .Values.kube.registry.hostname }}/{{ .Values.kube.organization }}/scf-secret-generation:8db93cce5522bbfdb7d4673de15829205d3b7e24"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "secret-generation"
        ports: ~
        readinessProbe: ~
        resources:
          requests:
            {{- if and .Values.sizing.memory.requests .Values.sizing.secret_generation.memory.request }}
            memory: "{{ int .Values.sizing.secret_generation.memory.request }}Mi"
            {{- end }}

            {{- if and .Values.sizing.cpu.requests .Values.sizing.secret_generation.cpu.request }}
            cpu: "{{ int .Values.sizing.secret_generation.cpu.request }}m"
            {{- end }}

          limits:
            {{- if and .Values.sizing.memory.limits .Values.sizing.secret_generation.memory.limit }}
            memory: "{{ int .Values.sizing.secret_generation.memory.limit }}Mi"
            {{- end }}

            {{- if and .Values.sizing.cpu.limits .Values.sizing.secret_generation.cpu.limit }}
            cpu: "{{ int .Values.sizing.secret_generation.cpu.limit }}m"
            {{- end }}

        securityContext:
          {{- if has "ALL" .Values.sizing.secret_generation.capabilities }}
          privileged: true
          {{- end }}

          {{- if not (has "ALL" .Values.sizing.secret_generation.capabilities) }}
          capabilities:
            add:
            {{- range .Values.sizing.secret_generation.capabilities }}
            - {{ . | upper }}
            {{- end }}
          {{- end }}

        volumeMounts: ~
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "OnFailure"
      {{- if eq (printf "%s" .Values.kube.auth) "rbac" }}
      serviceAccountName: "secret-generator"
      {{- end }}
      terminationGracePeriodSeconds: 600
      volumes: ~
