---
# The secret-generation role contains the following jobs:
#
# - generate-secrets: This job will generate the secrets for the cluster
apiVersion: {{ if or (gt (int .Capabilities.KubeVersion.Major) 1) (and (eq (int .Capabilities.KubeVersion.Major) 1) (ge (int .Capabilities.KubeVersion.Minor) 6)) -}} batch/v1 {{- else -}} extensions/v1beta1 {{- end }}
kind: "Job"
metadata:
  name: "secret-generation-{{ .Release.Revision }}"
spec:
  template:
    metadata:
      name: "secret-generation"
      labels:
        skiff-role-name: "secret-generation"
    spec:
      containers:
      - env:
        - name: "CATS_SUITES"
          value: {{ .Values.env.CATS_SUITES | quote }}
        - name: "DOMAIN"
          value: {{ required "DOMAIN configuration missing" .Values.env.DOMAIN | quote }}
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_SERVICE_DOMAIN_SUFFIX"
          value: {{ .Values.env.KUBE_SERVICE_DOMAIN_SUFFIX | quote }}
        - name: "KUBE_SIZING_API_COUNT"
          value: {{ .Values.sizing.api.count | quote }}
        - name: "KUBE_SIZING_BLOBSTORE_COUNT"
          value: {{ .Values.sizing.blobstore.count | quote }}
        - name: "KUBE_SIZING_CC_UPLOADER_COUNT"
          value: {{ .Values.sizing.cc_uploader.count | quote }}
        - name: "KUBE_SIZING_CF_USB_COUNT"
          value: {{ .Values.sizing.cf_usb.count | quote }}
        - name: "KUBE_SIZING_DIEGO_API_COUNT"
          value: {{ .Values.sizing.diego_api.count | quote }}
        - name: "KUBE_SIZING_DIEGO_BRAIN_COUNT"
          value: {{ .Values.sizing.diego_brain.count | quote }}
        - name: "KUBE_SIZING_DIEGO_CELL_COUNT"
          value: {{ .Values.sizing.diego_cell.count | quote }}
        - name: "RELEASE_REVISION"
          value: {{ .Release.Revision | quote }}
        - name: "SCF_LOG_HOST"
          value: {{ .Values.env.SCF_LOG_HOST | quote }}
        - name: "SCF_LOG_PORT"
          value: {{ .Values.env.SCF_LOG_PORT | quote }}
        - name: "SCF_LOG_PROTOCOL"
          value: {{ required "SCF_LOG_PROTOCOL configuration missing" .Values.env.SCF_LOG_PROTOCOL | quote }}
        image: "{{ .Values.kube.registry.hostname }}/{{ .Values.kube.organization }}/scf-secret-generation:a40203255fac753b0e9537e05f00f5bc41ae6c6a"
        livenessProbe: ~
        name: "secret-generation"
        ports: ~
        readinessProbe: ~
        resources: ~
        securityContext: ~
        volumeMounts: ~
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "OnFailure"
      {{- if eq (printf "%s" .Values.kube.auth) "rbac" }}
      serviceAccountName: "secret-generator"
      {{- end }}
