---
apiVersion: "v1"
data:
  # The password for the cluster administrator.
  # This value is immutable and must not be changed once set.
  cluster-admin-password: {{ required "secrets.CLUSTER_ADMIN_PASSWORD has not been set" .Values.secrets.CLUSTER_ADMIN_PASSWORD | b64enc | quote }}

  # LDAP service account password (required for LDAP integration only)
  # This value is immutable and must not be changed once set.
  persi-nfs-driver-ldap-password: {{ required "secrets.PERSI_NFS_DRIVER_LDAP_PASSWORD has not been set" .Values.secrets.PERSI_NFS_DRIVER_LDAP_PASSWORD | b64enc | quote }}

  # The password of the admin client - a client named admin with uaa.admin as an
  # authority.
  # This value is immutable and must not be changed once set.
  uaa-admin-client-secret: {{ required "secrets.UAA_ADMIN_CLIENT_SECRET has not been set" .Values.secrets.UAA_ADMIN_CLIENT_SECRET | b64enc | quote }}

  # The CA certificate for UAA
  uaa-ca-cert: {{ required "secrets.UAA_CA_CERT has not been set" .Values.secrets.UAA_CA_CERT | b64enc | quote }}

  # PEM encoded RSA private key used to identify host.
  # This value uses a generated default.
  app-ssh-key: {{ default "" .Values.secrets.APP_SSH_KEY | b64enc | quote }}

  # MD5 fingerprint of the host key of the SSH proxy that brokers connections to
  # application instances.
  # This value uses a generated default.
  app-ssh-key-fingerprint: {{ default "" .Values.secrets.APP_SSH_KEY_FINGERPRINT | b64enc | quote }}

  # PEM-encoded certificate
  # This value uses a generated default.
  auctioneer-rep-cert: {{ default "" .Values.secrets.AUCTIONEER_REP_CERT | b64enc | quote }}

  # PEM-encoded key
  # This value uses a generated default.
  auctioneer-rep-key: {{ default "" .Values.secrets.AUCTIONEER_REP_KEY | b64enc | quote }}

  # PEM-encoded server certificate
  # This value uses a generated default.
  auctioneer-server-cert: {{ default "" .Values.secrets.AUCTIONEER_SERVER_CERT | b64enc | quote }}

  # PEM-encoded server key
  # This value uses a generated default.
  auctioneer-server-key: {{ default "" .Values.secrets.AUCTIONEER_SERVER_KEY | b64enc | quote }}

  # PEM-encoded certificate
  # This value uses a generated default.
  bbs-auctioneer-cert: {{ default "" .Values.secrets.BBS_AUCTIONEER_CERT | b64enc | quote }}

  # PEM-encoded key
  # This value uses a generated default.
  bbs-auctioneer-key: {{ default "" .Values.secrets.BBS_AUCTIONEER_KEY | b64enc | quote }}

  # PEM-encoded client certificate.
  # This value uses a generated default.
  bbs-client-crt: {{ default "" .Values.secrets.BBS_CLIENT_CRT | b64enc | quote }}

  # PEM-encoded client key.
  # This value uses a generated default.
  bbs-client-key: {{ default "" .Values.secrets.BBS_CLIENT_KEY | b64enc | quote }}

  # PEM-encoded certificate
  # This value uses a generated default.
  bbs-rep-cert: {{ default "" .Values.secrets.BBS_REP_CERT | b64enc | quote }}

  # PEM-encoded key
  # This value uses a generated default.
  bbs-rep-key: {{ default "" .Values.secrets.BBS_REP_KEY | b64enc | quote }}

  # PEM-encoded client certificate.
  # This value uses a generated default.
  bbs-server-crt: {{ default "" .Values.secrets.BBS_SERVER_CRT | b64enc | quote }}

  # PEM-encoded client key.
  # This value uses a generated default.
  bbs-server-key: {{ default "" .Values.secrets.BBS_SERVER_KEY | b64enc | quote }}

  # The PEM-encoded certificate (optionally as a certificate chain) for serving
  # blobs over TLS/SSL.
  # This value uses a generated default.
  blobstore-tls-cert: {{ default "" .Values.secrets.BLOBSTORE_TLS_CERT | b64enc | quote }}

  # The PEM-encoded private key for signing TLS/SSL traffic.
  # This value uses a generated default.
  blobstore-tls-key: {{ default "" .Values.secrets.BLOBSTORE_TLS_KEY | b64enc | quote }}

  # The PEM-encoded certificate for internal cloud controller traffic.
  # This value uses a generated default.
  cc-server-crt: {{ default "" .Values.secrets.CC_SERVER_CRT | b64enc | quote }}

  # The PEM-encoded private key for internal cloud controller traffic.
  # This value uses a generated default.
  cc-server-key: {{ default "" .Values.secrets.CC_SERVER_KEY | b64enc | quote }}

  # The PEM-encoded certificate for internal cloud controller uploader traffic.
  # This value uses a generated default.
  cc-uploader-crt: {{ default "" .Values.secrets.CC_UPLOADER_CRT | b64enc | quote }}

  # The PEM-encoded private key for internal cloud controller uploader traffic.
  # This value uses a generated default.
  cc-uploader-key: {{ default "" .Values.secrets.CC_UPLOADER_KEY | b64enc | quote }}

  # PEM-encoded broker server certificate.
  # This value uses a generated default.
  cf-usb-broker-server-cert: {{ default "" .Values.secrets.CF_USB_BROKER_SERVER_CERT | b64enc | quote }}

  # PEM-encoded broker server key.
  # This value uses a generated default.
  cf-usb-broker-server-key: {{ default "" .Values.secrets.CF_USB_BROKER_SERVER_KEY | b64enc | quote }}

  # PEM-encoded client certificate
  # This value uses a generated default.
  diego-client-cert: {{ default "" .Values.secrets.DIEGO_CLIENT_CERT | b64enc | quote }}

  # PEM-encoded client key
  # This value uses a generated default.
  diego-client-key: {{ default "" .Values.secrets.DIEGO_CLIENT_KEY | b64enc | quote }}

  # PEM-encoded certificate.
  # This value uses a generated default.
  doppler-cert: {{ default "" .Values.secrets.DOPPLER_CERT | b64enc | quote }}

  # PEM-encoded key.
  # This value uses a generated default.
  doppler-key: {{ default "" .Values.secrets.DOPPLER_KEY | b64enc | quote }}

  # PEM-encoded CA certificate used to sign the TLS certificate used by all
  # components to secure their communications.
  # This value uses a generated default.
  internal-ca-cert: {{ default "" .Values.secrets.INTERNAL_CA_CERT | b64enc | quote }}

  # PEM-encoded CA key.
  # This value uses a generated default.
  internal-ca-key: {{ default "" .Values.secrets.INTERNAL_CA_KEY | b64enc | quote }}

  # PEM-encoded certificate.
  # This value uses a generated default.
  metron-cert: {{ default "" .Values.secrets.METRON_CERT | b64enc | quote }}

  # PEM-encoded key.
  # This value uses a generated default.
  metron-key: {{ default "" .Values.secrets.METRON_KEY | b64enc | quote }}

  # PEM-encoded server certificate
  # This value uses a generated default.
  rep-server-cert: {{ default "" .Values.secrets.REP_SERVER_CERT | b64enc | quote }}

  # PEM-encoded server key
  # This value uses a generated default.
  rep-server-key: {{ default "" .Values.secrets.REP_SERVER_KEY | b64enc | quote }}

  # The public ssl cert for ssl termination.
  # This value uses a generated default.
  router-ssl-cert: {{ default "" .Values.secrets.ROUTER_SSL_CERT | b64enc | quote }}

  # The private ssl key for ssl termination.
  # This value uses a generated default.
  router-ssl-key: {{ default "" .Values.secrets.ROUTER_SSL_KEY | b64enc | quote }}

  # PEM-encoded certificate
  # This value uses a generated default.
  syslog-adapt-cert: {{ default "" .Values.secrets.SYSLOG_ADAPT_CERT | b64enc | quote }}

  # PEM-encoded key.
  # This value uses a generated default.
  syslog-adapt-key: {{ default "" .Values.secrets.SYSLOG_ADAPT_KEY | b64enc | quote }}

  # PEM-encoded certificate
  # This value uses a generated default.
  syslog-rlp-cert: {{ default "" .Values.secrets.SYSLOG_RLP_CERT | b64enc | quote }}

  # PEM-encoded key.
  # This value uses a generated default.
  syslog-rlp-key: {{ default "" .Values.secrets.SYSLOG_RLP_KEY | b64enc | quote }}

  # PEM-encoded certificate
  # This value uses a generated default.
  syslog-sched-cert: {{ default "" .Values.secrets.SYSLOG_SCHED_CERT | b64enc | quote }}

  # PEM-encoded key.
  # This value uses a generated default.
  syslog-sched-key: {{ default "" .Values.secrets.SYSLOG_SCHED_KEY | b64enc | quote }}

  # PEM-encoded client certificate for internal communication between the cloud
  # controller and TPS.
  # This value uses a generated default.
  tps-cc-client-crt: {{ default "" .Values.secrets.TPS_CC_CLIENT_CRT | b64enc | quote }}

  # PEM-encoded client key for internal communication between the cloud
  # controller and TPS.
  # This value uses a generated default.
  tps-cc-client-key: {{ default "" .Values.secrets.TPS_CC_CLIENT_KEY | b64enc | quote }}

  # PEM-encoded certificate for communication with the traffic controller of the
  # log infra structure.
  # This value uses a generated default.
  trafficcontroller-cert: {{ default "" .Values.secrets.TRAFFICCONTROLLER_CERT | b64enc | quote }}

  # PEM-encoded key for communication with the traffic controller of the log
  # infra structure.
  # This value uses a generated default.
  trafficcontroller-key: {{ default "" .Values.secrets.TRAFFICCONTROLLER_KEY | b64enc | quote }}

kind: "Secret"
metadata:
  name: "secrets"
  labels:
    skiff-role-name: "secrets"
