---
# The syslog-adapter role contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# Also: adapter, metron_agent

{{- if gt (int .Values.sizing.syslog_adapter.count) 65535 }}
_maxReplicas: {{ fail "syslog_adapter cannot have more than 65535 instances" }}
{{- end }}

{{- if and .Values.sizing.HA (and (ne (int .Values.sizing.syslog_adapter.count) 1) (lt (int .Values.sizing.syslog_adapter.count) 2)) }}
_minHAReplicas: {{ fail "syslog_adapter must have at least 2 instances for HA" }}
{{- end }}

{{- if lt (int .Values.sizing.memory.limit_factor) 1 }}
_minLimitFactor: {{ fail "The memory limit factor must be at least 1" }}
{{- end }}

{{- if lt (int .Values.sizing.syslog_adapter.count) 1 }}
_minReplicas: {{ fail "syslog_adapter must have at least 1 instances" }}
{{- end }}

apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "syslog-adapter"
  labels:
    skiff-role-name: "syslog-adapter"
spec:
  replicas: {{ if and .Values.sizing.HA (eq (int .Values.sizing.syslog_adapter.count) 1) -}} 2 {{- else -}} {{ .Values.sizing.syslog_adapter.count }} {{- end }}
  selector:
    matchLabels:
      skiff-role-name: "syslog-adapter"
  template:
    metadata:
      name: "syslog-adapter"
      labels:
        skiff-role-name: "syslog-adapter"
    spec:
      containers:
      - env:
        - name: "CATS_SUITES"
          value: {{ .Values.env.CATS_SUITES | quote }}
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secret-{{ .Release.Revision }}"
        - name: "INTERNAL_CA_KEY"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-key"
              name: "secret-{{ .Release.Revision }}"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_AZ"
          value: "z1"
        - name: "KUBE_SERVICE_DOMAIN_SUFFIX"
          value: {{ .Values.env.KUBE_SERVICE_DOMAIN_SUFFIX | quote }}
        - name: "METRON_CERT"
          valueFrom:
            secretKeyRef:
              key: "metron-cert"
              name: "secret-{{ .Release.Revision }}"
        - name: "METRON_KEY"
          valueFrom:
            secretKeyRef:
              key: "metron-key"
              name: "secret-{{ .Release.Revision }}"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secret-{{ .Release.Revision }}"
        - name: "RELEASE_REVISION"
          value: {{ .Release.Revision | quote }}
        - name: "SCF_LOG_HOST"
          value: {{ .Values.env.SCF_LOG_HOST | quote }}
        - name: "SCF_LOG_PORT"
          value: {{ .Values.env.SCF_LOG_PORT | quote }}
        - name: "SCF_LOG_PROTOCOL"
          value: {{ required "SCF_LOG_PROTOCOL configuration missing" .Values.env.SCF_LOG_PROTOCOL | quote }}
        - name: "SYSLOG_ADAPT_CERT"
          valueFrom:
            secretKeyRef:
              key: "syslog-adapt-cert"
              name: "secret-{{ .Release.Revision }}"
        - name: "SYSLOG_ADAPT_KEY"
          valueFrom:
            secretKeyRef:
              key: "syslog-adapt-key"
              name: "secret-{{ .Release.Revision }}"
        image: "{{ .Values.kube.registry.hostname }}/{{ .Values.kube.organization }}/scf-syslog-adapter:dfe0615a4a7ad55a776858f6440ab94384e28c32"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "syslog-adapter"
        ports:
        - containerPort: 4443
          name: "adapter"
          protocol: "TCP"
        - containerPort: 8080
          name: "adapter-health"
          protocol: "TCP"
        readinessProbe:
          failureThreshold: 0
          httpGet:
            path: "/health"
            port: 8080
            scheme: "HTTP"
          initialDelaySeconds: 0
          periodSeconds: 0
          successThreshold: 0
          timeoutSeconds: 0
        resources:
          {{- if .Values.sizing.memory.requests }}
          requests:
            memory: "{{ int .Values.sizing.syslog_adapter.memory }}Mi"
          {{- end }}

          {{- if .Values.sizing.memory.limits }}
          limits:
            memory: "{{ (mul (int .Values.sizing.memory.limit_factor) (int .Values.sizing.syslog_adapter.memory)) }}Mi"
          {{- end }}

        securityContext: ~
        volumeMounts: ~
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 600
---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "syslog-adapter"
  spec:
    ports:
    - name: "adapter"
      port: 4443
      protocol: "TCP"
      targetPort: "adapter"
    - name: "adapter-health"
      port: 8080
      protocol: "TCP"
      targetPort: "adapter-health"
    selector:
      skiff-role-name: "syslog-adapter"
    type: {{ if .Values.services.loadbalanced }} LoadBalancer {{ else }} ClusterIP {{ end }}
kind: "List"
