---
# The syslog-rlp role contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# Also: metron_agent, reverse_log_proxy

{{- if gt (int .Values.sizing.syslog_rlp.count) 65535 }}
_maxReplicas: {{ fail "syslog_rlp cannot have more than 65535 instances" }}
{{- end }}

{{- if and .Values.sizing.HA (and (ne (int .Values.sizing.syslog_rlp.count) 1) (lt (int .Values.sizing.syslog_rlp.count) 2)) }}
_minHAReplicas: {{ fail "syslog_rlp must have at least 2 instances for HA" }}
{{- end }}

{{- if lt (int .Values.sizing.syslog_rlp.count) 1 }}
_minReplicas: {{ fail "syslog_rlp must have at least 1 instances" }}
{{- end }}

apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "syslog-rlp"
  labels:
    skiff-role-name: "syslog-rlp"
spec:
  replicas: {{ if and .Values.sizing.HA (eq (int .Values.sizing.syslog_rlp.count) 1) -}} 2 {{- else -}} {{ .Values.sizing.syslog_rlp.count }} {{- end }}
  selector:
    matchLabels:
      skiff-role-name: "syslog-rlp"
  template:
    metadata:
      name: "syslog-rlp"
      labels:
        skiff-role-name: "syslog-rlp"
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: "skiff-role-name"
                  operator: "In"
                  values:
                  - "syslog-rlp"
              topologyKey: "beta.kubernetes.io/os"
            weight: 100
        {{- if .Values.sizing.syslog_rlp.affinity.nodeAffinity }}
        nodeAffinity: {{ toJson .Values.sizing.syslog_rlp.affinity.nodeAffinity }}
        {{- end }}
      containers:
      - env:
        - name: "CATS_SUITES"
          value: {{ .Values.env.CATS_SUITES | quote }}

        {{- if not .Values.secrets.INTERNAL_CA_CERT }}
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.INTERNAL_CA_CERT }}
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.INTERNAL_CA_KEY }}
        - name: "INTERNAL_CA_KEY"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-key"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.INTERNAL_CA_KEY }}
        - name: "INTERNAL_CA_KEY"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-key"
              name: "secrets"
        {{- end }}

        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_AZ"
          value: "z1"
        - name: "KUBE_SERVICE_DOMAIN_SUFFIX"
          value: {{ .Values.env.KUBE_SERVICE_DOMAIN_SUFFIX | quote }}

        {{- if not .Values.secrets.METRON_CERT }}
        - name: "METRON_CERT"
          valueFrom:
            secretKeyRef:
              key: "metron-cert"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.METRON_CERT }}
        - name: "METRON_CERT"
          valueFrom:
            secretKeyRef:
              key: "metron-cert"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.METRON_KEY }}
        - name: "METRON_KEY"
          valueFrom:
            secretKeyRef:
              key: "metron-key"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.METRON_KEY }}
        - name: "METRON_KEY"
          valueFrom:
            secretKeyRef:
              key: "metron-key"
              name: "secrets"
        {{- end }}

        {{- if .Values.secrets.MONIT_PASSWORD }}
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.MONIT_PASSWORD }}
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        - name: "SCF_LOG_HOST"
          value: {{ .Values.env.SCF_LOG_HOST | quote }}
        - name: "SCF_LOG_PORT"
          value: {{ .Values.env.SCF_LOG_PORT | quote }}
        - name: "SCF_LOG_PROTOCOL"
          value: {{ required "SCF_LOG_PROTOCOL configuration missing" .Values.env.SCF_LOG_PROTOCOL | quote }}

        {{- if not .Values.secrets.SYSLOG_RLP_CERT }}
        - name: "SYSLOG_RLP_CERT"
          valueFrom:
            secretKeyRef:
              key: "syslog-rlp-cert"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.SYSLOG_RLP_CERT }}
        - name: "SYSLOG_RLP_CERT"
          valueFrom:
            secretKeyRef:
              key: "syslog-rlp-cert"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.SYSLOG_RLP_KEY }}
        - name: "SYSLOG_RLP_KEY"
          valueFrom:
            secretKeyRef:
              key: "syslog-rlp-key"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.SYSLOG_RLP_KEY }}
        - name: "SYSLOG_RLP_KEY"
          valueFrom:
            secretKeyRef:
              key: "syslog-rlp-key"
              name: "secrets"
        {{- end }}

        image: "{{ .Values.kube.registry.hostname }}/{{ .Values.kube.organization }}/scf-syslog-rlp:7256fc28125c1d86623e745c5aa07f479a27d208"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "syslog-rlp"
        ports:
        - containerPort: 8082
          name: "rlp"
          protocol: "TCP"
        readinessProbe:
          tcpSocket:
            port: 8082
        resources:
          requests:
            {{- if and .Values.sizing.memory.requests .Values.sizing.syslog_rlp.memory.request }}
            memory: "{{ int .Values.sizing.syslog_rlp.memory.request }}Mi"
            {{- end }}

            {{- if and .Values.sizing.cpu.requests .Values.sizing.syslog_rlp.cpu.request }}
            cpu: "{{ int .Values.sizing.syslog_rlp.cpu.request }}m"
            {{- end }}

          limits:
            {{- if and .Values.sizing.memory.limits .Values.sizing.syslog_rlp.memory.limit }}
            memory: "{{ int .Values.sizing.syslog_rlp.memory.limit }}Mi"
            {{- end }}

            {{- if and .Values.sizing.cpu.limits .Values.sizing.syslog_rlp.cpu.limit }}
            cpu: "{{ int .Values.sizing.syslog_rlp.cpu.limit }}m"
            {{- end }}

        securityContext:
          {{- if has "ALL" .Values.sizing.syslog_rlp.capabilities }}
          privileged: true
          {{- end }}

          {{- if not (has "ALL" .Values.sizing.syslog_rlp.capabilities) }}
          capabilities:
            add:
            {{- range .Values.sizing.syslog_rlp.capabilities }}
            - {{ . | upper }}
            {{- end }}
          {{- end }}

        volumeMounts: ~
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 600
      volumes: ~
---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "syslog-rlp"
  spec:
    ports:
    - name: "rlp"
      port: 8082
      protocol: "TCP"
      targetPort: "rlp"
    selector:
      skiff-role-name: "syslog-rlp"
    type: {{ if .Values.services.loadbalanced }} LoadBalancer {{ else }} ClusterIP {{ end }}
kind: "List"
