---
# The syslog-rlp role contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# Also: metron_agent, reverse_log_proxy

{{- if gt (int .Values.sizing.syslog_rlp.count) 65535 }}
_maxReplicas: {{ fail "syslog_rlp cannot have more than 65535 instances" }}
{{- end }}

{{- if and .Values.sizing.HA (and (ne (int .Values.sizing.syslog_rlp.count) 1) (lt (int .Values.sizing.syslog_rlp.count) 2)) }}
_minHAReplicas: {{ fail "syslog_rlp must have at least 2 instances for HA" }}
{{- end }}

{{- if lt (int .Values.sizing.syslog_rlp.count) 1 }}
_minReplicas: {{ fail "syslog_rlp must have at least 1 instances" }}
{{- end }}

apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "syslog-rlp"
  labels:
    skiff-role-name: "syslog-rlp"
spec:
  replicas: {{ if and .Values.sizing.HA (eq (int .Values.sizing.syslog_rlp.count) 1) -}} 2 {{- else -}} {{ .Values.sizing.syslog_rlp.count }} {{- end }}
  selector:
    matchLabels:
      skiff-role-name: "syslog-rlp"
  template:
    metadata:
      name: "syslog-rlp"
      labels:
        skiff-role-name: "syslog-rlp"
    spec:
      containers:
      - env:
        - name: "CATS_SUITES"
          value: {{ .Values.env.CATS_SUITES | quote }}
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secret"
        - name: "INTERNAL_CA_KEY"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-key"
              name: "secret"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_AZ"
          value: "z1"
        - name: "KUBE_SERVICE_DOMAIN_SUFFIX"
          value: {{ .Values.env.KUBE_SERVICE_DOMAIN_SUFFIX | quote }}
        - name: "METRON_CERT"
          valueFrom:
            secretKeyRef:
              key: "metron-cert"
              name: "secret"
        - name: "METRON_KEY"
          valueFrom:
            secretKeyRef:
              key: "metron-key"
              name: "secret"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secret"
        - name: "RELEASE_REVISION"
          value: {{ .Release.Revision | quote }}
        - name: "SCF_LOG_HOST"
          value: {{ .Values.env.SCF_LOG_HOST | quote }}
        - name: "SCF_LOG_PORT"
          value: {{ .Values.env.SCF_LOG_PORT | quote }}
        - name: "SCF_LOG_PROTOCOL"
          value: {{ required "SCF_LOG_PROTOCOL configuration missing" .Values.env.SCF_LOG_PROTOCOL | quote }}
        - name: "SYSLOG_RLP_CERT"
          valueFrom:
            secretKeyRef:
              key: "syslog-rlp-cert"
              name: "secret"
        - name: "SYSLOG_RLP_KEY"
          valueFrom:
            secretKeyRef:
              key: "syslog-rlp-key"
              name: "secret"
        image: "{{ .Values.kube.registry.hostname }}/{{ .Values.kube.organization }}/scf-syslog-rlp:f79fad2a5053a597f9926f3b33254f3ffff61ff7"
        livenessProbe: ~
        name: "syslog-rlp"
        ports:
        - containerPort: 8082
          name: "rlp"
          protocol: "TCP"
        readinessProbe:
          tcpSocket:
            port: 8082
        resources: ~
        securityContext: ~
        volumeMounts: ~
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "syslog-rlp"
  spec:
    ports:
    - name: "rlp"
      port: 8082
      protocol: "TCP"
      targetPort: "rlp"
    selector:
      skiff-role-name: "syslog-rlp"
    type: {{ if .Values.services.loadbalanced }} LoadBalancer {{ else }} ClusterIP {{ end }}
kind: "List"
