apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cert-exporter.fullname" . }}-nodes
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ include "cert-exporter.fullname" . }}-nodes
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cert-exporter.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: 
  - ""
  resources:
  - "secrets"
  verbs:
  - "get"
  - "list"
