{{- if .Values.customSecret.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cert-exporter.fullname" . }}-custom-secret
roleRef:
  kind: ClusterRole
  name: {{ template "cert-exporter.fullname" . }}-custom-secret
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ template "cert-exporter.fullname" . }}-custom-secret
  namespace: {{ .Release.Namespace }}
{{- end }}
