{{- if .Values.customSecret.enabled }}
{{- range .Values.customSecret.certs }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cert-exporter.fullname" $ }}-custom-secret-{{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels: 
{{- include "cert-exporter.labels" $ | nindent 4 }}  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "cert-exporter.name" $ }}
      heritage: {{ $.Release.Name }}
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app: {{ include "cert-exporter.name" $ }}
        heritage: {{ $.Release.Name }}
    spec:
    {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "cert-exporter.fullname" $ }}-custom-secret
      containers:
        - name: {{ $.Chart.Name }}
          image: {{ $.Values.image.repository }}:{{ $.Values.image.tag }}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          command:
            - cert-exporter
          args:
          {{- if .namespace }}
            - --secrets-namespace={{ .namespace }}
          {{- end }}
          {{- range $value := .includeKeys }}
            - --secrets-include-glob={{ $value }}
          {{- end }}
          {{- range $value := .excludeKeys }}
            - --secrets-exclude-glob={{ $value }}
          {{- end }}
          {{- range $value := .labelSelector }}
            - --secrets-label-selector={{ $value }}
          {{- end }}
          {{- range $value := .annotationSelector }}
            - --secrets-annotation-selector={{ $value }}
          {{- end }}
            - --alsologtostderr
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
      {{- with $.Values.customSecret.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.customSecret.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- end }}
{{- end }}
