
{{- if .Values.customSecret.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cert-exporter.fullname" . }}-custom-secret
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "cert-exporter.labels" . | nindent 4 }}  
{{- end }}
