apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cert-exporter.fullname" . }}-secret
  labels: 
    helm.sh/chart: {{ include "cert-exporter.chart" . }}
    app.kubernetes.io/name: {{ include "cert-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cert-exporter.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: {{ include "cert-exporter.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "cert-exporter.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["./app"]
          args:
            - --include-kubeconfig-glob=/etc/kubernetes/*.conf
            - --exclude-kubeconfig-glob=/etc/kubernetes/kubelet.conf
            - --include-cert-glob=/etc/kubernetes/pki/*.crt
            - --include-cert-glob=/etc/kubernetes/pki/etcd/*.crt
            - --include-cert-glob=/var/lib/kubelet/pki/*.crt
            - --alsologtostderr
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
