apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cert-exporter.fullname" . }}-node
  labels:
{{- include "cert-exporter.labels" . | nindent 4 }}  
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ include "cert-exporter.fullname" . }}-node
  verbs:
  - use
