apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "cert-exporter.fullname" . }}-node
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "cert-exporter.labels" . | nindent 4 }}  
spec:
  selector:
    matchLabels:
      app: {{ include "cert-exporter.name" . }}
      heritage: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app: {{ include "cert-exporter.name" . }}
        heritage: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "cert-exporter.fullname" . }}-node
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      volumes:
        - name: kubelet-pki
          hostPath:
            path: /var/lib/kubelet/pki
            type: Directory
        - name: kube-pki
          hostPath:
            path: /etc/kubernetes
            type: Directory
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - cert-exporter
          args:
            - --include-kubeconfig-glob=/etc/kubernetes/*.conf
            - --include-cert-glob=/etc/kubernetes/pki/*.crt
            - --include-cert-glob=/etc/kubernetes/pki/etcd/*.crt
            - --include-cert-glob=/var/lib/kubelet/pki/*.crt
            - --alsologtostderr
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/kubelet/pki
              name: kubelet-pki
              readOnly: true
            - mountPath: /etc/kubernetes
              name: kube-pki
              readOnly: true
          securityContext:
            runAsUser: 0
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
