apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cert-exporter.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels: 
{{- include "cert-exporter.labels" . | nindent 4 }}  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "cert-exporter.name" . }}
      heritage: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app: {{ include "cert-exporter.name" . }}
        heritage: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "cert-exporter.fullname" . }}-secret
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["cert-exporter"]
          args:
            - --secrets-namespace=kube-system
            - --secrets-label-selector=monitor-cert
            - --secrets-include-glob=*.crt
            - --secrets-exclude-glob=tls.key
            - --alsologtostderr
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
