apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cert-exporter.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "cert-exporter.labels" . | nindent 4 }}  
