---
env:
  # Base domain name of the UAA endpoint; `uaa.${DOMAIN}` must be correctly
  # configured to point to this UAA instance
  DOMAIN: ~

  HCP_SERVICE_DOMAIN_SUFFIX: ~

  # PEM-encoded CA certificate used to sign the TLS certificate used by all
  # components to secure their communications.
  INTERNAL_CA_CERT: ~

  # PEM-encoded CA key.
  INTERNAL_CA_KEY: ~

  JWT_SIGNING_PEM: "-----BEGIN RSA PRIVATE KEY-----\nMIIJKQIBAAKCAgEAoYj+Akdz0ZcGUxikRHlrqYlSg3z3puMhLH+S8Dom1Ho7gBhH\nt0ltlY6IyL2kXA/AlvuDlln17J/P92nZHCV4nNxqMGG8cmSG7svq2FARdn2lmgP5\nGI5n4Rtu8Irod1P411nCskpQilBFBWh68svpkgxBcZiuYp6p+d5q8ASKZbHr6Jeu\nk+7QzGBLg5yuSSxvbkDwPYnq1v8E7aO0FtELMeUs1HExHHJ/zRS9NQX6kGPP+MQV\nuNpIfbKiuY1BYOIlKwEEFyIa3u08dk6WRGRpYssnPU+6yiqTSULeIGBC84hHyecv\nezVFs3Ddo5iloWs56IPwSWdCZVmQLRqoWBld0qbImSfyjN6gAoC35tTxRsWJ6IMJ\nAYzYnfd8sUuEXvBPAJFpLPZKuRVRft6hxVrnIxSfFzqPOLRq87LAx7fi8RU+A4AX\n9+24WV2K1iPOLq7XKVG9hNuwJBzl4SYPD3WtkN83fa9zkx9YwDY/rHpYlC1giCse\n9kMR9FC5slvXM0PeZ1GGD4hZkrEVu3rzKxEdVepXug0FxjYE8cqAWr088PEf60T+\nYDLEQP6jYZKhOJ6400QxNOdmH8nN2DOECTwD1JRcmrYF8BThzKYczKdAwwZNovvC\nYzSh4mlJP20A6wrhWpGSJWY8jhNSNIr+RKxrBzUg6lKFyxYxeUbCGHDCK9kCAwEA\nAQKCAgBkhOj75hbOX9qRrw3Zhm1WrJtqM0Ow2Dn2hNSdJLKxGfcYuQM3rTvCC1ZX\nBJvYpfzEd3LlBsogGzrAzV9LQo4Rnp99x/QKgz/sLXzQatLTF1ELzFkfzM4bqISa\nrvYF+30oFTUw2UnRKC4rNV7846NPPM0ksUwjFnTThnKpNUoiCluw+2Kpr7zC0VFs\nbv2Nj1cwFrzoroAylbMtZedVI3SB8gi5kk5rU1zv823iJvxLCbGLLgoOY9ckURst\nuBbtAQz7+7/d3V03SA2N2U1s9ccWsTCT2J912pSYzEGJiB1hinaRz4kedIIRLbTe\nbsjy79SzOhc2tkj85ITxbFtBp1dYF0uq0NfQ9E6WRUHK3QQYLLfhk/ziTsQz7Pbl\nGZet9WMEB1oZ1k3E0UujDYi9pJeXaDLLcJHer1F9GF07n7USSfK6kwj9KR6toHXD\numIekJnz8S/PlOEkue44D/Ov6c/Vt7YgLk/xvYLBjJvVgvYEj+oOt1HR6779kNw9\nQdTQrqM5PFTnY9Kk1Pisahcey6ZHWXZHZS4KPuT3bNPyOcxMEUSIJo3+ueiKUQZA\nhKd+tcQ3NhQppW4zfcdp2bJbTYV8TRiIVySJZjZiAMGQnT5yjVdW7EgNCMuKa7bk\nfjzTNm4U0nRO8LXNbs8U+Pm5AJPR2f3MCSsvc71bJd6Gl4AA4QKCAQEAzyTtuAIf\njFZBMu1xs0tc2pdHoa+zqqiiNEBoPwoW6rfHVgtDw5+H/DDOG4LUdzz5KBmvn9oO\neS6fSJNt0JTvqWVB1AZ0bxXZ4FP76fygC4mNRX1qtf0COhP1NXVQLHMt8y90weV0\nzYgGHA9CI41W79gbnAHWf8vMoFhB7LP3Z8FJKn9IeMlpcPz6TPV58ocShYFR3bvm\nVIukwy5ApXpVkQq93l91ipjwZkj/HRBGN2bcz1WjNz1TokIZB718SiOsvi2NlW+Z\nGKLjSxLXdQxviLUQo640QssAaJ4Xyv3ewjEQjBz3UZdWBBp30fX/hW8NK/vB5LXa\nl1ci266T9OZu1QKCAQEAx6JAFHzgS5lyo1Mc99+Br0nEjHCA0dAmcNjqZZj65Hpt\nVL0hOfPtBUnkcSQRgp9t+8YM5tFXkizFpS539z6gUWNK9S0lHxIKYrclc6vDEuKE\nCVBuSJjLne1drt3RoaOL3YG6FSOOFWy/lH/fV7Av6Gi7flMwUzGbh+S1e9em9CGW\nh0GcKEUxmgDERp0HXU2EEGXczrKFN+q6tN3G/uyKPbeWNkjo7MwJcEmz1Qsk9ybk\n+orlLbF/jypgPS/9cm3pBcXcNEek+DRdRvq7qoIQs6Go1OcXeZNejGrspPqjz0C4\nsu31amA0p0AMuFZifYr1N0kNHeHdCu57aKr104Ky9QKCAQEAtt6yIq11Lo6DVrN6\nmj+hBLVjHqGfqrzfHePyZBzDKIoAJ70gINZ41bI8ctsoOPASQk2S1ztJZcA8DHVj\nEC47+j8TQ1xDdEJFK57ZGbPVkvnnRv62s11elulBo+UiV2uDmFo/6GFqoXxBcIoj\n6IEBzBHsJekVdZL03mWsJYynkOh5cFQYJdIiDQa47jIUa4DFYClPncIhUGhLl6gA\nmFYMrlReVK/PdAEa0iIFXqIcaxKbQ0smIUE50VgrAsNMs6MVAHv0r4VrEe3TXVaP\n8Zx95qF6xBWpu4G9pZ5UAPforWVlZ1y3FkfVPyAiwbA72Y+1gCvs+71z8gGSG4De\ny+iW1QKCAQEAsai35EO5jC3T8ntdtU3H6In6i4z3Z0EZZKX1+1JoPPqi352suxlU\nHrfCv9l8Z8WgKEb5ZlR43VJQ1g6DnpmyLJvzsjtp5Lu2WGFqyATchqrlHDDi5GJu\nGm6KR7uJ+pJEP21af8Nzh6eO2wXtaekWyXqjGOnJgNAN/KLRy5OANZTKlDYUVVY2\nrTnvcnP+gM8iL0Gnfp8qpTeUzq7rkCRLZl9CI69A8rMl1zMQAhF35SdM8Za4G7Dx\ntyPcH7fckoAztvp9XF1B980KEcfDSRuU53d/e3Do2D4JD2d8j9mp/CA5/qp8FB3n\n3cvHRilCXz1RutCdBrHheAAB/YTfXkrbHQKCAQAmOwFgAFzttoJVswM/qQQVYlD/\n9eY8OIoqAkOQS6a5WEx4gQJdSqcrZ2MUxQxHOiQC4diaBnOvASixwsF8sThh4eLT\nNweLx8wH2pIq/XFEwmZWCIwr2LMjg5xsRyb1H65zgeEM7xDHHNsE/hEaZ3cBnxpY\n12N+1cnXY0t/B5O0iSOctR+g2zmm9fMUJwVk1OEU3PXfbpYZbkQp0qwKbOGAHRWG\nRFF5MU3WHoukltHhjMYtDX/hIV6yylLywF3VAOEIXTMW9sCQTDIvJx2MpT6OO5Tb\nU5gh3Nmp9upI6zwmt+FHSyrZtcSeSy7jYIkYOs9elAdI8eKzUKo8JA4pnIVt\n-----END RSA PRIVATE KEY-----\n"
  KUBE_SERVICE_DOMAIN_SUFFIX: ~

  # Password used for the monit API.
  MONIT_PASSWORD: ~

  # The password for the MySQL server admin user.
  MYSQL_ADMIN_PASSWORD: ~

  # The password for the cluster logger health user.
  MYSQL_CLUSTER_HEALTH_PASSWORD: ~

  # The password used to contact the sidecar endpoints via Basic Auth.
  MYSQL_GALERA_HEALTHCHECK_ENDPOINT_PASSWORD: ~

  # An indicator to increment when changing the number of MySQL hosts in the
  # cluster, to properly trigger component restarts.
  MYSQL_HCF_CLUSTER_CONFIG_REVISION: "0"

  # PEM-encoded certificate
  SAML_SERVICEPROVIDER_CERT: ~

  # PEM-encoded key.
  SAML_SERVICEPROVIDER_KEY: ~

  # The password for access to the UAA database.
  UAADB_PASSWORD: ~

  # The password of the admin client - a client named admin with uaa.admin as an
  # authority.
  UAA_ADMIN_CLIENT_SECRET: ~

  # The server's ssl certificate. The default is a self-signed certificate and
  # should always be replaced for production deployments.
  UAA_SERVER_CERT: ~

  # The server's ssl private key. Only passphrase-less keys are supported.
  UAA_SERVER_KEY: ~

sizing:
  HA: false

  # The mysql role contains the following jobs:
  #
  # - global-properties: Dummy BOSH job used to host global parameters that are
  #   required to configure SCF / fissile
  #
  # - patch-properties: Dummy BOSH job used to host parameters that are used in
  #   HCF patches for upstream bugs
  #
  # Also: mysql
  mysql:
    # The mysql role cannot be scaled.
    count: 1
    disk_sizes:
      mysql_data: 20
    memory: 3072
    vcpu_count: 2

  # The secret-generation role contains the following jobs:
  #
  # - generate-secrets: This job will generate the secrets for the cluster
  secret_generation:
    # The secret-generation role cannot be scaled.
    count: 1
    memory: 256
    vcpu_count: 1

  # The uaa role contains the following jobs:
  #
  # - global-properties: Dummy BOSH job used to host global parameters that are
  #   required to configure SCF / fissile
  #
  # - uaa: The UAA is the identity management service for Cloud Foundry. It's
  #   primary role is as an OAuth2 provider, issuing tokens for client
  #   applications to use when they act on behalf of Cloud Foundry users. It can
  #   also authenticate users with their Cloud Foundry credentials, and can act
  #   as an SSO service using those credentials (or others). It has endpoints
  #   for managing user accounts and for registering OAuth2 clients, as well as
  #   various other management functions.
  uaa:
    # The uaa role can scale between 1 and 65535 instances.
    count: 1
    memory: 2048
    vcpu_count: 2

services:
  loadbalanced: false
kube:
  external_ip: "192.168.77.77"
  storage_class:
    persistent: "persistent"
    shared: "shared"
  registry:
    hostname: "staging.registry.howdoi.website"
    username: ""
    password: ""
  organization: "splatform"
  auth: ~
