apiVersion: v1
appVersion: 2.5.0-2.g3959072d
description: A Helm chart for KubeCF
icon: https://raw.githubusercontent.com/cloudfoundry-incubator/kubecf/master/icon/kubecf.png
name: kubecf
version: 2.5.0-2.g3959072d
