dependencies:
- name: eirini
  version: 1.0.2
  repository: http://opensource.suse.com/eirini-release/
  condition: features.eirini.enabled
- name: bits
  version: 1.0.14
  repository: http://opensource.suse.com/bits-service-release/
  condition: features.eirini.enabled
- name: eirini-extensions
  alias: eirinix
  repository: https://opensource.suse.com/eirinix-helm-release/
  version: "0.0.0-9+g6b37279"
  condition: features.eirini.enabled
