---
apiVersion: "v1"
data:
  # The password for access to the configured postgres database.
  service-postgres-pass: {{ required "SERVICE_POSTGRESQL_PASS configuration missing" .Values.env.SERVICE_POSTGRESQL_PASS | b64enc | quote }}

  # The token for sidecar access by the cf-usb role in SCF.
  sidecar-api-key: {{ randAlphaNum 32 | b64enc | quote }}

  # The PEM-encoded SCF CA certificate used to sign the TLS
  # certificate required by the cf client in the setup task to secure
  # the communication with the api endpoint.
  cf-ca-cert: {{ required "CF_CA_CERT configuration missing" .Values.env.CF_CA_CERT | b64enc | quote }}

  # The PEM-encoded UAA CA certificate
  uaa-ca-cert: {{ required "UAA_CA_CERT configuration missing" .Values.env.UAA_CA_CERT | b64enc | quote }}

  # Cluster password
  cf-admin-password: {{ required "CF_ADMIN_PASSWORD configuration missing" .Values.env.CF_ADMIN_PASSWORD | b64enc | quote }}

kind: "Secret"
metadata:
  name: "cf-usb-sidecar-postgres-secret"
  labels:
    skiff-role-name: "cf-usb-sidecar-postgres-secret"
