{{- include "_config.load" $ }}
{{- if .Values.features.embedded_database.enabled }}
---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: var-pxc-root-password
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- list . "database" | include "component.labels" | nindent 4 }}
spec:
  type: password
  secretName: {{ include "kubecf.varSecretName" (list $ "pxc_root_password") }}
---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: var-pxc-password
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- list . "database" | include "component.labels" | nindent 4 }}
spec:
  type: password
  secretName: {{ include "kubecf.varSecretName" (list $ "pxc_password") }}

{{- end }}{{/* .Values.features.embedded_database.enabled */}}
