{{- if .Values.global.rbac.create }}
---
apiVersion: v1
kind: List
items:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      creationTimestamp: null
      name: {{ template "quarks-job.fullname" . }}
    rules:
    - apiGroups:
      - apiextensions.k8s.io
      resources:
      - customresourcedefinitions
      verbs:
      - create
      - get
      - update
  - kind: ClusterRoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: {{ template "quarks-job.fullname" . }}
    roleRef:
      kind: ClusterRole
      name: {{ template "quarks-job.fullname" . }}
      apiGroup: rbac.authorization.k8s.io
    subjects:
    - kind: ServiceAccount
      name: {{ template "quarks-job.serviceAccountName" . }}
      namespace: {{ .Release.Namespace }}
{{- end }}
