{{- if or .Values.serviceAccount.create .Values.global.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "quarks-job.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}

{{- if .Values.global.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "quarks-job.fullname" . }}
roleRef:
  kind: ClusterRole
  name: {{ template "quarks-job.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ template "quarks-job.serviceAccountName" . }}
  namespace: "{{ .Release.Namespace }}"
{{- end }}
