{{- if or .Values.serviceAccount.create .Values.global.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "quarks-job.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}

{{- if .Values.global.rbac.create }}
---
apiVersion: v1
kind: List
items:
  - kind: RoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: {{ template "quarks-job.fullname" . }}
      namespace: {{ .Values.global.operator.watchNamespace }}
    subjects:
    - kind: ServiceAccount
      name: {{ template "quarks-job.serviceAccountName" . }}
      namespace: {{ .Release.Namespace }}
    roleRef:
      kind: Role
      name: {{ template "quarks-job.fullname" . }}
      apiGroup: rbac.authorization.k8s.io

  - kind: ClusterRoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: {{ template "quarks-job.fullname" . }}-cluster
    roleRef:
      kind: ClusterRole
      name: {{ template "quarks-job.fullname" . }}-cluster
      apiGroup: rbac.authorization.k8s.io
    subjects:
    - kind: ServiceAccount
      name: {{ template "quarks-job.serviceAccountName" . }}
      namespace: {{ .Release.Namespace }}
{{- end }}
