{{- if or .Values.serviceAccount.create .Values.global.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "quarks-job.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
