# Default values for cert-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: registry.suse.com/caasp/v4/cert-exporter
  tag: 2.2.0
  pullPolicy: IfNotPresent

imagePullSecrets: []

resources:
  {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# Deploy a DaemonSet to monitors on disk certificates
node:
  enabled: true

# Deploy a Deployment to monitors the addon secret certificates
addon:
  enabled: true
  nodeSelector: {}
  affinity: {}

# Deploy the Deployment(s) to monitors the custom secret certificates
customSecret:
  enabled: false
  # Name of the custom secret to create the Deployment resource.
  # If you have multiple custom secret to monitoring, copy the below
  # section and differs in name
  - name: default
    # Kubernetes namespace to list secrets (optional).
    namespace:
    # Secret globs to include when looking for secret data keys (optional).
    includeKeys: []
    # Secret globs to exclude when looking for secret data keys (optional).
    excludeKeys: []
    # Label selector to find secrets to publish as metrics (optional).
    # Annotation selector to find secrets to publish as metrics (optional).
    # If both labelSelector and annotationSelector configured, the cert-exporter
    # search secrets with AND operation, which means the secrets are the intersects
    # of labelSelector and annotationSelector.
    labelSelector: []
    annotationSelector: []
    nodeSelector: {}
    affinity: {}
