---
resources:
- name: ci
  type: git
  source:
    uri: git@github.com:SUSE/kubernetes-charts-suse-com.git
    private_key: {{github-private-key}}
jobs:
- name: sync
  plan:
  - get: ci
    trigger: true
  - task: sync
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: splatform/concourse-aws-helm
      inputs:
        - name: ci
      params:
        BUCKET: {{s3-helm-charts-bucket}}
        AWS_ACCESS_KEY_ID: {{aws-access-key}}
        AWS_SECRET_ACCESS_KEY: {{aws-secret-key}}
      run:
        path: ci/pipeline/tasks/sync.sh
