---
resources:
- name: ci
  type: git
  source:
    uri: git@github.com:SUSE/kubernetes-charts-suse-com.git
    private_key: {{github-private-key}}

jobs:
- name: sync
  plan:
  - get: ci
  - task: sync
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: dragonchaser/aws-cli
      inputs:
        - name: ci
      params:
        BUCKET: {{s3-helm-charts-bucket}}
      run:
        path: ci/pipeline/tasks/sync.sh
