---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "log-agent-rsyslog.fullname" . }}
  labels:
    helm.sh/chart: {{ include "log-agent-rsyslog.chart" . }}
    app.kubernetes.io/name: {{ include "log-agent-rsyslog.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  rootCA.pem: {{ .Values.server.tls.rootCa | default "none" | indent 4 }}
  client-key.pem: {{ .Values.server.tls.clientKey | default "none" | indent 4 }}
  client.pem: {{ .Values.server.tls.clientCert | default "none" | indent 4 }}

