---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "log-agent-rsyslog.fullname" . }}
  labels:
    helm.sh/chart: {{ include "log-agent-rsyslog.chart" . }}
    app.kubernetes.io/name: {{ include "log-agent-rsyslog.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
