system_domain: example.com
CF_ADMIN_USER: test
env:
  CF_DOMAIN: test
  DOMAIN: test
  SERVICE_LOCATION: test
  SERVICE_POSTGRESQL_HOST: AUTO
  UAA_HOST: test
  CF_ADMIN_PASSWORD: test
  CF_CA_CERT: test
  CLUSTER_ADMIN_PASSWORD: test
  UAA_ADMIN_CLIENT_SECRET: test
  UAA_CA_CERT: test
  DOMAIN: test
secrets:
  CF_ADMIN_PASSWORD: test
  CF_CA_CERT: test
  CLUSTER_ADMIN_PASSWORD: test
  UAA_ADMIN_CLIENT_SECRET: test
  UAA_CA_CERT: test
  BITS_TLS_CRT: test
