#!BuildTag: ceph-csi-cephfs:3.1.1_1.1
---
apiVersion: v1
appVersion: v3.1.1
description: "Container Storage Interface (CSI) driver,
provisioner, snapshotter and attacher for Ceph cephfs"
name: ceph-csi-cephfs
version: 3.1.1-1.1
keywords:
  - ceph
  - cephfs
  - ceph-csi
home: https://github.com/ceph/ceph-csi
sources:
  - https://github.com/ceph/ceph-csi/tree/master/charts/ceph-csi-cephfs
icon: https://raw.githubusercontent.com/ceph/ceph-csi/master/assets/ceph-logo.png
