#!BuildTag: ceph-csi-rbd:3.1.1_1.1
---
apiVersion: v1
appVersion: v3.1.1
description: "Container Storage Interface (CSI) driver,
provisioner, snapshotter, and attacher for Ceph RBD"
name: ceph-csi-rbd
version: 3.1.1_1.1
keywords:
  - ceph
  - rbd
  - ceph-csi
home: https://github.com/ceph/ceph-csi
sources:
  - https://github.com/ceph/ceph-csi/tree/master/charts/ceph-csi-rbd
icon: https://raw.githubusercontent.com/ceph/ceph-csi/master/assets/ceph-logo.png
