bits:
  blobstore:
    serviceName: "singleton-blobstore"
    userName: "blobstore-user"
    secret:
      name: "var-blobstore-admin-users-password"
      passwordPath: "password"

  global:
    images:
      bits_service: registry.suse.com/cap-staging/bits-service:bits-1.0.21-15.1.6.2.298-24.56

  services:
    nodePort: 31666

  secrets:
    BITS_SERVICE_SECRET: secret
    BITS_SERVICE_SIGNING_USER_PASSWORD: notpassword123
    BLOBSTORE_PASSWORD: blobstore

  tls_secret_name: bits-service-ssl
