eirinix:
  dns-aliases:
    image: ghcr.io/cfcontainerizationbot/eirini-dns-aliases
    image_tag: 0.0.0-32.g585bc34d
    pullPolicy: IfNotPresent

  loggregator-bridge:
    replicaCount: 1
    image:
      repository: splatform
      tag: v0.0.0-0.g7da9e04
      pullPolicy: IfNotPresent
    resources: {}
    nodeSelector: {}
    affinity: {}
    tolerations: []

    endpoint: doppler:8082
    secrets:
      ca: var-loggregator-ca          # Name of secret containing loggregator CA
      cert: var-loggregator-tls-agent # Name of secret containing cert info

  persi:
    replicaCount: 1
    image:
      repository: splatform
      tag: v0.0.0-73.g8201eba
      pullPolicy: IfNotPresent
    resources: {}
    nodeSelector: {}
    affinity: {}
    tolerations: []

  persi-broker:
    replicaCount: 1
    image:
      repository: splatform
      tag: v0.0.0-g0c241e7
      pullPolicy: IfNotPresent
    setup-image:
      repository: splatform
      tag: v0.0.0-g9d08cc7
      pullPolicy: IfNotPresent
    resources: {}
    nodeSelector: {}
    affinity: {}
    tolerations: []

    # XXX This part lives in `chart/values.yaml` until we have the facility to merge mixin `values.yaml` files
    # service-plans:
    # - id: default
    #   name: "default"
    #   description: "Existing default storage class"
    #   kube_storage_class: ~
    #   free: true
    #   default_size: "1Gi"
    # description: Eirini persistence broker
    # long_description: Eirini persistence broker to provide Kubernete storage classes
    # provider_display_name: Eirini broker
    # documentation_url: https://github.com/SUSE/eirini-persi-broker
    # support_url: https://github.com/SUSE/eirini-persi-broker/issues
    # display_name: Eirini broker
    # icon_image: Eirini broker
    # secrets:
    #   auth-password: ~ # Password is randomly generated if not given

  ssh:
    replicaCount: 1
    image:
      repository: splatform
      tag: v0.0.0-0.g09b53c0
      pullPolicy: IfNotPresent
    resources: {}
    nodeSelector: {}
    affinity: {}
    tolerations: []

    cc-api-url: https://api:9024
    uaa-token-url: https://uaa:8443/oauth/token

  ssh-proxy:
    replicaCount: 1
    image:
      repository: splatform
      tag: v0.0.0-0.g09b53c0
      pullPolicy: IfNotPresent
    setup-image:
      repository: splatform
      tag: v0.0.0-g9d08cc7
      pullPolicy: IfNotPresent
    resources: {}
    nodeSelector: {}
    affinity: {}
    tolerations: []

    secrets:
      host-keys: var-diego-ssh-proxy-host-key
      uaa-client-proxy-secret: var-uaa-clients-ssh-proxy-secret
      uaa-ca: var-uaa-ca
      cc-api-ca: var-cc-public-tls

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  rbac:
    enable: true
    webhook:
      cluster_role:
        rules: []

  service_account:
    name: "eirinix"
