
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fdbdoclayer
{{- if .Values.console.service -}}
{{- if .Values.console.service.annotations }}
  annotations:
{{ toYaml .Values.console.service.annotations | indent 4 }}
{{- end }}
{{- end }}
  labels:
    app.kubernetes.io/name: "stratos"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/component: "{{ .Release.Name }}-fdbdoclayer"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
{{- if .Values.console.service -}}
{{- if .Values.console.service.extraLabels }}
{{ toYaml .Values.console.service.extraLabels | indent 4 }}
{{- end }}
{{- end }}
spec:
  type: ClusterIP
  ports:
  - port: 27016
    targetPort: 27016
    protocol: TCP
    name: fdbdoclayer
  selector:
    app.kubernetes.io/name: "stratos"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/component: "stratos-chartstore"
