apiVersion: v1
appVersion: 2.1.0-rc3
description: A Helm chart for cf-operator, the k8s operator for deploying BOSH releases
home: https://github.com/cloudfoundry-incubator/cf-operator
icon: https://cloudfoundry-incubator.github.io/quarks-helm/logo.png
keywords:
- cloudfoundry
- bosh
- quarks
- deployment
maintainers:
- email: project-quarks@googlegroups.com
  name: project-quarks
name: cf-operator
sources:
- https://github.com/cloudfoundry-incubator/cf-operator
- https://github.com/cloudfoundry-incubator/quarks-job
- https://github.com/cloudfoundry-incubator/quarks-secret
- https://github.com/cloudfoundry-incubator/quarks-utils
- https://build.opensuse.org/package/show/Cloud:Platform:quarks/quarks-operator-base
version: 6.1.17-rc3+0.gec409fd7
