apiVersion: v1
appVersion: 2.0.0-rc2
description: A Helm chart for cf-operator, the k8s operator for deploying BOSH releases
home: https://github.com/cloudfoundry-incubator/cf-operator
icon: https://cloudfoundry-incubator.github.io/quarks-helm/logo.png
keywords:
- cloudfoundry
- bosh
- quarks
- deployment
maintainers:
- email: project-quarks@googlegroups.com
  name: project-quarks
name: cf-operator
sources:
- https://github.com/cloudfoundry-incubator/cf-operator
- https://github.com/cloudfoundry-incubator/quarks-job
- https://github.com/cfcontainerizationbot/cf-operator-base
version: 2.0.0-rc2
