---
dependencies:
- name: quarks-job
  version: 1.0.206
  repository: https://cloudfoundry-incubator.github.io/quarks-helm
- name: quarks-secret
  version: 1.0.744
  repository: https://cloudfoundry-incubator.github.io/quarks-helm
