---
dependencies:
- name: quarks-job
  version: 1.0.218
  repository: https://cloudfoundry-incubator.github.io/quarks-helm
- name: quarks-secret
  version: 1.0.758
  repository: https://cloudfoundry-incubator.github.io/quarks-helm
- name: quarks-statefulset
  version: 1.0.1319
  repository: https://cloudfoundry-incubator.github.io/quarks-helm
