---
dependencies:
- name: quarks-job
  version: 1.0.198
  repository: https://cloudfoundry-incubator.github.io/quarks-helm
- name: quarks-secret
  version: 1.0.738
  repository: https://cloudfoundry-incubator.github.io/quarks-helm
