{{ if .Values.deployServiceCatalog }}
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ClusterServiceBroker
metadata:
  name: minibroker
  labels:
    {{- include "minibroker.labels" . | nindent 4 }}
spec:
  url: {{ printf "http://%s.%s.svc:%d" (include "minibroker.fullname" .) .Release.Namespace (int .Values.broker.service.port) | quote }}
{{ end }}
