{{ if .Values.deployServiceCatalog }}
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ClusterServiceBroker
metadata:
  name: minibroker
  {{- template "minibroker.labels" . }}
spec:
  url: http://{{ template "minibroker.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
{{ end }}
