{{- if .Values.rbac.create }}
{{- if .Values.rbac.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.serviceAccount.name | quote }}
  labels:
    {{- include "minibroker.labels" . | nindent 4 }}
    {{- range $k, $v := .Values.rbac.serviceAccount.labels }}
    {{ $k | quote }}: {{ $v | quote }}
    {{- end }}
  annotations:
    {{- range $k, $v := .Values.rbac.serviceAccount.annotations }}
    {{ $k | quote }}: {{ $v | quote }}
    {{- end }}
{{- end }}{{/* if .Values.rbac.serviceAccount.create */}}

{{- if .Values.rbac.namespaced.enabled }}
{{/* Checks for when the rbac is namespaced. */}}
{{- if .Values.defaultNamespace }}
{{- if not has .Values.defaultNamespace .Values.rbac.namespaced.whitelist }}
{{- fail "The default namespace is not whitelisted in rbac.namespaced.whitelist" }}
{{- end }}{{/* if not has .Values.defaultNamespace .Values.rbac.namespaced.whitelist */}}
{{- end }}{{/* if .Values.defaultNamespace */}}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ printf "minibroker-%s" .Release.Name | quote }}
  labels:
    {{- include "minibroker.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
  - namespaces
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "minibroker-%s" .Release.Name | quote }}
  labels:
    {{- include "minibroker.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ printf "minibroker-%s" .Release.Name | quote }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.rbac.serviceAccount.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: minibroker
  labels:
    {{- include "minibroker.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: minibroker
  labels:
    {{- include "minibroker.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: minibroker
subjects:
- kind: ServiceAccount
  name: {{ .Values.rbac.serviceAccount.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
{{- range $namespace := .Values.rbac.namespaced.whitelist }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: minibroker
  namespace: {{ $namespace | quote }}
  labels:
    {{- include "minibroker.labels" . | nindent 4 }}
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: minibroker
  namespace: {{ $namespace | quote }}
  labels:
    {{- include "minibroker.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: minibroker
subjects:
- kind: ServiceAccount
  name: {{ $.Values.rbac.serviceAccount.name | quote }}
  namespace: {{ $.Release.Namespace | quote }}
{{- end }}{{/* range $namespace := .Values.rbac.namespaced.whitelist */}}
{{- else }}{{/* if .Values.rbac.namespaced.enabled */}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ printf "minibroker-%s" .Release.Name | quote }}
  labels:
    {{- include "minibroker.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
  - configmaps
  - endpoints
  - limitranges
  - persistentvolumeclaims
  - pods
  - podtemplates
  - replicationcontrollers
  - resourcequotas
  - secrets
  - serviceaccounts
  - services
  verbs: ["*"]
- apiGroups: [""]
  resources:
  - namespaces
  verbs:
  - get
  - list
- apiGroups:
  - apps
  - autoscaling
  - batch
  - networking.k8s.io
  resources: ["*"]
  verbs: ["*"]
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs: ["*"]
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: minibroker
  labels:
    {{- include "minibroker.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ printf "minibroker-%s" .Release.Name | quote }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.rbac.serviceAccount.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
{{- end }}{{/* if .Values.rbac.namespaced.enabled */}}

{{- end }}{{/* if .Values.rbac.create */}}
