kind: Service
apiVersion: v1
metadata:
  name: {{ template "minibroker.fullname" . }}
  {{- template "minibroker.labels" . }}
spec:
  selector:
    app: {{ template "minibroker.fullname" . }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
