{{- if .Values.global.rbac.create }}
---
apiVersion: v1
kind: List
items:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      creationTimestamp: null
      name: {{ template "cf-operator.fullname" . }}
    rules:
    - apiGroups:
      - certificates.k8s.io
      resources:
      - certificatesigningrequests
      verbs:
      - create
      - get
      - list
      - update
      - watch
    - apiGroups:
      - certificates.k8s.io
      resources:
      - certificatesigningrequests/approval
      verbs:
      - create
      - update
    - apiGroups:
      - apiextensions.k8s.io
      resources:
      - customresourcedefinitions
      verbs:
      - create
      - get
      - update
    - apiGroups:
      - ""
      resources:
      - namespaces
      verbs:
      - get
      - list
      - update
      - watch
    - apiGroups:
      - admissionregistration.k8s.io
      resources:
      - validatingwebhookconfigurations
      - mutatingwebhookconfigurations
      verbs:
      - create
      - delete
      - update
  - kind: ClusterRoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: {{ template "cf-operator.fullname" . }}
      namespace: {{ .Release.Namespace }}
    roleRef:
      kind: ClusterRole
      name: {{ template "cf-operator.fullname" . }}
      apiGroup: rbac.authorization.k8s.io
    subjects:
    - kind: ServiceAccount
      name: {{ template "cf-operator.serviceAccountName" . }}
      namespace: {{ .Release.Namespace }}
{{- end }}
