{{- if .Values.global.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: {{ template "cf-operator.fullname" . }}-cluster
rules:
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - approve
  - create
  - delete
  - get
  - list
  - update
  - watch

- apiGroups:
  - certificates.k8s.io
  resources:
  - signers
  resourceNames:
  - kubernetes.io/legacy-unknown
  verbs:
  - approve

- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
  - delete
  - list
  - update
  - watch

- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests/approval
  verbs:
  - create
  - update

- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - get
  - update

- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - update
  - watch

- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  - mutatingwebhookconfigurations
  verbs:
  - create
  - delete
  - update

# for monitored namespaces

- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update

- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - update
  - watch

- apiGroups:
  - ""
  resources:
  - services
  - configmaps
  verbs:
  - create
  - get
  - list
  - update
  - watch

- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch

- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - get
  - list
  - update
  - watch

- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
  - list

- apiGroups:
  - quarks.cloudfoundry.org
  resources:
  - quarksjobs
  verbs:
  - create
  - get
  - list
  - update
  - watch

- apiGroups:
  - quarks.cloudfoundry.org
  resources:
  - boshdeployments
  - quarksstatefulsets
  - quarkssecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

- apiGroups:
  - quarks.cloudfoundry.org
  resources:
  - boshdeployments/status
  verbs:
  - create
  - patch
  - update
{{- end }}
