{{- if .Values.global.rbac.create }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "cf-operator.fullname" . }}
  namespace: {{ .Values.global.operator.watchNamespace }}
subjects:
- kind: ServiceAccount
  name: {{ template "cf-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "cf-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "cf-operator.role-name" . }}
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ template "cf-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "cf-operator.role-name" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
