{{- include "_config.load" $ }}
{{- if .Values.features.eirini.enabled }}
---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: {{ .Values.bits.tls_secret_name }}
spec:
  request:
    certificate:
      alternativeNames:
      - 127.0.0.1
      commonName: bits
      isCA: false
      signerType: cluster
  secretName: {{ .Values.bits.tls_secret_name }}
  type: certificate
{{- end }}
