{{- $root := . }}
---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: BOSHDeployment
metadata:
  name: {{ include "kubecf.deployment-name" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/name: {{ include "kubecf.fullname" . }}
    app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
    helm.sh/chart: {{ include "kubecf.chart" . }}
spec:
  manifest:
    name: cf-deployment
    type: configmap
{{- if gt (len .Values.credentials) 0}}
  vars:
{{- $creds := dict }}
{{- range $name, $value := .Values.credentials }}
  {{- $parts := splitList "." $name }}
  {{- $_ := set $creds (first $parts) nil }}
{{- end }}
{{- range $name, $value := $creds }}
  - name: {{ $name | quote }}
    secret: {{ printf "cred-%s" ($name | replace "_" "-" | replace "." "-") | quote }}
{{- end }}
{{- else }}
  vars: []
{{- end }}
  ops:
{{- range $path, $_ := .Files.Glob "assets/operations/job_moving/*" }}
  - name: {{ include "kubecf.ops-name" (dict "ReleaseName" $root.Release.Name "Path" $path) }}
    type: configmap
{{- end }}
{{- if .Values.features.suse_buildpacks.enabled }}
  - name: {{ include "kubecf.ops-name" (dict "Path" "assets/operations/buildpacks/set_suse_buildpacks.yaml") }}
    type: configmap
{{- end }}
{{- if eq .Values.features.blobstore.provider "s3" }}
  - name: {{ include "kubecf.ops-name" (dict "Path" "assets/use-external-blobstore.yml") }}
    type: configmap
  - name: {{ include "kubecf.ops-name" (dict "Path" "assets/use-s3-blobstore.yml") }}
    type: configmap
{{- if .Values.features.eirini.enabled }}
  - name: {{ include "kubecf.ops-name" (dict "Path" "assets/configure-bits-service-s3.yml") }}
    type: configmap
{{- end }}
{{- end }}
{{- range $path, $bytes := .Files.Glob "assets/operations/instance_groups/*" }}
  - name: {{ include "kubecf.ops-name" (dict "Path" $path) }}
    type: configmap
{{- end }}
{{- range $path, $bytes := .Files.Glob "assets/operations/temporary/*" }}
  - name: {{ include "kubecf.ops-name" (dict "Path" $path) }}
    type: configmap
{{- end }}
  - name: {{ include "kubecf.ops-name" (dict "Path" "assets/operations/sizing.yaml") }}
    type: configmap
  - name: {{ include "kubecf.ops-name" (dict "Path" "assets/operations/azs.yaml") }}
    type: configmap
{{- range $path, $bytes := .Files.Glob "assets/operations/*" }}
  - name: {{ include "kubecf.ops-name" (dict "Path" $path) }}
    type: configmap
{{- end }}
{{- range $_, $ops := .Values.operations.custom }}
  - name: {{ $ops | quote }}
    type: configmap
{{- end }}
{{- if gt (len .Values.operations.inline) 0 }}
  - name: user-provided-inline-operations
    type: configmap
{{- end }}
  - name: user-provided-properties
    type: configmap
