{{- include "_config.load" $ }}
{{- if .Values.features.eirini.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "eirini"
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      name: "eirini"
  template:
    metadata:
      labels:
        name: "eirini"
      annotations:
        quarks.cloudfoundry.org/restart-on-update: "true"
    spec:
      dnsPolicy: "ClusterFirst"
      serviceAccountName: "opi"
      volumes:
        - name: config-map-volume
          configMap:
            name: "eirini"
            items:
            - key: opi.yml
              path: opi.yml
        - name: cf-secrets
          projected:
            sources:
            - secret:
                name: "{{ .Values.eirini.opi.tls.opiCapiClient.secretName }}"
                items:
                - key: "{{ .Values.eirini.opi.tls.opiCapiClient.certPath }}"
                  path: cc.crt
                - key: "{{ .Values.eirini.opi.tls.opiCapiClient.keyPath }}"
                  path: cc.key
            - secret:
                name: "{{ .Values.eirini.opi.tls.capi.secretName }}"
                items:
                - key: "{{ .Values.eirini.opi.tls.capi.caPath }}"
                  path: cc.ca
            - secret:
                name: "{{ .Values.eirini.opi.tls.opiServer.secretName }}"
                items:
                - key: "{{ .Values.eirini.opi.tls.opiServer.certPath }}"
                  path: eirini-server.crt
                - key: "{{ .Values.eirini.opi.tls.opiServer.keyPath }}"
                  path: eirini-server.key
            - secret:
                name: "{{ .Values.eirini.opi.tls.eirini.secretName }}"
                items:
                - key: "{{ .Values.eirini.opi.tls.eirini.caPath }}"
                  path: eirini.ca
      securityContext:
        runAsNonRoot: true
      containers:
      - name: opi
        {{- if .Values.eirini.opi.image }}
        image: {{ .Values.eirini.opi.image }}:{{ .Values.eirini.opi.image_tag }}
        {{- else }}
        image: eirini/opi@{{ .Files.Get "assets/versions/opi" }}
        {{- end }}
        imagePullPolicy: Always
        volumeMounts:
        - name: config-map-volume
          mountPath: /workspace/jobs/opi/config
        - name: cf-secrets
          mountPath: /workspace/jobs/opi/secrets
        ports:
        - containerPort: 8085
          name: https
        resources:
          requests:
            cpu: 20m
            memory: 20Mi
{{- end }}
