{{- include "_config.load" $ }}
{{- if .Values.features.eirini.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: eirini-registry-credentials
  namespace: {{ .Values.eirini.opi.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\": {\"127.0.0.1:31666\": {\"auth\": \"%s\"}}}" (printf "admin:%s" .Values.bits.secrets.BITS_SERVICE_SIGNING_USER_PASSWORD | b64enc) | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    quarks.cloudfoundry.org/secret-kind: generated
  annotations:
    quarks.cloudfoundry.org/secret-copy-of: {{ .Release.Namespace }}/var-eirini-tls-client-cert
  name: var-eirini-tls-client-cert
  namespace: {{ .Values.eirini.opi.namespace | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    quarks.cloudfoundry.org/secret-kind: generated
  annotations:
    quarks.cloudfoundry.org/secret-copy-of: {{ .Release.Namespace }}/var-cc-bridge-cc-uploader
  name: var-cc-bridge-cc-uploader
  namespace: {{ .Values.eirini.opi.namespace | quote }}
{{- end }}
