{{- $_ := include "_config.load" $ }}
{{- if .Values.features.eirini.enabled }}
{{ $component := "loggregator-bridge" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ mustMerge (dict "name" $component) . | include "eirinix.component-name" }}
  labels:
    app.kubernetes.io/component: {{ $component }}
{{ include "eirinix.labels" . | indent 4 }}
spec:
  replicas: {{ index .Values.eirinix $component "replicaCount" }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "eirinix.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: {{ $component }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "eirinix.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: {{ $component }}
      annotations:
        quarks.cloudfoundry.org/restart-on-update: "true"
    spec:
    {{- with .Values.eirinix.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ .Values.eirinix.service_account.name | quote }}
      containers:
        - name: {{ $component }}
          {{- with index .Values.eirinix $component "image" }}
          image: {{ printf "%s/eirinix-%s:%s" .repository $component .tag | quote }}
          imagePullPolicy: {{ .pullPolicy }}
          {{- end }}
          env:
          - name: EIRINI_LOGGREGATOR_BRIDGE_LOGLEVEL
            value: DEBUG
          - name: LOGGREGATOR_CERT_PATH
            value: /run/secrets/loggregator-cert/certificate
          - name: LOGGREGATOR_KEY_PATH
            value: /run/secrets/loggregator-cert/private_key
          - name: LOGGREGATOR_CA_PATH
            value: /run/secrets/loggregator-ca/certificate
          - name: NAMESPACE
            value: {{ .Values.eirini.opi.namespace }}
          - name: LOGGREGATOR_ENDPOINT
            value: {{ index .Values.eirinix "loggregator-bridge" "endpoint" }}
          - name: OPERATOR_SERVICE_NAME
            value: eirinix-{{ $component }}
          - name: OPERATOR_WEBHOOK_NAMESPACE
            value: {{ .Release.Namespace | quote }}
          - name: OPERATOR_WEBHOOK_HOST
            value: "0.0.0.0"
          - name: OPERATOR_WEBHOOK_PORT
            value: "8443"
          - name: OPI_IMAGE_CONTAINS
            value: "127.0.0.1:{{ .Values.bits.services.nodePort }}"
          volumeMounts:
          - name: loggregator-ca
            mountPath: /run/secrets/loggregator-ca
          - name: loggregator-cert
            mountPath: /run/secrets/loggregator-cert
          resources:
            {{- index .Values.eirinix $component "resources" | toYaml | nindent 12 }}
      volumes:
      - name: config
        emptyDir: {}
      - name: loggregator-ca
        secret:
          secretName: {{ index .Values.eirinix $component "secrets" "ca" }}
          items:
          - key: certificate
            path: certificate
      - name: loggregator-cert
        secret:
          secretName: {{ index .Values.eirinix $component "secrets" "cert" }}
          items:
          - key: certificate
            path: certificate
          - key: private_key
            path: private_key
    {{- with index .Values.eirinix $component }}
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .affinity | nindent 8 }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}
    {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: eirinix-{{ $component }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "eirinix.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: {{ $component }}
  ports:
  - protocol: TCP
    name: https
    port: 8443
{{- end }}
