{{- include "_config.load" $ }}
{{- if .Values.features.eirini.enabled }}
{{- if .Values.eirini.opi.metrics.enable }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eirini-metrics
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eirini-metrics
  namespace: {{ .Values.eirini.opi.namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eirini-metrics
  namespace: {{ .Values.eirini.opi.namespace }}
roleRef:
  kind: Role
  name: eirini-metrics
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: eirini-metrics
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eirini-metrics-psp
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - eirini-metrics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eirini-metrics-psp
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: eirini-metrics-psp
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: eirini-metrics
  namespace: {{ .Release.Namespace }}
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: eirini-metrics
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'runtime/default'
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  volumes:
    - 'configMap'
    - 'secret'
    - 'projected'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'MustRunAsNonRoot'
  seLinux:
    # This policy assumes the nodes are using AppArmor rather than SELinux.
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: eirini-nodes-policy
rules:
- apiGroups:
  - ""
  resources:
  - "nodes"
  - "nodes/proxy"
  verbs:
  - "get"
  - "list"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: eirini-metrics
subjects:
- kind: ServiceAccount
  name: eirini-metrics
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: eirini-nodes-policy
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
