{{- include "_config.load" $ }}
{{- if or .Values.features.multiple_cluster_mode.control_plane.enabled .Values.features.multiple_cluster_mode.cell_segment.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: multiple-cluster-mode-operations
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: operations
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/name: {{ include "kubecf.fullname" . }}
    app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
    helm.sh/chart: {{ include "kubecf.chart" . }}
data:
  ops: |-
{{- if .Values.features.multiple_cluster_mode.control_plane.enabled }}
    # To deploy the control plane
    - type: remove
      path: /instance_groups/name=diego-cell
{{- end }}{{/* if .Values.features.multiple_cluster_mode.control_plane.enabled */}}
{{- if .Values.features.multiple_cluster_mode.cell_segment.enabled }}
    # To deploy a cell
    - type: remove
      path: /instance_groups/name=api
    - type: remove
      path: /instance_groups/name=auctioneer
    - type: remove
      path: /instance_groups/name=cc-worker
    - type: remove
      path: /instance_groups/name=diego-api
    - type: remove
      path: /instance_groups/name=doppler
    - type: remove
      path: /instance_groups/name=log-api
    - type: remove
      path: /instance_groups/name=log-cache
    - type: remove
      path: /instance_groups/name=nats
    - type: remove
      path: /instance_groups/name=router
    - type: remove
      path: /instance_groups/name=scheduler
    - type: remove
      path: /instance_groups/name=singleton-blobstore
    - type: remove
      path: /instance_groups/name=uaa
    - type: remove
      path: /instance_groups/name=rotate-cc-database-key
    - type: remove
      path: /instance_groups/name=smoke-tests?
    - type: remove
      path: /instance_groups/name=acceptance-tests?
    - type: remove
      path: /instance_groups/name=sync-integration-tests?
    - type: remove
      path: /variables/name=silk_controller?
    - type: remove
      path: /instance_groups/name=diego-cell/jobs/name=bosh-dns-adapter?
    - type: replace
      path: /instance_groups/name=diego-cell/jobs/name=route_emitter/consumes?
      value:
        nats: {from: nats}
        nats-tls: {from: nats-tls}
        {{- if .Values.features.routing_api.enabled }}
        routing_api: {from: routing_api}
        {{- end }}{{/* if .Values.features.routing_api.enabled */}}
    - type: replace
      path: /instance_groups/name=diego-cell/jobs/name=loggr-udp-forwarder/consumes?
      value:
        cloud_controller: {from: cloud_controller}
    - type: replace
      path: /instance_groups/name=diego-cell/jobs/name=garden-cni/consumes?
      value:
        cloud_controller_container_networking_info: {from: cloud_controller_container_networking_info}
    - type: replace
      path: /instance_groups/name=diego-cell/jobs/name=vxlan-policy-agent/consumes?
      value:
        cf_network: {from: cf_network}
    - type: replace
      path: /addons/name=prom_scraper/jobs/name=prom_scraper/consumes?
      value:
        loggregator: {from: loggregator}
    - type: replace
      path: /addons/name=loggregator_agent/jobs/name=loggregator_agent/consumes?
      value:
        doppler: {from: doppler}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.features.multiple_cluster_mode.provider_link_service.nats.secret_name }} 
  annotations:
    quarks.cloudfoundry.org/deployment-name: "{{ include "kubecf.deployment-name" . }}"
    quarks.cloudfoundry.org/provides: '{"name":"nats","type":"nats"}'
stringData:
  link: {{- toYaml .Values.features.multiple_cluster_mode.provider_link_service.nats.link | nindent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.features.multiple_cluster_mode.provider_link_service.nats_tls.secret_name }} 
  annotations:
    quarks.cloudfoundry.org/deployment-name: "{{ include "kubecf.deployment-name" . }}"
    quarks.cloudfoundry.org/provides: '{"name":"nats-tls","type":"nats-tls"}'
stringData:
  link: {{- toYaml .Values.features.multiple_cluster_mode.provider_link_service.nats_tls.link | nindent 4 }} 
{{- if .Values.features.routing_api.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.features.multiple_cluster_mode.provider_link_service.routing_api.secret_name }} 
  annotations:
    quarks.cloudfoundry.org/deployment-name: "{{ include "kubecf.deployment-name" . }}"
    quarks.cloudfoundry.org/provides: '{"name":"routing_api","type":"routing_api"}'
stringData:
  link: {{- toYaml .Values.features.multiple_cluster_mode.provider_link_service.routing_api.link | nindent 4 }} 
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.features.multiple_cluster_mode.provider_link_service.doppler.secret_name }} 
  annotations:
    quarks.cloudfoundry.org/deployment-name: "{{ include "kubecf.deployment-name" . }}"
    quarks.cloudfoundry.org/provides: '{"name":"doppler","type":"doppler"}'
stringData:
  link: {{- toYaml .Values.features.multiple_cluster_mode.provider_link_service.doppler.link | nindent 4 }} 
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.features.multiple_cluster_mode.provider_link_service.loggregator.secret_name }} 
  annotations:
    quarks.cloudfoundry.org/deployment-name: "{{ include "kubecf.deployment-name" . }}"
    quarks.cloudfoundry.org/provides: '{"name":"loggregator","type":"loggregator"}'
stringData:
  link: {{- toYaml .Values.features.multiple_cluster_mode.provider_link_service.loggregator.link | nindent 4 }} 
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.features.multiple_cluster_mode.provider_link_service.cloud_controller.secret_name }}
  annotations:
    quarks.cloudfoundry.org/deployment-name: "{{ include "kubecf.deployment-name" . }}"
    quarks.cloudfoundry.org/provides: '{"name":"cloud_controller","type":"cloud_controller"}'
stringData:
  link: {{- toYaml .Values.features.multiple_cluster_mode.provider_link_service.cloud_controller.link | nindent 4 }} 
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.features.multiple_cluster_mode.provider_link_service.cf_network.secret_name }} 
  annotations:
    quarks.cloudfoundry.org/deployment-name: "{{ include "kubecf.deployment-name" . }}"
    quarks.cloudfoundry.org/provides: '{"name":"cf_network","type":"cf_network"}'
stringData:
  link:  {{- toYaml .Values.features.multiple_cluster_mode.provider_link_service.cf_network.link | nindent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.features.multiple_cluster_mode.provider_link_service.cloud_controller_container_networking_info.secret_name }} 
  annotations:
    quarks.cloudfoundry.org/deployment-name: "{{ include "kubecf.deployment-name" . }}"
    quarks.cloudfoundry.org/provides: '{"name":"cloud_controller_container_networking_info","type":"cloud_controller_container_networking_info"}'
stringData:
  link: {{- toYaml .Values.features.multiple_cluster_mode.provider_link_service.cloud_controller_container_networking_info.link | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    quarks.cloudfoundry.org/deployment-name: "{{ include "kubecf.deployment-name" . }}"
    quarks.cloudfoundry.org/link-provider-name: nats
  name: {{ .Values.features.multiple_cluster_mode.provider_link_service.nats.service_name }} 
spec:
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    quarks.cloudfoundry.org/deployment-name: "{{ include "kubecf.deployment-name" . }}"
    quarks.cloudfoundry.org/link-provider-name: nats-tls
  name: {{ .Values.features.multiple_cluster_mode.provider_link_service.nats_tls.service_name }}
spec:
  clusterIP: None
  type: ClusterIP
{{- if .Values.features.routing_api.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    quarks.cloudfoundry.org/deployment-name: "{{ include "kubecf.deployment-name" . }}"
    quarks.cloudfoundry.org/link-provider-name: routing_api
  name: {{ .Values.features.multiple_cluster_mode.provider_link_service.routing_api.service_name }}
spec:
  clusterIP: None
  type: ClusterIP
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    quarks.cloudfoundry.org/deployment-name: "{{ include "kubecf.deployment-name" . }}"
    quarks.cloudfoundry.org/link-provider-name: doppler
  name: {{ .Values.features.multiple_cluster_mode.provider_link_service.doppler.service_name }}
spec:
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    quarks.cloudfoundry.org/deployment-name: "{{ include "kubecf.deployment-name" . }}"
    quarks.cloudfoundry.org/link-provider-name: loggregator
  name: {{ .Values.features.multiple_cluster_mode.provider_link_service.loggregator.service_name }}
spec:
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    quarks.cloudfoundry.org/deployment-name: "{{ include "kubecf.deployment-name" . }}"
    quarks.cloudfoundry.org/link-provider-name: cloud_controller
  name: {{ .Values.features.multiple_cluster_mode.provider_link_service.cloud_controller.service_name }}
spec:
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    quarks.cloudfoundry.org/deployment-name: "{{ include "kubecf.deployment-name" . }}"
    quarks.cloudfoundry.org/link-provider-name: cloud_controller_container_networking_info
  name: {{ .Values.features.multiple_cluster_mode.provider_link_service.cloud_controller_container_networking_info.service_name }} 
spec:
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    quarks.cloudfoundry.org/deployment-name: "{{ include "kubecf.deployment-name" . }}"
    quarks.cloudfoundry.org/link-provider-name: cf_network
  name: {{ .Values.features.multiple_cluster_mode.provider_link_service.cf_network.service_name }} 
spec:
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.features.multiple_cluster_mode.provider_link_service.nats.service_name }} 
subsets:
- addresses:
  {{- range .Values.features.multiple_cluster_mode.provider_link_service.nats.addresses }}
    - ip: {{ .ip }}
  {{- end }}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.features.multiple_cluster_mode.provider_link_service.nats_tls.service_name }}
subsets:
- addresses:
  {{- range .Values.features.multiple_cluster_mode.provider_link_service.nats_tls.addresses }}
    - ip: {{ .ip }}
  {{- end }}
{{- if .Values.features.routing_api.enabled }}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.features.multiple_cluster_mode.provider_link_service.routing_api.service_name }}
subsets:
- addresses:
  {{- range .Values.features.multiple_cluster_mode.provider_link_service.routing_api.addresses }}
    - ip: {{ .ip }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.features.multiple_cluster_mode.provider_link_service.doppler.service_name }}
subsets:
- addresses:
  {{- range .Values.features.multiple_cluster_mode.provider_link_service.doppler.addresses }}
    - ip: {{ .ip }}
  {{- end }}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.features.multiple_cluster_mode.provider_link_service.loggregator.service_name }}
subsets:
- addresses:
  {{- range .Values.features.multiple_cluster_mode.provider_link_service.loggregator.addresses }}
    - ip: {{ .ip }}
  {{- end }}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.features.multiple_cluster_mode.provider_link_service.cloud_controller.service_name }} 
subsets:
- addresses:
  {{- range .Values.features.multiple_cluster_mode.provider_link_service.cloud_controller.addresses }}
    - ip: {{ .ip }}
  {{- end }}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.features.multiple_cluster_mode.provider_link_service.cloud_controller_container_networking_info.service_name }} 
subsets:
- addresses:
  {{- range .Values.features.multiple_cluster_mode.provider_link_service.cloud_controller_container_networking_info.addresses }}
    - ip: {{ .ip }}
  {{- end }}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.features.multiple_cluster_mode.provider_link_service.cf_network.service_name }} 
subsets:
- addresses:
  {{- range .Values.features.multiple_cluster_mode.provider_link_service.cf_network.addresses }}
    - ip: {{ .ip }}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.features.multiple_cluster_mode.control_plane_workers.uaa.name }}
spec:
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.features.multiple_cluster_mode.control_plane_workers.uaa.name }}
subsets:
- addresses:
  {{- range .Values.features.multiple_cluster_mode.control_plane_workers.uaa.addresses }}
    - ip: {{ .ip }}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.features.multiple_cluster_mode.control_plane_workers.diego_api.name }}
spec:
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.features.multiple_cluster_mode.control_plane_workers.diego_api.name }}
subsets:
- addresses:
  {{- range .Values.features.multiple_cluster_mode.control_plane_workers.diego_api.addresses }}
    - ip: {{ .ip }}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.features.multiple_cluster_mode.control_plane_workers.api.name }} 
spec:
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.features.multiple_cluster_mode.control_plane_workers.api.name }} 
subsets:
- addresses:
  {{- range .Values.features.multiple_cluster_mode.control_plane_workers.api.addresses }}
    - ip: {{ .ip }}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.features.multiple_cluster_mode.control_plane_workers.singleton_blobstore.name }} 
spec:
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.features.multiple_cluster_mode.control_plane_workers.singleton_blobstore.name }}
subsets:
- addresses:
  {{- range .Values.features.multiple_cluster_mode.control_plane_workers.singleton_blobstore.addresses }}
    - ip: {{ .ip }}
  {{- end }}
{{- end }}{{/* if .Values.features.multiple_cluster_mode.cell_segment.enabled */}}
{{- end }}{{/* if or .Values.features.multiple_cluster_mode.control_plane.enabled .Values.features.multiple_cluster_mode.cell_segment.enabled */}}
