{{- include "_config.load" $ }}
{{- if .Values.features.eirini.enabled }}
{{- if .Values.eirini.opi.deny_app_ingress }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-app-ingress
  namespace: {{ .Values.eirini.opi.namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ .Release.Namespace }}
      podSelector:
        matchLabels:
          app.kubernetes.io/component: router
    - namespaceSelector:
        matchLabels:
          name: {{ .Release.Namespace }}
      podSelector:
        matchLabels:
          app.kubernetes.io/component: adapter
{{- end }}
{{- end }}
