{{- include "_config.load" $ }}
# This template creates a ConfigMap for each ops file under assets/operations.
{{- define "kubecf.ops" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubecf.ops-name" (dict "Path" .Path) }}
  namespace: {{ .Root.Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: operations
    app.kubernetes.io/instance: {{ .Root.Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Root.Release.Service | quote }}
    app.kubernetes.io/name: {{ include "kubecf.fullname" .Root }}
    app.kubernetes.io/version: {{ default .Root.Chart.Version .Root.Chart.AppVersion | quote }}
    helm.sh/chart: {{ include "kubecf.chart" .Root }}
data:
  ops: |-
    {{- tpl (.Root.Files.Get .Path) .Root | nindent 4 }}
{{- end }}

{{- $root := . }}

{{- range $path, $_ := .Files.Glob "assets/operations/job_moving/*" }}
{{ include "kubecf.ops" (dict "Root" $root "Path" $path) }}
{{- end }}

{{- if eq .Values.features.blobstore.provider "s3" }}
{{ include "kubecf.ops" (dict "Root" $root "Path" "assets/use-external-blobstore.yml") }}
{{ include "kubecf.ops" (dict "Root" $root "Path" "assets/use-s3-blobstore.yml") }}
{{- if .Values.features.eirini.enabled }}
{{ include "kubecf.ops" (dict "Root" $root "Path" "assets/configure-bits-service-s3.yml") }}
{{- end }}
{{- end }}

{{- range $path, $_ := .Files.Glob "assets/operations/instance_groups/*" }}
{{ include "kubecf.ops" (dict "Root" $root "Path" $path) }}
{{- end }}

{{- range $path, $_ := .Files.Glob "assets/operations/sizing/*" }}
{{ include "kubecf.ops" (dict "Root" $root "Path" $path) }}
{{- end }}

{{- range $path, $_ := .Files.Glob "assets/operations/*" }}
{{ include "kubecf.ops" (dict "Root" $root "Path" $path) }}
{{- end }}

{{- if gt (len .Values.operations.inline) 0 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-provided-inline-operations
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: operations
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/name: {{ include "kubecf.fullname" . }}
    app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
    helm.sh/chart: {{ include "kubecf.chart" . }}
data:
  ops: |-
    {{- .Values.operations.inline | toYaml | nindent 4 }}
{{- end }}
