{{- include "_config.load" $ }}
{{- if .Values.features.eirini.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opi
  namespace: {{ .Release.Namespace }}
{{- if .Values.kube.image_pull_secrets }}
imagePullSecrets:
{{- include "kubecf.imagePullSecrets" $ }}
{{- end }}
{{- end }}
