{{- include "_config.load" $ }}
{{- if and .Values.testing.sync_integration_tests.enabled (not .Values.features.eirini.enabled) }}
# SITS only makes sense when using Diego, for this reason, we only enable it if Eirini is not
# enabled.

# Service account, roles, and cluster role for the sync integration tests.
# Raw kube objects going into the chart.

# Service account "tests-sits" is used by the instance group "sync-integration-tests"
---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  name: tests-sits
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: "{{ .Release.Name }}-tests-sits"
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/name: {{ include "kubecf.fullname" . }}
    app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
    helm.sh/chart: {{ include "kubecf.chart" . }}

# Role "test-role-sits" only used by account "tests-sits"
---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "Role"
metadata:
  name: test-role-sits
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: "{{ .Release.Name }}-test-role-sits"
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/name: {{ include "kubecf.fullname" . }}
    app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
    helm.sh/chart: {{ include "kubecf.chart" . }}
rules:
- apiGroups:
  - ""
  resources:
  - "services"
  verbs:
  - "create"
  - "get"
  - "delete"
  - "list"
  - "patch"
- apiGroups:
  - "extensions"
  resourceNames:
  - "default"
  resources:
  - "podsecuritypolicies"
  verbs:
  - "use"
- apiGroups:
  - "extensions"
  resources:
  - "replicasets"
  verbs:
  - "create"
  - "get"
  - "list"
  - "delete"
  - "update"
- apiGroups:
  - "apps"
  resources:
  - "statefulsets"
  verbs:
  - "create"
  - "get"
  - "update"
  - "delete"
  - "list"
  - "patch"
- apiGroups:
  - ""
  resources:
  - "pods"
  verbs:
  - "create"
  - "get"
  - "list"
  - "delete"
  - "update"
  - "patch"
- apiGroups:
  - ""
  resources:
  - "pods/exec"
  verbs:
  - "create"
  - "delete"
- apiGroups:
  - ""
  resources:
  - "pods/log"
  verbs:
  - "create"
  - "delete"
  - "get"
  - "list"
- apiGroups:
  - ""
  resources:
  - "secrets"
  verbs:
  - "create"
  - "get"
  - "delete"
  - "list"

# Role binding for service account "tests-sits" and role "test-role-sits"
---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "RoleBinding"
metadata:
  name: tests-sits-test-role-sits-binding
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: "{{ .Release.Name }}-tests-sits-test-role-sits-binding"
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/name: {{ include "kubecf.fullname" . }}
    app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
    helm.sh/chart: {{ include "kubecf.chart" . }}
subjects:
- kind: "ServiceAccount"
  name: tests-sits
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: "Role"
  name: test-role-sits

# Cluster role "tests-sits-cluster-role" only used by account "tests-sits"
---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "ClusterRole"
metadata:
  name: "{{ .Release.Namespace }}-tests-sits-cluster-role"
  labels:
    app.kubernetes.io/component: "{{ .Release.Namespace }}-{{ .Release.Name }}-tests-sits-cluster-role"
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/name: {{ include "kubecf.fullname" . }}
    app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
    helm.sh/chart: {{ include "kubecf.chart" . }}
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  verbs:
  - "create"
  - "get"
  - "delete"
- apiGroups:
  - ""
  resources:
  - "pods"
  - "pods/log"
  - "namespaces"
  verbs:
  - "get"
  - "list"
  - "watch"
- apiGroups:
  - ""
  resources:
  - "pods/portforward"
  verbs:
  - "create"
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "clusterrolebindings"
  verbs:
  - "delete"
- apiGroups:
  - ""
  resources:
  - "persistentvolumes"
  - "persistentvolumeclaims"
  verbs:
  - "get"
  - "list"
- apiGroups:
  - "storage.k8s.io"
  resources:
  - "storageclasses"
  verbs:
  - "get"
  - "list"
- apiGroups:
  - "batch"
  resources:
  - "jobs"
  verbs:
  - "get"
  - "list"

# Cluster role binding for service account "tests-sits" and cluster role "tests-sits-cluster-role"
---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "ClusterRoleBinding"
metadata:
  name: "{{ .Release.Namespace }}-tests-sits-cluster-binding"
  labels:
    app.kubernetes.io/component: "{{ .Release.Namespace }}-{{ .Release.Name }}-tests-sits-cluster-binding"
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/name: {{ include "kubecf.fullname" . }}
    app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
    helm.sh/chart: {{ include "kubecf.chart" . }}
subjects:
- kind: "ServiceAccount"
  name: tests-sits
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: "ClusterRole"
  apiGroup: "rbac.authorization.k8s.io"
  name: "{{ .Release.Namespace }}-tests-sits-cluster-role"

{{- end }}
