applyCRD: true
fullnameOverride: ""
global:
  contextTimeout: 30
  image:
    pullPolicy: IfNotPresent
  meltdownDuration: 60
  meltdownRequeueAfter: 30
  monitoredID: null
  rbac:
    create: true
  singleNamespace:
    create: true
    name: staging
image:
  org: registry.suse.com/cap
  repository: quarks-job
  tag: v1.0.206
logLevel: debug
maxWorkers: 1
nameOverride: ""
persistOutputClusterRole:
  create: true
  name: qjob-persist-output
serviceAccount:
  create: true
  name: null
singleNamespace:
  createAccount: true
  createNamespace: true
