{{- $secret := include "harbor.core" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: Opaque
data:
{{- if .Release.IsUpgrade }}
  {{- $prevSecret := (lookup "v1" "Secret" .Release.Namespace $secret) }}
  {{- if .Values.secretKey }}
  secretKey: {{ .Values.secretKey | b64enc | quote }}
  {{- else if $prevSecret }}
  secretKey: {{ $prevSecret.data.secretKey }}
  {{- else }}
  secretKey: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  {{- if .Values.secret }}
  secret: {{ .Values.secret | b64enc | quote }}
  {{- else if $prevSecret }}
  secret: {{ $prevSecret.data.secret }}
  {{- else }}
  secret: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  {{- if .Values.harborAdminPassword }}
  HARBOR_ADMIN_PASSWORD: {{ .Values.harborAdminPassword | b64enc | quote }}
  {{- else if $prevSecret }}
  HARBOR_ADMIN_PASSWORD: {{ $prevSecret.data.HARBOR_ADMIN_PASSWORD }}
  {{- else }}
  HARBOR_ADMIN_PASSWORD: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  {{- if .Values.core.xsrfKey }}
  CSRF_KEY: {{ .Values.core.xsrfKey | b64enc | quote }}
  {{- else if $prevSecret }}
  CSRF_KEY: {{ $prevSecret.data.CSRF_KEY }}
  {{- else }}
  CSRF_KEY: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- else }}
  secretKey: {{ .Values.core.secretKey | default (randAlphaNum 16) | b64enc | quote }}
  secret: {{ .Values.core.secret | default (randAlphaNum 16) | b64enc | quote }}
  HARBOR_ADMIN_PASSWORD: {{ .Values.harborAdminPassword | default (randAlphaNum 16) | b64enc | quote }}
  CSRF_KEY: {{ .Values.core.xsrfKey | default (randAlphaNum 32) | b64enc | quote }}
{{- end }}
{{- if not .Values.core.secretName }}
  {{- $cert := genSelfSignedCert "harbor" nil nil 365 }}
  {{- $certCtx := (merge (dict "ca" nil "cert" $cert "secret" $secret "rotateCert" .Values.core.rotateCert ) .) }}
{{ include "harbor.getGenCertOrLoadFromSecret" $certCtx | indent 2 }}
{{- end }}
  REGISTRY_CREDENTIAL_PASSWORD: {{ .Values.registry.credentials.password | b64enc | quote }}
