---
{{- if eq (printf "%s" .Values.kube.auth) "rbac" }}
apiVersion: "rbac.authorization.k8s.io/v1beta1"
kind: "RoleBinding"
metadata:
  name: "default-configgin-role-binding"
  labels:
    app.kubernetes.io/component: "default-configgin-role-binding"
    skiff-role-name: "default-configgin-role-binding"
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" | quote }}
    app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name (.Chart.Version | replace "+" "_") | quote }}
subjects:
- kind: "ServiceAccount"
  name: "default"
roleRef:
  kind: "Role"
  name: "configgin-role"
  apiGroup: "rbac.authorization.k8s.io"
{{- end }}
---
{{- if and (eq (printf "%s" .Values.kube.auth) "rbac") .Values.kube.psp.nonprivileged }}
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "ClusterRoleBinding"
metadata:
  name: "{{ .Release.Namespace }}-default-binding-psp"
  labels:
    app.kubernetes.io/component: "{{ .Release.Namespace }}-default-binding-psp"
    skiff-role-name: "{{ .Release.Namespace }}-default-binding-psp"
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" | quote }}
    app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name (.Chart.Version | replace "+" "_") | quote }}
subjects:
- kind: "ServiceAccount"
  name: "default"
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: "ClusterRole"
  name: "{{ .Release.Namespace }}-psp-role-nonprivileged"
  apiGroup: "rbac.authorization.k8s.io"
{{- end }}
