apiVersion: v1
appVersion: 1.3.1
description: A Helm chart for velero
home: https://github.com/vmware-tanzu/velero
icon: https://cdn-images-1.medium.com/max/1600/1*-9mb3AKnKdcL_QD3CMnthQ.png
maintainers:
- email: ashisham@vmware.com
  name: ashish-amarnath
- email: carlisiac@vmware.com
  name: carlisia
- email: ctadeu@gmail.com
  name: cpanato
- email: brubakern@vmware.com
  name: nrb
- email: krisss@vmware.com
  name: skriss
name: velero
sources:
- https://github.com/vmware-tanzu/velero
tillerVersion: '>=2.10.0'
version: 2.12.1
