{{ $component := "loggregator-bridge" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ mustMerge (dict "name" $component) . | include "eirinix.component-name" }}
  labels:
    app.kubernetes.io/component: {{ $component }}
{{ include "eirinix.labels" . | indent 4 }}
spec:
  replicas: {{ index .Values $component "replicaCount" }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "eirinix.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: {{ $component }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "eirinix.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: {{ $component }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ .Values.service_account.name | quote }}
      containers:
        - name: {{ $component }}
          {{- with index .Values $component "image" }}
          image: {{ printf "%s/eirinix-%s:%s" .repository $component .tag | quote }}
          imagePullPolicy: {{ .pullPolicy }}
          {{- end }}
          env:
          - name: EIRINI_LOGGREGATOR_BRIDGE_LOGLEVEL
            value: DEBUG
          - name: LOGGREGATOR_CERT_PATH
            value: /run/secrets/loggregator-cert/certificate
          - name: LOGGREGATOR_KEY_PATH
            value: /run/secrets/loggregator-cert/private_key
          - name: LOGGREGATOR_CA_PATH
            value: /run/secrets/loggregator-ca/certificate
          - name: NAMESPACE
            value: {{ .Values.namespace }}
          - name: LOGGREGATOR_ENDPOINT
            value: {{ index .Values "loggregator-bridge" "endpoint" }}
          volumeMounts:
          - name: loggregator-ca
            mountPath: /run/secrets/loggregator-ca
          - name: loggregator-cert
            mountPath: /run/secrets/loggregator-cert
          resources:
            {{- index .Values $component "resources" | toYaml | nindent 12 }}
      volumes:
      - name: config
        emptyDir: {}
      - name: loggregator-ca
        secret:
          secretName: {{ index .Values $component "secrets" "ca" }}
          items:
          - key: certificate
            path: certificate
      - name: loggregator-cert
        secret:
          secretName: {{ index .Values $component "secrets" "cert" }}
          items:
          - key: certificate
            path: certificate
          - key: private_key
            path: private_key
    {{- with index .Values $component }}
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .affinity | nindent 8 }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}
    {{- end }}
