---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-encryption-key-volume"
  labels:
    app:  "{{ .Release.Name }}"
  annotations:
  {{- if .Values.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.storageClass | quote }}
  {{- else if .Values.kube.storage_class.persistent }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.kube.storage_class.persistent | quote }}
  {{- else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi
---
{{- if and .Values.mariadb.persistence.enabled (not .Values.mariadb.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: console-mariadb
  labels:
    app:  "{{ .Release.Name }}"
  annotations:
  {{- if .Values.mariadb.persistence.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.mariadb.persistence.storageClass | quote }}
  {{- else if .Values.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.storageClass | quote }}
  {{- else if .Values.kube.storage_class.persistent }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.kube.storage_class.persistent | quote }}
  {{- else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}
spec:
  accessModes:
    - {{ .Values.mariadb.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.mariadb.persistence.size | quote }}
{{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-upgrade-volume"
  labels:
    app:  "{{ .Release.Name }}"
  annotations:
  {{- if .Values.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.storageClass | quote }}
  {{- else if .Values.kube.storage_class.persistent }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.kube.storage_class.persistent | quote }}
  {{- else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi
