---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "{{ .Release.Name }}-secret"
  labels:
    app.kubernetes.io/name: "stratos"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/component: "console-secret"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  client: {{ default "cf" .Values.uaa.consoleClient | b64enc | quote }}
  clientSecret: {{  default "" .Values.uaa.consoleClientSecret | b64enc | quote }}
  localAdminPassword: {{ default "" .Values.console.localAdminPassword | b64enc | quote }}
  smtpUser: {{ default "" .Values.env.SMTP_USER | b64enc | quote }}
  smtpPassword: {{ default "" .Values.env.SMTP_PASSWORD | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-db-secret"
  labels:
    app.kubernetes.io/name: "stratos"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/component: "console-db-secret"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: Opaque
data:
  {{- if or .Values.mariadb.rootPassword .Values.mariadb.mariadbRootPassword }}
  rootPassword: {{ (default .Values.mariadb.rootPassword .Values.mariadb.mariadbRootPassword) | b64enc | quote }}
  {{- else }}
  rootPassword: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- if or .Values.mariadb.userPassword .Values.mariadb.mariadbPassword }}
  password: {{ (default .Values.mariadb.userPassword .Values.mariadb.mariadbPassword) | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  user: {{ default .Values.mariadb.user .Values.mariadb.mariadbUser | b64enc | quote }}
  database: {{ default .Values.mariadb.database .Values.mariadb.mariadbDatabase | b64enc | quote }}
  {{- if .Values.console.sessionStoreSecret }}
  sessionStoreSecret: {{ .Values.console.sessionStoreSecret | b64enc | quote }}
  {{- else }}
  sessionStoreSecret: {{ randAlphaNum 64 | b64enc | quote }}
  {{- end }}
{{- if and .Values.kube.registry.username .Values.kube.registry.password }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockercfg
metadata:
  name: {{ .Values.dockerRegistrySecret }}
  labels:
    app.kubernetes.io/name: "stratos"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/component: "console-dockerreg-secret"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  .dockercfg: {{ template "imagePullSecret" . }}
{{- end}}
