---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "{{ .Release.Name }}-secret"
  labels:
    app: "{{ .Release.Name }}"
data:
  stolon: {{ .Values.dbPassword | b64enc }}
  db-password: {{  .Values.mariadb.mariadbPassword | b64enc }}
---
{{- if .Values.mariadb.usePassword }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-mariadb-secret"
  labels:
    app: "{{ .Release.Name }}"
type: Opaque
data:
  {{- if .Values.mariadb.mariadbRootPassword }}
  mariadb-root-password: {{ .Values.mariadb.mariadbRootPassword | b64enc | quote }}
  {{- else }}
  mariadb-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.mariadb.mariadbPassword }}
  mariadb-password: {{ .Values.mariadb.mariadbPassword | b64enc | quote }}
  {{- else }}
  mariadb-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
{{- end}}
{{- if and .Values.kube.registry.username .Values.kube.registry.password }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockercfg
metadata:
  name: {{ .Values.dockerRegistrySecret }}
  labels:
    app: "{{ .Release.Name }}"
data:
  .dockercfg: {{ template "imagePullSecret" . }}
{{- end}}
