---
apiVersion: "v1"
data:
  .dockercfg: {{ printf "{%q:{%q:%q,%q:%q,%q:%q}}" .Values.kube.registry.hostname "username" (default "" .Values.kube.registry.username) "password" (default "" .Values.kube.registry.password) "auth" (printf "%s:%s" .Values.kube.registry.username .Values.kube.registry.password | b64enc) | b64enc }}
kind: "Secret"
metadata:
  name: "registry-credentials"
  labels:
    skiff-role-name: "registry-credentials"
type: "kubernetes.io/dockercfg"
