---
# The mysql-proxy role contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF / fissile
#
# - patch-properties: Dummy BOSH job used to host parameters that are used in
#   patches for upstream bugs
#
# Also: proxy

{{- if gt (int .Values.sizing.mysql_proxy.count) 3 }}
_maxReplicas: {{ fail "mysql_proxy cannot have more than 3 instances" }}
{{- end }}

{{- if lt (int .Values.sizing.mysql_proxy.count) 1 }}
_minReplicas: {{ fail "mysql_proxy must have at least 1 instances" }}
{{- end }}

apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "mysql-proxy"
  labels:
    skiff-role-name: "mysql-proxy"
spec:
  replicas: {{ .Values.sizing.mysql_proxy.count }}
  selector:
    matchLabels:
      skiff-role-name: "mysql-proxy"
  template:
    metadata:
      name: "mysql-proxy"
      labels:
        skiff-role-name: "mysql-proxy"
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_SERVICE_DOMAIN_SUFFIX"
          value: {{ .Values.env.KUBE_SERVICE_DOMAIN_SUFFIX | quote }}
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        - name: "MYSQL_PROXY_ADMIN_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "mysql-proxy-admin-password"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        - name: "SCF_LOG_HOST"
          value: {{ .Values.env.SCF_LOG_HOST | quote }}
        - name: "SCF_LOG_PORT"
          value: {{ .Values.env.SCF_LOG_PORT | quote }}
        - name: "SCF_LOG_PROTOCOL"
          value: {{ required "SCF_LOG_PROTOCOL configuration missing" .Values.env.SCF_LOG_PROTOCOL | quote }}
        image: "{{ .Values.kube.registry.hostname }}/{{ .Values.kube.organization }}/uaa-mysql-proxy:ec0c88d694f88ed38feccaf077f0d81ec51c824a"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "mysql-proxy"
        ports:
        - containerPort: 3306
          name: "mysql-proxy"
          protocol: "TCP"
        - containerPort: 80
          name: "api"
          protocol: "TCP"
        - containerPort: 1936
          name: "healthcheck"
          protocol: "TCP"
        readinessProbe:
          failureThreshold: 0
          httpGet:
            path: "/"
            port: 1936
            scheme: "HTTP"
          initialDelaySeconds: 0
          periodSeconds: 0
          successThreshold: 0
          timeoutSeconds: 0
        resources:
          requests:
            {{- if and .Values.sizing.memory.requests .Values.sizing.mysql_proxy.memory.request }}
            memory: "{{ int .Values.sizing.mysql_proxy.memory.request }}Mi"
            {{- end }}

            {{- if and .Values.sizing.cpu.requests .Values.sizing.mysql_proxy.cpu.request }}
            cpu: "{{ int .Values.sizing.mysql_proxy.cpu.request }}m"
            {{- end }}

          limits:
            {{- if and .Values.sizing.memory.limits .Values.sizing.mysql_proxy.memory.limit }}
            memory: "{{ int .Values.sizing.mysql_proxy.memory.limit }}Mi"
            {{- end }}

            {{- if and .Values.sizing.cpu.limits .Values.sizing.mysql_proxy.cpu.limit }}
            cpu: "{{ int .Values.sizing.mysql_proxy.cpu.limit }}m"
            {{- end }}

        securityContext: ~
        volumeMounts: ~
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 600
---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "mysql-proxy"
  spec:
    ports:
    - name: "mysql-proxy"
      port: 3306
      protocol: "TCP"
      targetPort: "mysql-proxy"
    - name: "api"
      port: 80
      protocol: "TCP"
      targetPort: "api"
    - name: "healthcheck"
      port: 1936
      protocol: "TCP"
      targetPort: "healthcheck"
    selector:
      skiff-role-name: "mysql-proxy"
    type: {{ if .Values.services.loadbalanced }} LoadBalancer {{ else }} ClusterIP {{ end }}
kind: "List"
