---
# The secret-generation role contains the following jobs:
#
# - generate-secrets: This job will generate the secrets for the cluster
apiVersion: {{ if or (gt (int .Capabilities.KubeVersion.Major) 1) (and (eq (int .Capabilities.KubeVersion.Major) 1) (ge (int .Capabilities.KubeVersion.Minor) 6)) -}} batch/v1 {{- else -}} extensions/v1beta1 {{- end }}
kind: "Job"
metadata:
  name: "secret-generation-{{ .Release.Revision }}"
spec:
  template:
    metadata:
      name: "secret-generation"
      labels:
        skiff-role-name: "secret-generation"
    spec:
      containers:
      - env:
        - name: "DOMAIN"
          value: {{ required "DOMAIN configuration missing" .Values.env.DOMAIN | quote }}
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_SERVICE_DOMAIN_SUFFIX"
          value: {{ .Values.env.KUBE_SERVICE_DOMAIN_SUFFIX | quote }}
        - name: "KUBE_SIZING_UAA_COUNT"
          value: {{ .Values.sizing.uaa.count | quote }}
        - name: "RELEASE_REVISION"
          value: {{ .Release.Revision | quote }}
        image: "{{ .Values.kube.registry.hostname }}/{{ .Values.kube.organization }}/uaa-secret-generation:16c68a7a30c61bd25de8dca1b8ffccd7d8d580ab"
        livenessProbe: ~
        name: "secret-generation"
        ports: ~
        readinessProbe: ~
        resources: ~
        securityContext: ~
        volumeMounts: ~
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "OnFailure"
      {{- if eq (printf "%s" .Values.kube.auth) "rbac" }}
      serviceAccountName: "secret-generator"
      {{- end }}
