---
# The secret-generation role contains the following jobs:
#
# - generate-secrets: This job will generate the secrets for the cluster
apiVersion: {{ if or (gt (int .Capabilities.KubeVersion.Major) 1) (and (eq (int .Capabilities.KubeVersion.Major) 1) (ge (int .Capabilities.KubeVersion.Minor) 6)) -}} batch/v1 {{- else -}} extensions/v1beta1 {{- end }}
kind: "Job"
metadata:
  name: "secret-generation-{{ .Release.Revision }}"
spec:
  template:
    metadata:
      name: "secret-generation"
      labels:
        skiff-role-name: "secret-generation"
    spec:
      containers:
      - env:
        - name: "DOMAIN"
          value: {{ required "DOMAIN configuration missing" .Values.env.DOMAIN | quote }}
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_SERVICE_DOMAIN_SUFFIX"
          value: {{ .Values.env.KUBE_SERVICE_DOMAIN_SUFFIX | quote }}
        - name: "RELEASE_REVISION"
          value: {{ .Release.Revision | quote }}
        image: "{{ .Values.kube.registry.hostname }}/{{ .Values.kube.organization }}/uaa-secret-generation:5a128561261c09f3d9986b34fc27ab03fac1a7bb"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "secret-generation"
        ports: ~
        readinessProbe: ~
        resources:
          {{- if .Values.sizing.memory.requests }}
          requests:
            memory: "{{ int .Values.sizing.secret_generation.memory }}Mi"
          {{- end }}

          {{- if .Values.sizing.memory.limits }}
          limits:
            memory: "{{ (mul (int .Values.sizing.memory.limit_factor) (int .Values.sizing.secret_generation.memory)) }}Mi"
          {{- end }}

        securityContext: ~
        volumeMounts: ~
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "OnFailure"
      {{- if eq (printf "%s" .Values.kube.auth) "rbac" }}
      serviceAccountName: "secret-generator"
      {{- end }}
      terminationGracePeriodSeconds: 600
