---
apiVersion: "v1"
data:
  # The password of the admin client - a client named admin with uaa.admin as an
  # authority.
  # This value is immutable and must not be changed once set.
  uaa-admin-client-secret: {{ required "secrets.UAA_ADMIN_CLIENT_SECRET has not been set" .Values.secrets.UAA_ADMIN_CLIENT_SECRET | b64enc | quote }}

  # PEM-encoded CA certificate used to sign the TLS certificate used by all
  # components to secure their communications.
  # This value uses a generated default.
  internal-ca-cert: {{ default "" .Values.secrets.INTERNAL_CA_CERT | b64enc | quote }}

  # PEM-encoded CA key.
  # This value uses a generated default.
  internal-ca-key: {{ default "" .Values.secrets.INTERNAL_CA_KEY | b64enc | quote }}

  # PEM-encoded JWT certificate.
  # This value uses a generated default.
  jwt-signing-cert: {{ default "" .Values.secrets.JWT_SIGNING_CERT | b64enc | quote }}

  # PEM-encoded JWT signing key.
  # This value uses a generated default.
  jwt-signing-key: {{ default "" .Values.secrets.JWT_SIGNING_KEY | b64enc | quote }}

  # PEM-encoded certificate
  # This value uses a generated default.
  saml-serviceprovider-cert: {{ default "" .Values.secrets.SAML_SERVICEPROVIDER_CERT | b64enc | quote }}

  # PEM-encoded key.
  # This value uses a generated default.
  saml-serviceprovider-key: {{ default "" .Values.secrets.SAML_SERVICEPROVIDER_KEY | b64enc | quote }}

  # The server's ssl certificate. The default is a self-signed certificate and
  # should always be replaced for production deployments.
  # This value uses a generated default.
  uaa-server-cert: {{ default "" .Values.secrets.UAA_SERVER_CERT | b64enc | quote }}

  # The server's ssl private key. Only passphrase-less keys are supported.
  # This value uses a generated default.
  uaa-server-key: {{ default "" .Values.secrets.UAA_SERVER_KEY | b64enc | quote }}

kind: "Secret"
metadata:
  name: "secrets"
  labels:
    skiff-role-name: "secrets"
