---
# The uaa role contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF / fissile
#
# - uaa: The UAA is the identity management service for Cloud Foundry. It's
#   primary role is as an OAuth2 provider, issuing tokens for client
#   applications to use when they act on behalf of Cloud Foundry users. It can
#   also authenticate users with their Cloud Foundry credentials, and can act as
#   an SSO service using those credentials (or others). It has endpoints for
#   managing user accounts and for registering OAuth2 clients, as well as
#   various other management functions.

{{- if gt (int .Values.sizing.uaa.count) 65535 }}
_maxReplicas: {{ fail "uaa cannot have more than 65535 instances" }}
{{- end }}

{{- if lt (int .Values.sizing.uaa.count) 1 }}
_minReplicas: {{ fail "uaa must have at least 1 instances" }}
{{- end }}

apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "uaa"
  labels:
    skiff-role-name: "uaa"
spec:
  replicas: {{ .Values.sizing.uaa.count }}
  selector:
    matchLabels:
      skiff-role-name: "uaa"
  template:
    metadata:
      name: "uaa"
      labels:
        skiff-role-name: "uaa"
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
    spec:
      containers:
      - env:
        - name: "DOMAIN"
          value: {{ required "DOMAIN configuration missing" .Values.env.DOMAIN | quote }}

        {{- if not .Values.secrets.INTERNAL_CA_CERT }}
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.INTERNAL_CA_CERT }}
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.INTERNAL_CA_KEY }}
        - name: "INTERNAL_CA_KEY"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-key"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.INTERNAL_CA_KEY }}
        - name: "INTERNAL_CA_KEY"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-key"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.JWT_SIGNING_CERT }}
        - name: "JWT_SIGNING_CERT"
          valueFrom:
            secretKeyRef:
              key: "jwt-signing-cert"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.JWT_SIGNING_CERT }}
        - name: "JWT_SIGNING_CERT"
          valueFrom:
            secretKeyRef:
              key: "jwt-signing-cert"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.JWT_SIGNING_KEY }}
        - name: "JWT_SIGNING_KEY"
          valueFrom:
            secretKeyRef:
              key: "jwt-signing-key"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.JWT_SIGNING_KEY }}
        - name: "JWT_SIGNING_KEY"
          valueFrom:
            secretKeyRef:
              key: "jwt-signing-key"
              name: "secrets"
        {{- end }}

        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_SERVICE_DOMAIN_SUFFIX"
          value: {{ .Values.env.KUBE_SERVICE_DOMAIN_SUFFIX | quote }}
        - name: "LOG_LEVEL"
          value: {{ required "LOG_LEVEL configuration missing" .Values.env.LOG_LEVEL | quote }}
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"

        {{- if not .Values.secrets.SAML_SERVICEPROVIDER_CERT }}
        - name: "SAML_SERVICEPROVIDER_CERT"
          valueFrom:
            secretKeyRef:
              key: "saml-serviceprovider-cert"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.SAML_SERVICEPROVIDER_CERT }}
        - name: "SAML_SERVICEPROVIDER_CERT"
          valueFrom:
            secretKeyRef:
              key: "saml-serviceprovider-cert"
              name: "secrets"
        {{- end }}

        {{- if .Values.secrets.SAML_SERVICEPROVIDER_KEY }}
        - name: "SAML_SERVICEPROVIDER_KEY"
          valueFrom:
            secretKeyRef:
              key: "saml-serviceprovider-key"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.SAML_SERVICEPROVIDER_KEY }}
        - name: "SAML_SERVICEPROVIDER_KEY"
          valueFrom:
            secretKeyRef:
              key: "saml-serviceprovider-key"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        - name: "SCF_LOG_HOST"
          value: {{ .Values.env.SCF_LOG_HOST | quote }}
        - name: "SCF_LOG_PORT"
          value: {{ .Values.env.SCF_LOG_PORT | quote }}
        - name: "SCF_LOG_PROTOCOL"
          value: {{ required "SCF_LOG_PROTOCOL configuration missing" .Values.env.SCF_LOG_PROTOCOL | quote }}
        - name: "UAADB_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "uaadb-password"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        - name: "UAA_ADMIN_CLIENT_SECRET"
          valueFrom:
            secretKeyRef:
              key: "uaa-admin-client-secret"
              name: "secrets"

        {{- if not .Values.secrets.UAA_SERVER_CERT }}
        - name: "UAA_SERVER_CERT"
          valueFrom:
            secretKeyRef:
              key: "uaa-server-cert"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.UAA_SERVER_CERT }}
        - name: "UAA_SERVER_CERT"
          valueFrom:
            secretKeyRef:
              key: "uaa-server-cert"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.UAA_SERVER_KEY }}
        - name: "UAA_SERVER_KEY"
          valueFrom:
            secretKeyRef:
              key: "uaa-server-key"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.UAA_SERVER_KEY }}
        - name: "UAA_SERVER_KEY"
          valueFrom:
            secretKeyRef:
              key: "uaa-server-key"
              name: "secrets"
        {{- end }}

        image: "{{ .Values.kube.registry.hostname }}/{{ .Values.kube.organization }}/uaa-uaa:9d1859928fcda5fa73ca0e68a182e1784595c2c6"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "uaa"
        ports:
        - containerPort: 8080
          name: "uaa"
          protocol: "TCP"
        - containerPort: 8443
          name: "uaa-ssl"
          protocol: "TCP"
        readinessProbe:
          failureThreshold: 0
          httpGet:
            httpHeaders:
            - name: "Host"
              value: "uaa"
            - name: "Accept"
              value: "application/json"
            path: "/info"
            port: 8443
            scheme: "HTTPS"
          initialDelaySeconds: 0
          periodSeconds: 0
          successThreshold: 0
          timeoutSeconds: 0
        resources:
          requests:
            {{- if and .Values.sizing.memory.requests .Values.sizing.uaa.memory.request }}
            memory: "{{ int .Values.sizing.uaa.memory.request }}Mi"
            {{- end }}

            {{- if and .Values.sizing.cpu.requests .Values.sizing.uaa.cpu.request }}
            cpu: "{{ int .Values.sizing.uaa.cpu.request }}m"
            {{- end }}

          limits:
            {{- if and .Values.sizing.memory.limits .Values.sizing.uaa.memory.limit }}
            memory: "{{ int .Values.sizing.uaa.memory.limit }}Mi"
            {{- end }}

            {{- if and .Values.sizing.cpu.limits .Values.sizing.uaa.cpu.limit }}
            cpu: "{{ int .Values.sizing.uaa.cpu.limit }}m"
            {{- end }}

        securityContext: ~
        volumeMounts: ~
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 600
---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "uaa"
  spec:
    ports:
    - name: "uaa"
      port: 8080
      protocol: "TCP"
      targetPort: "uaa"
    - name: "uaa-ssl"
      port: 2793
      protocol: "TCP"
      targetPort: "uaa-ssl"
    selector:
      skiff-role-name: "uaa"
    type: {{ if .Values.services.loadbalanced }} LoadBalancer {{ else }} ClusterIP {{ end }}
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "uaa-public"
  spec:
    externalIPs: {{ .Values.kube.external_ips | toJson }}
    ports:
    - name: "uaa-ssl"
      port: 2793
      protocol: "TCP"
      targetPort: "uaa-ssl"
    selector:
      skiff-role-name: "uaa"
    type: {{ if .Values.services.loadbalanced }} LoadBalancer {{ else }} ClusterIP {{ end }}
kind: "List"
