---
env:
  CF_ADMIN_PASSWORD: ~
  CF_ADMIN_USER: ~
  CF_CA_CERT: ~
  CF_DOMAIN: ~
  SERVICE_LOCATION: ~
  SERVICE_MYSQL_HOST: "mysql"
  SERVICE_MYSQL_PASS: "cf-usb-sidecar-mysql-admin-password"
  SERVICE_MYSQL_PORT: 3306
  SERVICE_MYSQL_USER: "root"
  SERVICE_TYPE: "mysql"
  UAA_CA_CERT: ~

kube:
  external_ip: "192.168.77.77"
  storage_class:
    persistent: "persistent"
    shared: "shared"
  registry:
    hostname: registry.suse.de
    username: ""
    password: ""
  organization: cap
