apiVersion: v1
appVersion: 2.1.1
description: A Helm chart for deploying Stratos
home: https://stratos.app
icon: https://raw.githubusercontent.com/SUSE/stratos/master/deploy/kubernetes/custom/icon.png
keywords:
- Stratos
- Cloud Foundry
- Kubernetes
- Helm
maintainers:
- email: stratos-maintainers@suse.de
  name: Stratos Maintainers
name: console
sources:
- https://github.com/SUSE/stratos
version: 4.4.4
