---
{{- if and (eq (printf "%s" .Values.kube.auth) "rbac") .Values.kube.psp.nonprivileged }}
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "ClusterRole"
metadata:
  name: "{{ .Release.Namespace }}-psp-role-nonprivileged"
  labels:
    app.kubernetes.io/component: "{{ .Release.Namespace }}-psp-role-nonprivileged"
    skiff-role-name: "{{ .Release.Namespace }}-psp-role-nonprivileged"
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" | quote }}
    app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name (.Chart.Version | replace "+" "_") | quote }}
rules:
- apiGroups:
  - "extensions"
  resourceNames:
  - {{ .Values.kube.psp.nonprivileged | quote }}
  resources:
  - "podsecuritypolicies"
  verbs:
  - "use"
{{- end }}
